### ISSUE TITLE
expose upstream associated MAC randomization implementation on supported devices and enable it by default

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os_issue_tracker#1]

**Comment by dorakas** [comment]
Hey thestinger.

Doesn't the pixel 3 has full Mac random already build in

**Comment by thestinger** [comment]
Yes, as do other Pixel phones, but it's not enabled by default. That's the point.

**Comment by thestinger** [comment]
Associated MAC randomization is not the same thing as scanning MAC randomization.

**Comment by dorakas** [comment]
Pixel 3 does have associated mac randomization in the developer options. Or am I mistaken something

**Comment by thestinger** [comment]
> Yes, as do other Pixel phones, but it's not enabled by default. That's the point.

**Comment by thestinger** [comment]
Having a toggle in developer options isn't the desired outcome and neither is having it disabled by default. There isn't even a toggle in developer options in an unmodified AOSP build since it's a build configuration option that needs to be enabled. The issue is about what the title states: identifying the devices where this is already supported and exposing it for users, not in developer options, where it isn't even present right now either.

**Comment by slq32** [comment]
Isn't this as:
-adding

        <SwitchPreference
            android:key="wifi_connected_mac_randomization"
            android:title="@string/wifi_connected_mac_randomization"
            android:summary="@string/wifi_connected_mac_randomization_summary"
            settings:controller="com.android.settings.security.WifiConnectedMacRandomizationPreferenceController" />

to res/xml/security_dashboard_settings.xml , under some category,
-removing 


     protected void onDeveloperOptionsSwitchDisabled() {
         super.onDeveloperOptionsSwitchDisabled();
         Settings.Global.putInt(mContext.getContentResolver(),
                 Settings.Global.WIFI_CONNECTED_MAC_RANDOMIZATION_ENABLED, SETTING_VALUE_OFF);
         ((SwitchPreference) mPreference).setChecked(false);
    }

from src/com/android/settings/development/WifiConnectedMacRandomizationPreferenceController.java


-importing
     
     com.android.settings.development.WifiConnectedMacRandomizationPreferenceController;


in src/com/android/settings/security/SecuritySettings.java

-and finally adding

    controllers.add(new WifiConnectedMacRandomizationPreferenceController(context));


somewhere in the above file ? 

tested and it seems to be working for me ... no idea how to make it enabled by default though.

I am sure somebody could improve this ...

**Comment by dorakas** [comment]
Hahaha. Believe me @slq32 thestinger knows exactly how to do this. I doubt there is anything that he doesn't know about Android. It's the fact that people seem not to respect his work. What seems a very sad thing. Anyway thanks for the help sql32

**Comment by thestinger** [comment]
The standard support for this is now enabled and fully tested. It works well and simply needs to be enabled by default and the toggle moved to a more appropriate place, likely somewhere in the Wi-Fi settings menu. This would be a good starting point for a contributor to the project.

**Comment by thestinger** [comment]
Closing in favour of https://github.com/GrapheneOS/os_issue_tracker/issues/59.
