### ISSUE TITLE
Settings will crash when uninstalling other profile's app on main profile

### ISSUE THREAD

**Issue by expobar** [GrapheneOS/os_issue_tracker#104]
Steps to reproduce:
1. Try to uninstall other profile's app on the main profile 
2. After pressing uninstall, the app icon still remains.
3. Tapping the remaining app icon will result in crash.

**Comment by thestinger** [comment]
@expobar Is this still an issue on the latest release based on Android 10?

**Comment by expobar** [comment]
@thestinger looks like it's been fixed on Android 10.
