### ISSUE TITLE
make remembering per-network random MAC an opt-in network setting

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os_issue_tracker#106]

**Comment by lazerl0rd** [comment]
What's your opinion on AOSP's MAC Randomisation feature?

**Comment by thestinger** [comment]
This is about improving the standard associated MAC randomization to function the way the past GrapheneOS MAC randomization worked.

**Comment by lazerl0rd** [comment]
Ah, so it is for https://source.android.com/devices/tech/connect/wifi-mac-randomization but to give the user an option to "randomise each time, even for the same network". Thanks.
