### ISSUE TITLE
[Feature request] Network upload / download speed indicator

### ISSUE THREAD

**Issue by k3tju** [GrapheneOS/os_issue_tracker#110]
Hello!

If this is easy to implement, it would be nice to have an option like in LineageOS with the network indicator on the top bar.
https://github.com/LineageOS/cm_platform_sdk/blob/712ab4b03595899126897e43b8d6df473cd41770/cm/res/res/values/symbols.xml#L136

https://github.com/LineageOS/cm_platform_sdk/blob/8cad8e3c1318a693711f0a935f5863fdbb6430e2/sdk/src/java/org/cyanogenmod/internal/statusbar/NetworkTraffic.java#L333

**Comment by thestinger** [comment]
This isn't within the privacy and security scope of the project.

**Comment by JSchimmelpfennig** [comment]
One could argue that it increases the awareness how many data flowing right now through the air. If megabytes are transferred "without no reason" to the owner, this could indicate that an app does things it should not or the user forgot that he gave that permission.

It would be amazing to have that!
