### ISSUE TITLE
[Feature request] Possibility to fake data sent and/or cherry pick the data: ex. contacts

### ISSUE THREAD

**Issue by k3tju** [GrapheneOS/os_issue_tracker#114]
If I understood correctly this might be coming in the next AOSP right?
If it is not, it would be nice to have this for, at least contacts, but there is a way around currently and it might be interesting for people reading this issue.
I imagine that implementing such a feature would be very time consuming so it is worth using what we have available currently.

The current way around is to use the work profile functionality. Unfortunately, this seems bugged currently on GrapheneOS. At least for me it did not work. See #113.

**Comment by beerisgood** [comment]
As workaround you can use this app, so other apps can't read your contacts:
https://f-droid.org/en/packages/opencontacts.open.com.opencontacts/

**Comment by k3tju** [comment]
Thank you for the advice @beerisgood ! I will try it

**Comment by thestinger** [comment]
I want to approach this with profiles, not ad-hoc hacks for each form of data. Work profiles work fine on GrapheneOS. They aren't buggy and the full test suite for them passes. It's an issue with the third party app and how you're using it, not with GrapheneOS.

**Comment by thestinger** [comment]
Also, by profiles, I primarily mean user profiles, not work profiles. There are already some issues filed about improving profiles. Consider working on those. Isolated workspaces is the right approach to things like this, not an increasingly complex / arcane way of doing this on an ad-hoc basis for power users where it's incomplete, leaks information and is extremely prone to error.
