### ISSUE TITLE
[Feature request] Possibility to refuse, and possibility to fake the transmission of unique device identifier (IMEI or Mac address for instance) - currently silently transmitted 

### ISSUE THREAD

**Issue by k3tju** [GrapheneOS/os_issue_tracker#116]
As far as I understand, like in stock AOSP, unique device identifier are handled by applications without any prompt.
Would it be possible to have a feature offering the possibility to refuse, and possibility to fake the transmission of these?

On my previous phone, I was running PMP (http://www.protectmyprivacy.org/). Unfortunately, this requires the XPosed framework and opens up many security holes on a device.

**Comment by beerisgood** [comment]
Just wait for Android 10..

**Comment by thestinger** [comment]
> Possibility to refuse, and possibility to fake the transmission of unique device identifier (IMEI or Mac address for instance) - currently silently transmitted.

You can already deny the Phone permission. The issue isn't accurate.

> As far as I understand, like in stock AOSP, unique device identifier are handled by applications without any prompt.

That's not accurate.

> On my previous phone, I was running PMP (http://www.protectmyprivacy.org/). Unfortunately, this requires the XPosed framework and opens up many security holes on a device.

Client side checks injected into apps via Xposed fundamentally don't work. It's equivalent to adding security checks in the client side code in the browser. I hope it makes sense why it cannot work. The app can obtain the information via different client side code, even if it doesn't intentionally bypass this. If it does want to bypass it, it can easily detect and bypass the hooks directly too.

**Comment by thestinger** [comment]
The Phone permission also stops giving access to the IMEI in Android Q, but you can certainly already deny that today.

**Comment by thestinger** [comment]
The same things applies to other device identifiers which either started requiring the Phone permission in the past or are no longer accessible. Please do some research into it first.
