### ISSUE TITLE
Persistant `Customise your Pixel` message in Settings 

### ISSUE THREAD

**Issue by SimonBrazell** [GrapheneOS/os_issue_tracker#120]
Mentioned this on the [Reddit thread](https://old.reddit.com/r/GrapheneOS/comments/d4g627/grapheneos_2019091310_snapshot_targeting_android/f0bsd9m/), running the latest beta Android 10 build (QP1A. 190711.020.2019.09.13.10) on my Pixel (sailfish) and getting this persistent pinned prompt at the top of the Setting menu:

![screenshot](https://user-images.githubusercontent.com/16571951/64930748-e880b380-d876-11e9-9fab-8ae97e817ab1.png)

Tapping and selecting the prompt gives you the option to update your wallpaper but doing so does not dismiss the prompt.

**Comment by SimonBrazell** [comment]
This also has disappeared a rollback and then update again to Q.

**Comment by nutts0** [comment]
Please reopen this. Rollback and update didn't fix it on my 3xl
