### ISSUE TITLE
Calls & SMS are not coming through

### ISSUE THREAD

**Issue by SimonBrazell** [GrapheneOS/os_issue_tracker#121]
Pixel (sailfish) latest beta Android 10 build (QP1A. 190711.020.2019.09.13.10) both calls and SMS are not coming through. 

Phone is not ringing for calls, tested by calling it from another phone, it's ringing out and going to message bank without every indicating that it is ringing on the GrapheneOS device.

SMS messages are registered in the stock SMS (Messages) app but there is no notification raised when they do come through, can just see them when you access the app.

**Comment by SimonBrazell** [comment]
Issue still present on latest build `QP1A.190711.020.2019.09.18.14` is no one else experiencing this? Seems like a pretty big bug, certainly not something you would expect to see in a beta...

**Comment by thestinger** [comment]
What do you expect to see in a Beta snapshot release?

https://twitter.com/GrapheneOS/status/1172500358091935749

**Comment by thestinger** [comment]
Also not reproducible here and I haven't yet heard of anyone else encountering the same issue. Probably an issue with carrier configuration in AOSP for Q.

**Comment by SimonBrazell** [comment]
Guess I was expecting basic functions like phone calls and SMS to work but you're right I probably shouldn't expect anything from a beta.

From a [post](https://old.reddit.com/r/GrapheneOS/comments/d4g627/grapheneos_2019091310_snapshot_targeting_android/f0h7bg5/) from another user on Reddit it appears that these functions are working for a Pixel 2 on the same carrier as me (Telstra). I just tried restarting the phone in safe mode to rule out any apps and also had a look online for similar issues with Android Q where I found this [support comment](https://support.google.com/pixelphone/thread/13584442?msgid=14719447) with some suggestions. Do you think it's relevant that point 3. is not possible with this build? When I navigate to the `Caller ID & spam app` default setting it does not have the `Phone` app available as a selection.

**Comment by SimonBrazell** [comment]
Does the carrier configuration vary between builds or major versions? Because its working fine on the latest stable build, just not on the beta channel.

**Comment by thestinger** [comment]
Yes, it's different. You should try configuring the APN yourself and debugging it because you're the only person reporting a problem with this, and one person having this issue isn't going to block an eventual release. I also can't replicate it so there's nothing for me to work on here, if I even had time to deal with carrier specific issues, which I don't. The community needs to step up and contribute or carrier issues like this will just have to be accepted.

**Comment by SimonBrazell** [comment]
I understand that, I'm just not familiar with AOSP development at all so not really sure where to start with a problem like this, I did have a look through the code and could see some past commits where XML files were modified for Telstra carrier settings but it seems those files have since been removed or relocated elsewhere. I did also try modify some of the APN settings manually to no avail. I would love to contribute to this project but I feel there is a fairly large learning curve before I can be productive, as I currently only work with web technologies.

**Comment by SimonBrazell** [comment]
Something odd happened, I decided to go back to stable yesterday but then this morning switched back to the beta thinking I'd have a go at troubleshooting the problem only to find that the phone can now receive calls on the beta...

The Messages app is still not notifying me when I receive an SMS but this can be worked around by using Signal as the SMS app instead.
