### ISSUE TITLE
Can we connect GrapheneOS to Phone Hub on Chromebook ?

### ISSUE THREAD

**Issue by ghost** [GrapheneOS/os_issue_tracker#1211]
Hi community, I just bought a Chromebook. It is possible to display phone applications on ChromeOS, a bit like mirroring. But impossible to do this with my Pixel 6 on GrapheneOS.
When I press the phone icon in the ChromeOS taskbar, Androis does not appear.
Has anyone managed to do this ? Thank you

https://ibb.co/6N78ZSs

**Comment by flawedworld** [comment]
You might be able to do this with sandboxed Google Play. For support ask in our Matrix rooms: https://grapheneos.org/contact#community
