### ISSUE TITLE
Messaging: allow selecting text inside the selected message - missing commit?

### ISSUE THREAD

**Issue by ghost** [GrapheneOS/os_issue_tracker#1214]
Hello, today i was looking into selecting part of text in the messaging app and found out that this commit 

https://android-review.googlesource.com/c/platform/packages/apps/Messaging/+/1754232
https://android.googlesource.com/platform//packages/apps/Messaging/+/5062902b35499a88ebb7cb721101bad592b35ecb%5E1..5062902b35499a88ebb7cb721101bad592b35ecb/

 seems to be missing in grapheneos messaging app
https://github.com/GrapheneOS/platform_packages_apps_Messaging/blob/9ed990a3a8ace72a004f0d8ab26d6637204b94fa/src/com/android/messaging/ui/conversation/ConversationMessageView.java#L710

 it's strange because newer commits seems to be included?

**Comment by thestinger** [comment]
I can backport this from master for our next release.
