### ISSUE TITLE
disable Scudo on 64-bit where hardened_malloc is used

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os_issue_tracker#122]

**Comment by renlord** [comment]
From correspondence in IRC with @thestinger:

Not a problem right now because scudo is only used for a few processes in Android 10 (Q) and they are 32-bit.

It will become a problem in Android 11 (R) and have to make sure to disable globally on 64-bit.

**Comment by thestinger** [comment]
This is now crucial since Scudo is used everywhere on Android 10.

**Comment by thestinger** [comment]
Replaced by https://github.com/GrapheneOS/os_issue_tracker/issues/269 since this is now part of a baseline port of hardened_malloc to Android 10, since we won't even know if it's working until we deal with this.

**Comment by thestinger** [comment]
Replaced by https://github.com/GrapheneOS/os_issue_tracker/issues/269 since this is now part of a baseline port of hardened_malloc to Android 11, since we won't even know if it's working until we deal with this.
