### ISSUE TITLE
[android-prepare-vendor] vendor prepare script is broken on pixel 3a for API 29 / Android 10

### ISSUE THREAD

**Issue by Helios747** [GrapheneOS/os_issue_tracker#132]
If you run `extract-all.sh` against sargo and API 29, it fails to parse some json and exits prematurely.

Example, using the latest from the repo on branch `10` + @jtl999 's patch to fix downloading the image. Available in an open PR:

`sudo ./execute-all.sh  -f -y -d sargo -b QP1A.190711.020 -o /home/anthony/aosp/10`

It will download the factory image, OTA, and extract them fine. It will extract a few files, then spam the following for several seconds. 

`jq: error (at /home/anthony/aosp/android-prepare-vendor/sargo/config.json:531): Cannot iterate over null (null)`
`[-] json raw string array parse failed`

After that it will download another tool, spam the error again, and exit.

This is specifically for sargo, but the json for bonito is so similar I assume thats broken too. @jtl999 on the matrix channel confirmed this on their machine as well.

**Comment by thestinger** [comment]
This appears to be a local issue with your build environment. All I can suggest is trying again and making sure to use the latest android-prepare-vendor from the GrapheneOS `10` branch.

**Comment by Helios747** [comment]
Narrowed it down.

building a full vendor with `-f` reproduces this on my machine. Naked vendor does not. Given that GrapheneOS likely has no use for full vendor, this might not be worth spending time on.

**Comment by thestinger** [comment]
Full vendor is essentially unsupported in android-prepare-vendor at this time. If you wanted Google Play Services, etc. android-prepare-vendor is the right way to bundle that but it's just not currently working.

**Comment by thestinger** [comment]
Full vendor is essentially unsupported in android-prepare-vendor at this time. If you wanted Google Play Services, etc. android-prepare-vendor is the right way to bundle that but it's just not currently configured to be functional and I don't have an interest in it.

**Comment by Helios747** [comment]
Sounds good. Closing.
