### ISSUE TITLE
Mobile network LTE is not working

### ISSUE THREAD

**Issue by mayur-mb** [GrapheneOS/os_issue_tracker#136]
I have enabled mobile data, roaming is also enabled as my SIM is in roaming state. In preferred network 4G is selected. I can also see 4G in the status bar near network symbol. But there is an "X" in the network symbol as well. When I try to test ping it says network is unreachable. I tried different APN settings also. Still same result. 

If I use \*#\*#4636#\*#\*  in that

Voice Service: In Service
Data Service: Connected
Data Network Type: LTE
Voice Network Type: LTE

Even if I switch to 3G it shows same result.

In adb logcat I am get this logs

09-24 16:34:31.103  3911  3911 D DCT     : [0]onDataSetupComplete: SETUP complete type=default, reason:connected
09-24 16:34:31.103  3364  3407 E Netd    : Error adding route 0.0.0.0/0 -> 10.64.64.64 ppp0 to table 1010: Network is unreachable
09-24 16:34:31.104  3542  3661 E ConnectivityService: Exception in addRoute for gateway: java.lang.IllegalStateException: command '86 network route add 103 ppp0 0.0.0.0/0 10.64.64.64' failed with '400 86 addRoute() failed (Network is unreachable)'

09-24 16:34:32.151  3542  4982 D NetworkMonitor/NetworkAgentInfo [MOBILE (LTE) - 103]: PROBE_DNS connectivitycheck.gstatic.com 2ms FAIL
09-24 16:34:32.151  3542  4981 D NetworkMonitor/NetworkAgentInfo [MOBILE (LTE) - 103]: PROBE_DNS www.google.com 3ms FAIL
09-24 16:34:32.154  3542  4981 D NetworkMonitor/NetworkAgentInfo [MOBILE (LTE) - 103]: PROBE_HTTPS https://www.google.com/generate_204 Probe failed with exception java.net.UnknownHostException: w
ww.google.com: TLS-bypass resolution failed
09-24 16:34:32.154  3542  4982 D NetworkMonitor/NetworkAgentInfo [MOBILE (LTE) - 103]: PROBE_HTTP http://connectivitycheck.gstatic.com/generate_204 Probe failed with exception java.net.UnknownHos
tException: connectivitycheck.gstatic.com: TLS-bypass resolution failed
09-24 16:34:32.158  3542  4968 D NetworkMonitor/NetworkAgentInfo [MOBILE (LTE) - 103]: PROBE_FALLBACK http://play.googleapis.com/generate_204 Probe failed with exception java.net.UnknownHostExcep
tion: play.googleapis.com: TLS-bypass resolution failed
09-24 16:34:34.164  3542  4988 D NetworkMonitor/NetworkAgentInfo [MOBILE (LTE) - 103]: PROBE_DNS www.google.com 3ms FAIL
09-24 16:34:34.165  3542  4989 D NetworkMonitor/NetworkAgentInfo [MOBILE (LTE) - 103]: PROBE_DNS connectivitycheck.gstatic.com 3ms FAIL
09-24 16:34:34.167  3542  4988 D NetworkMonitor/NetworkAgentInfo [MOBILE (LTE) - 103]: PROBE_HTTPS https://www.google.com/generate_204 Probe failed with exception java.net.UnknownHostException: w
ww.google.com: TLS-bypass resolution failed
09-24 16:34:34.169  3542  4989 D NetworkMonitor/NetworkAgentInfo [MOBILE (LTE) - 103]: PROBE_HTTP http://connectivitycheck.gstatic.com/generate_204 Probe failed with exception java.net.UnknownHos
tException: connectivitycheck.gstatic.com: TLS-bypass resolution failed
09-24 16:34:34.172  3542  4968 D NetworkMonitor/NetworkAgentInfo [MOBILE (LTE) - 103]: PROBE_FALLBACK http://www.google.com/gen_204 Probe failed with exception java.net.UnknownHostException: www.
google.com: TLS-bypass resolution failed

I am working in Android 9.0 background with a LTE module. It is running stock android with WiFi disabled and only mobile network is enabled.

**Comment by thestinger** [comment]
> I am working in Android 9.0 background with a LTE module. It is running stock android with WiFi disabled and only mobile network is enabled.

To clarify something, this is about an issue with GrapheneOS, right? Can you clarify and expand on this part?

**Comment by mayur-mb** [comment]
The Android is running on stock OS. WiFi network is disabled as I only need LTE network.

**Comment by thestinger** [comment]
So it's not about GrapheneOS? I think you probably found the AndroidHardeningArchive issue tracker by mistake since that's the legacy issue tracker for https://grapheneos.org/.
