### ISSUE TITLE
Please make a version of this OS for smartwatches

### ISSUE THREAD

**Issue by shawneric** [GrapheneOS/os_issue_tracker#140]
I have a Samsung Gear S2 Smart Watch and wanted to ask if it's ever going to be possible that you guys can make a GrapheneOS version for this watch as well?

**Comment by thestinger** [comment]
@shawneric It won't be within the scope of the project for a long time. It's already an extremely broad project and there are extremely limited resources. It's in a very early state of development and isn't currently sustainable with the current set of supported devices and features. You can see in this issue tracker (https://github.com/GrapheneOS/os_issue_tracker/issues) that there's a huge amount of work to do including many issues tagged past-feature which are about restoring past changes or replacements for them. Contributions are desperately needed and expanding the scope just isn't in the cards right now, and won't be in the foreseeable future.
