### ISSUE TITLE
crashes when flipping camera from front to back or vice-versa

### ISSUE THREAD

**Issue by renlord** [GrapheneOS/os_issue_tracker#142]
When changing camera from front to back or vice-versa, call application (i.e. Wire, Signal or Whatsapp) often crashes, but the call still remains connected.

Again all permissions granted.

Using Pixel3XL.
Build Number: QP1A.190711.020.C3.2019.09.25.00

**Comment by n1m1** [comment]
Hello @renlord ,
are you still experiencing this problem? A few days ago I have noticed this issue in the tracker and I have done several tests with Signal and Whatsapp: I have not experienced any crash with such applications.

Cheers.

**Comment by thestinger** [comment]
You need to specify which device you're using for it to mean anything.

**Comment by n1m1** [comment]
You are right. And probably my post is absolutely not relevant since I am using a Pixel3a. Apologies for the noise.

**Comment by thestinger** [comment]
It's relevant but the device needs to be stated.

**Comment by renlord** [comment]
> You are right. And probably my post is absolutely not relevant since I am using a Pixel3a. Apologies for the noise.

Yes, its still an issue on Pixel 3XL.

**Comment by ddreth** [comment]
this also happens to me on pixel 3XL

**Comment by SinisterLeonard** [comment]
Can confirm that this still happens.
Device: Pixel 3 XL

**Comment by TheBiostarfly** [comment]
I'm experiencing the same problem. In addition the camera crashes when starting an app which uses the camera e.g. the camera app.
Device: Pixel XL 3

**Comment by dreth** [comment]
I can confirm that after update 2020.09.25.00 this is NOT happening for me anymore, i used to get crashes on apps that used the camera saying the camera can't  open on whatsapp, instagram and would require relaunching these app's camera options multiple times until it worked.

It would also happen when flipping the camera but i haven't experienced this since the last update which is great!

**Comment by renlord** [comment]
Still leaving it open, when toggling into night sight sometime ago, the phone just freezed and had to hard reboot.

**Comment by thestinger** [comment]
There are still camera issues, but this problem seems to be resolved across the devices.

**Comment by thestinger** [comment]
There appear to be some remaining memory corruption bugs uncovered by the hardened allocator(s), but this doesn't seem to trigger any.
