### ISSUE TITLE
Flashlight brightness customization

### ISSUE THREAD

**Issue by dd-dreams** [GrapheneOS/os_issue_tracker#1430]
Android 13 now provides API's for changing the flashlight brightness. Would be nice to add a bar similar to screen brightness when pressing on flashlight quicktile.
https://developer.android.com/reference/android/hardware/camera2/CameraCharacteristics#FLASH_INFO_STRENGTH_DEFAULT_LEVEL
https://developer.android.com/reference/android/hardware/camera2/CameraManager#turnOnTorchWithStrengthLevel(java.lang.String,%20int)

**Comment by thestinger** [comment]
Not planned.

**Comment by r3g-5z** [comment]
This is something upstream AOSP needs to implement.

**Comment by r3g-5z** [comment]
And just because the APIs exist does not mean the hardware is capable of it.

**Comment by dd-dreams** [comment]
> This is something upstream AOSP needs to implement.

@r3g-5z  Currently stock OS provides this. I believe its something the OS needs to implement.

**Comment by thestinger** [comment]
It will be provided when it's in AOSP.

**Comment by r3g-5z** [comment]
There are plenty of stock OS features not in AOSP that will eventually make it into AOSP. It's not something that needs to be implemented downstream.

**Comment by thestinger** [comment]
Stock Pixel OS ships a newer branch of SystemUI, etc. than what ships in AOSP releases because AOSP follows along major branches and does bug fix updates. They ship a more bleeding edge branch for their Play Store builds of these kind of apps.

**Comment by dd-dreams** [comment]
> It will be provided when it's in AOSP.

@thestinger it will take time. We're still waiting for customizing the UI colors feature since android 12 came out. Clearly its marketing to encourage users to move to stock OS by having more features than AOSP.

**Comment by thestinger** [comment]
No, it isn't, and please stop spreading weird misinformation here.
