### ISSUE TITLE
TOR browser permissions failure

### ISSUE THREAD

**Issue by sempervictus** [GrapheneOS/os_issue_tracker#144]
When starting the current version of orbot/torbrowser, the bootstrap fails with:
```
Error configuring tor: java.lang.SecurityException: Permission Denial: opening provider org.torproject.torbrowser.ui.hiddenservices.providers.HSContentProvider from ProcessRecord{915dce6 7855:org.torproject.torbrowser/u0a0} (pid=7855, uid=10000) that is not exported from UID 10078
```

**Comment by thestinger** [comment]
Seems to be an upstream issue:

https://trac.torproject.org/projects/tor/ticket/30607
https://trac.torproject.org/projects/tor/ticket/32001

I'd recommend contacting them about the status and addressing whatever systemic issues led to not supporting Android Q upon release, despite having many months of early access to the SDK and developer previews / betas.
