### ISSUE TITLE
Location not working in browser

### ISSUE THREAD

**Issue by ghost** [GrapheneOS/os_issue_tracker#145]
- I have given Vanadium access to location.
- I have given https://www.google.com/maps access to location.
- I have also given my city's metro site access to location for real-time bus arrivals, which uses Google as a backend for location.

**This should be enough to allow the sites to find my location, but they just infinitely attempt to locate me.**

- Telegram and OsmAnd **are both able** to locate me as they are using OpenStreetMaps.
- The Google Maps app from Aurora Store **is able** to locate me.
- The Google Maps Go app from Aurora Store **is unable** to locate me as it uses Vanadium.
- Tested Brave, being Chromium-based like Vanadium, which **is unable** to locate me.
- Tested Firefox, using Gecko, which **is able** to locate me.
- Tested https://browserleaks.com/geo in Vanadium, which **is able** to locate me, but it uses OpenStreetMaps instead of Google.

This leads me to believe it's something specifically wrong with WebView and Google location, considering Firefox works and the Google Maps native app works.

**Comment by thestinger** [comment]
Probably https://github.com/GrapheneOS/os_issue_tracker/issues/24.

**Comment by thestinger** [comment]
Some location users may only use low battery location initially, or something like that. I'd rather just have that existing issue about it unless it's shown this is a different issue.
