### ISSUE TITLE
[Feature request] Maximum battery charge level limiter

### ISSUE THREAD

**Issue by sbth** [GrapheneOS/os_issue_tracker#146]
Preface: I acknowledge that there are far more important things that need to be addressed in the ROM that impact user security, privacy and usability. I also acknowledge that the project is meant to be AOSP with hardening and that adding a single out-of-scope feature could be a slippery slope. However, I'd like to entertain the idea and perhaps hear the thoughts of the project developer.

Up until I ran GrapheneOS, my phone has always been rooted. There has been no reason for this other than to use programs such as the Magisk Advanced Charging Controller to limit the amount my battery can be charged to 80% in an attempt to extend my battery's lifespan. Obviously, since GrapheneOS disallows root (rightfully so, as it is indeed another attack surface), I no longer have this functionality. Is it in the interest of the developer to allow these security-friendly devices to have more longevity by implementing this feature? Or is this not even remotely on the radar, even once the important things have been (re)implemented?

I'd love to hear the community's opinion on this. :)

**Comment by beerisgood** [comment]
https://reddit.com/comments/cc5n5u/comment/etl0kb9

No need for such restriction

**Comment by sbth** [comment]
> https://reddit.com/comments/cc5n5u/comment/etl0kb9
> 
> No need for such restriction

Ah, perfect! Thank you for the reply. This is all I needed. :)

**Comment by beerisgood** [comment]
Reddit is your friend  :D
