### ISSUE TITLE
GPS not working

### ISSUE THREAD

**Issue by narduin** [GrapheneOS/os_issue_tracker#150]
Hello!
I installed GrapheneOS last week and I love it. Everything is working just fine except the GPS.
I read all I could find on gitHub and reddit about GPS bugs. I did a factory reset, did not install anything except [GPSTest](https://f-droid.org/en/packages/com.android.gpstest.osmdroid/) but nothing worked.

I installed GrapheneOS from the stable branch on a new Pixel 3. I tested the GPS from France, don't know if it's related to country usage.

Thanks a lot!

**Comment by bungabunga** [comment]
GPS is working fine on my Pixel 3.

**Comment by narduin** [comment]
Yep, I just checked and it does work.
Maybe yesterday's update fixed it!

Thanks :)

**Comment by bungabunga** [comment]
It worked on my device just fine even before yesterday's update.

**Comment by vafanassieff** [comment]
Hey just installed GrapheneOS on a brand new Pixel 3a and i cant get any gps position using GPSTest, i'm running the stable channel.

**Comment by thestinger** [comment]
GPS is working fine. Test with SatStat and make sure you're outside and able to receive a clear GPS signal.

**Comment by vafanassieff** [comment]
@thestinger Indeed i just needed to go outside, i'm a fool but with the measure in France with coronavirus i just had to sign a paper to go outside !

Thanks for reminding me that outside exists.
