### ISSUE TITLE
Both FairEmail and K9 crashing after upgrade to QP1A.191105.003.2019.11.04 on Pixel 3A XL and QP1A.191105.004.2019.11.04 on 2 XL

### ISSUE THREAD

**Issue by hkzlab** [GrapheneOS/os_issue_tracker#151]
Hello,
I'm suffering crashes on two applications since the upgrade to latest beta for Pixel 3A XL (QP1A.191105.003.2019.11.04.23) and Pixel 2 XL (QP1A.191105.004.2019.11.04.23).

Both the devices were updated from QP1A.191005.007.A1.2019.10.07.21 (2 XL) and (QP1A.191005.007.2019.10.07.21) via the internal updater (which used a delta update, I guess, as it was really fast to download).

FairEmail doesn't even start and crashes immediately, K9 starts if i clear the storage, but dies as soon as I setup an email account.

I tried uninstalling and reinstalling both applications. Attached are the logcat of my Pixel 3A XL during the crashes.
I know the hardening can make hidden issues emerge in the applications, but as I cannot discriminate between a genuine issue in the applications and a potential issue in the OS introduced by the update, I'm reporting this.

The issues seems to be somewhat tied to the webviews, at least by a quick look of the log files.

[fairemail-logcat.txt](https://github.com/GrapheneOS/os_issue_tracker/files/3809773/fairemail-logcat.txt)
[k9-logcat.txt](https://github.com/GrapheneOS/os_issue_tracker/files/3809775/k9-logcat.txt)

**Comment by nutts0** [comment]
I could also send logcat if needed. Same problem pixel 3xl

**Comment by bungabunga** [comment]
Many other apps are crashing too. Paypal, Twidere and many local apps. I believe it's the same issue.

My device is Pixel 3.

**Comment by thestinger** [comment]
Thanks, I'm working on resolving this and pushing out another release. I won't be pushing the current release to the Stable channel.

**Comment by kenzoboe** [comment]
Same issues here on Pixel 3A. 
Protonmail crashes as soon as I open an email, Twire crashes upon login.

**Comment by thestinger** [comment]
I've resolved this for the upcoming release which I'll push to the Beta channel in the next few hours. Hopefully, this takes care of all the regressions and it can be pushed out to the Stable channel later today.
