### ISSUE TITLE
[Feature Request] Unlock Dialer/Call App

### ISSUE THREAD

**Issue by Mark-A-Billy** [GrapheneOS/os_issue_tracker#154]
I'm experimenting with an app to score/handle spam calls. Because the dialer/call app is locked down, I can't use it in GrapheneOS, It works fine in LineageOS and stock Android. I have to believe that users interested in privacy might also be interested in dealing with scam callers and telemarketers.

**Comment by thestinger** [comment]
I don't know what you mean by locked down or unlock.

**Comment by Mark-A-Billy** [comment]
Thanks for the quick response. If I install an alternative dialer/phone app and go to select the "default phone app" page in settings, it won't show up as an option. It only shows the system default app. Phones running LineageOS and stock Android see it fine, so I assumed you might have locked it down for security reasons.

**Comment by thestinger** [comment]
Nope, it probably just doesn't support Android 10.

**Comment by Mark-A-Billy** [comment]
Sorry for the delayed response on my part. You could be right. That's a valuable insight. I'm going to check into this and ensure that what we're building will work for Android 10 users, which could be a serious issue. Wish I'd tried it out on Android 10 before flashing the phone to GrapheneOS. I'm not going back, but can run some Android Studio emulators to check on this.
