### ISSUE TITLE
Revoke special app permission for Wi-Fi control from apps by default

### ISSUE THREAD

**Issue by ph00lt0** [GrapheneOS/os_issue_tracker#1551]
In relation to my previous enhancement request (https://github.com/GrapheneOS/os-issue-tracker/issues/1312) for making the permission more visible, I would like to request to revoke the the Wi-Fi control permission of apps all together.

I see many apps like banking apps, Google Play, Google Play Services, Google Maps, etc getting installed with this permission enabled by default. It is completely unclear to me why they would need this and neither does the functionality change by disabling it. I have not found a single app that shows different behavior after revoking this permission. The permission does however seem invasive to me and I see few cases this actually would be necessary (setting up iot devices with their own Wi-Fi channel). 

Given that many apps like banking apps and the like request and obtain the permission without users knowledge I request to revoke the permission to protect the user until android will have a granting request like it has with notifications since android 13.

**Comment by lukashoracek** [comment]
Google Play Services might need that permission for working network location

**Comment by thestinger** [comment]
Location data including nearby Wi-Fi networks isn't available without the Location permission. Some things need a combination of multiple permissions. Wi-Fi control permission doesn't give access to any sensitive location data without the Location permission too.

**Comment by thestinger** [comment]
Location requires Location permission and gives access to location data. Our sandboxed Google Play compatibility layer is only relevant to apps requesting location directly from Play services geolocation API instead of the OS geolocation API.
