### ISSUE TITLE
remove OldNetworkTimeUpdateService from source tree

### ISSUE THREAD

**Issue by renlord** [GrapheneOS/os_issue_tracker#158]
OldNetworkTimeUpdateService is no longer used by SystemServer and should be removed.

The only reference to it is at `frameworks/base/services/java/com/android/server/SystemServer.java#1653`.

And at `frameworks/base/services/java/com/android/server/SystemServer.java#1443` using NewNetworkTimeUpdateService is explicitly set to true.

**Comment by thestinger** [comment]
I'd rather just leave it around and let upstream clean up the code.
