### ISSUE TITLE
Merge scramble PIN layout

### ISSUE THREAD

**Issue by dngray** [GrapheneOS/os_issue_tracker#162]
If we could take the [scrambled PIN](https://review.lineageos.org/q/Add+option+to+scramble+pin+layout+when+unlocking) feature from LineageOS that would be great. I do believe this does [improve the security of digit PINs](https://www.schneier.com/blog/archives/2012/01/improving_the_s.html).

- [[256190]: Settings: Add option to scramble pin layout when unlocking (1/2)](https://review.lineageos.org/c/LineageOS/android_packages_apps_Settings/+/256190)
- [[256191]: Keyguard: Add option to scramble pin layout when unlocking (2/2)](https://review.lineageos.org/c/LineageOS/android_frameworks_base/+/256191)

**Comment by dngray** [comment]
Note, I am new and I have not got a build environment ready, so that's why I did  not do a PR myself. I would not feel comfortable doing so without testing first. (I am acquiring parts for my new personal build server though.)

**Comment by thestinger** [comment]
It's one of the past GrapheneOS features with a shared origin for the code.

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/os_issue_tracker/issues/68

**Comment by thestinger** [comment]
It needs to be done with SecureRandom among other changes. See the past GrapheneOS version of it.
