### ISSUE TITLE
Wi-Fi: real MAC not provided. Maybe MAC randomization related

### ISSUE THREAD

**Issue by beerisgood** [GrapheneOS/os_issue_tracker#167]
I try all solutions [here](https://github.com/GrapheneOS/os_issue_tracker/issues/165) but can't get my original MAC for my Wi-Fi. The systeminfo under "about" list the real one but even if a create new wifi connection, i doesn't get the real one.

Only a random MAC which doesn't change after use the workaround.

After the new 2020.01.06.21 update I can't update to my wifi (which use profiles based on MAC). The problem was that my device send a new MAC.
I then see that randomization was enabled, even that I disable that in the past for my Wi-Fi.

Any try to sending the real MAC wasn't successful. Even if I config that my real MAC should be send, it doesn't work. The only thing what works is that a random MAC is generated and it doesn't change to another random but that's not equal to the real device MAC

**Comment by thestinger** [comment]
cc @renlord

**Comment by renlord** [comment]
Have you tried selecting the "Use device MAC" option?

Otherwise, can you use screencast to record how you were able to produce this bug, so I can re-produce it on my end?

**Comment by beerisgood** [comment]
Like I wrote in the other thread, I use of course the option. Same like before the update - even that the update reset the option to using random MAC.

I will add a record

**Comment by beerisgood** [comment]
Here the screenshots:
![photo_2020-01-10_17-22-11](https://user-images.githubusercontent.com/9625159/72168771-b830c800-33c5-11ea-94ed-1167adbe89bd.jpg)

![photo_2020-01-10_17-22-11 (2)](https://user-images.githubusercontent.com/9625159/72168716-96cfdc00-33c5-11ea-8a8d-31e85e02eb5c.jpg)

**Comment by renlord** [comment]
@beerisgood the problem at the moment is the `array.xml` file that list options for the setting menu has not been translated to other languages yet. I got to figure out how to translate the english options to 86 other languages.

**Comment by beerisgood** [comment]
I can help with translation to German if needed

**Comment by renlord** [comment]
workaround: https://github.com/GrapheneOS/platform_packages_apps_Settings/pull/7

**Comment by beerisgood** [comment]
Fair enough. If you want help with translation in future, I will help

**Comment by thestinger** [comment]
Resolved for the next release.
