### ISSUE TITLE
Exclude the real MAC from random generating

### ISSUE THREAD

**Issue by nutts0** [GrapheneOS/os_issue_tracker#168]
Maybe the real MAC could be excluded from being generated with random setting. This would prevent accidentally leaking the real MAC.

**Comment by renlord** [comment]
the real MAC address is also an element in the set of all possible MAC addresses.
Why is this an issue?
How can an adversary even differentiate between a real/non-real MAC address if so?

**Comment by nutts0** [comment]
@renlord 
> the real MAC address is also an element in the set of all possible MAC addresses.

This is the the problem. It could be generated randomly and be the real MAC. Threat model is not being abke to prove that this particular device connected to an AP that monitors the connections. When the real MAC of the device can't be randomly generated this evidence can't be provided.

**Comment by renlord** [comment]
> For example I have set "always random MAC". Walk into the Turkish consulate use the free wifi and my device randomly generates my true MAC address. Minutes later some Saudis murder someone in there and my true MAC is connected to the AP. I become a suspect.

1 in 10 trillion chance of re-generating the real device MAC and an adversary simply cannot tell if the observed MAC address is real or unreal at the first place. The only way to inspect the 'realness' of a MAC address is to obtain the suspect's device physically.

I still don't see any merits of doing this additional check and think it is likely to cause more harm than good.

**Comment by nutts0** [comment]
All right. Closing this because if it could do more harm that good it isn't useful.
