### ISSUE TITLE
Accent colour option

### ISSUE THREAD

**Issue by w3bb** [GrapheneOS/os_issue_tracker#170]
On the stock Pixel 3XL ROM and LineageOS you can change the accent colour. The notification menu for example sticks out like a sore thumb with most colour schemes might set up. Being able to change this would be incredibly nice.

**Comment by thestinger** [comment]
Something like this isn't going to receive any attention from a privacy / security hardening project. Send a pull request enabling whatever it is you want if it's simply a configuration option. It's not a valid issue for the tracker though.
