### ISSUE TITLE
OsmAnd - no navigation voice on Google Pixel 3a running GrapheneOS

### ISSUE THREAD

**Issue by qubecub** [GrapheneOS/os_issue_tracker#172]
I've came across the isssue: There is no OsmAnd navigation voice on Pixel 3a running GrapheneOS.

I've got all default OsmAnd settings, and double checked that TTS voices are properly selected and sound enabled, OsmAnd doesn't do navigation voice at all. Just keeps silent.

**Comment by qubecub** [comment]
Update; 
According to OsmAnd support specialist GrapheneOS might not have TTS engine installed. 
I think that's actually what's causing the problem with silent navigation. 
Can you suggest an open source TTS engine I could use on GrapheneOS?

**Comment by beerisgood** [comment]
As you already figure out that is a osmand problem. You can use the Magic Earth app which works.

As alternative to that you can install Google TTS

**Comment by thestinger** [comment]
You need to install a TTS implementation.
