### ISSUE TITLE
PIN scrambling option only takes effect from admin profile

### ISSUE THREAD

**Issue by ineshi2** [GrapheneOS/os_issue_tracker#173]
I made a suggestion to the PIN scrambling feature to allow other user profiles to set PIN scrambling options for their own profile: https://github.com/GrapheneOS/platform_packages_apps_Settings/pull/8#discussion_r367050243. The reasoning behind this was that each profile was able to set their own lock screen security settings, so each profile should be able to control whether they want PIN scrambling.

I tested this in the QQ1A.200205.002.2020.02.04.01 release. PIN scrambling option only takes effect in the admin profile, and what the admin uses for the setting is the same for all profiles. Other non-admin profiles see the option to set PIN scrambling, but setting that option has no effect.

**Comment by ineshi2** [comment]
@renlord

**Comment by thestinger** [comment]
@renlord To match how this worked before, the setting should be hidden for non-admin users.

**Comment by thestinger** [comment]
Supporting a per-profile setting is a further enhancement requiring moving away from using a system property to another mechanism like secure settings. The correct way to do it needs to be researched and it should probably copy another lockscreen-related setting.
