### ISSUE TITLE
Brightness and graphics issues on Pixel 3A

### ISSUE THREAD

**Issue by w0ken** [GrapheneOS/os_issue_tracker#177]
Hello. I noticed that swiping the screen when there are black colored elements present (e.g. icons, images, apps in the switch apps screen, the quick settings menu in dark mode) there's a brief dark blue trail left behind those elements. This is related to the level of display brightness. At 100% it's not visible at all, but lowering it past this point makes this effect appear. The lower the brightness the stronger the effect becomes. I recorded the screen with an app with the hopes of providing evidence, but the video looks flawless on my PC.

**Comment by MaroonedAnchor** [comment]
Hi W0ken, that is the impact of having an OLED screen and would be present regardless of operating system used. It is sometimes referred to black crush or black smear. Hope this helps!

**Comment by w0ken** [comment]
Hi MaroonedAnchor, and thanks. Being my first device with an OLED display, I was clueless about this fact.

**Comment by MaroonedAnchor** [comment]
> Hi MaroonedAnchor, and thanks. Being my first device with an OLED display, I was clueless about this fact.

No problem! It’s a common complaint since OLED usually costs more but it is a trade off to get deeper blacks. Feel free to close this issue.

**Comment by thestinger** [comment]
The screen on the Pixel 3a is also not on the same level as the Pixel 3. It's one of the trade-offs for the cheaper device, like the lack of the Pixel Visual Core, which means no HDR+ on GrapheneOS, etc.
