### ISSUE TITLE
issues/improvements related to Setup wizard

### ISSUE THREAD

**Issue by empratyush** [GrapheneOS/os_issue_tracker#1774]
We have few issues/improvement related to setup wizard app. 
This is everything in one place in order of priority from max to min.

1. ~~[Do not enable Wi-Fi on creation of secondary profile](https://github.com/GrapheneOS/os-issue-tracker/issues/1097)~~
2. [Deprivilege SetupWizard, or make it not share android:uid with android.uid.system (uid 1000)](https://github.com/GrapheneOS/os-issue-tracker/issues/901)
3. [Setup wizard: Some language/location options are not available](https://github.com/GrapheneOS/os-issue-tracker/issues/799)
4. [add optional system navigation gesture tutorial to the end of the setup wizard](https://github.com/GrapheneOS/os-issue-tracker/issues/731)
5. [SetupWizard should ensure that the device has a locked bootloader ](https://github.com/GrapheneOS/os-issue-tracker/issues/576)

**Comment by r3g-5z** [comment]
1 and 2 are done now
