### ISSUE TITLE
Use randomized MAC always not working on first connection

### ISSUE THREAD

**Issue by Jawshy** [GrapheneOS/os_issue_tracker#178]
### Bug description
On the first connection to a Wi-Fi network with privacy set to use randomized MAC always will use the device's true Wi-Fi MAC address. A workaround is to reconnect to Wi-Fi. 

### Steps to reproduce
1. Go to settings > network and internet > Wi-Fi > saved networks > choose a network > set privacy to use randomized MAC always (default)
2. Turn Wi-Fi off and restart device. 
3. Turn Wi-Fi on and reconnect to the same network. 

**Actual result:** The MAC address for the connected network is the device's true MAC address. 
**Expected result:** The MAC address for the connected network is a randomly chosen MAC address. 

### Screenshots
![GrapheneOS-network-details](https://user-images.githubusercontent.com/10876578/75126908-fbb06e80-56b3-11ea-9e6f-8f766315a472.png)
![GrapheneOS-about-phone](https://user-images.githubusercontent.com/10876578/75126905-f8b57e00-56b3-11ea-99bb-13a3ffcdea13.png)

### Device info
**Device:** Google Pixel 3a XL (aosp_bonito)
**Android version:** 10 (2020.02.07.19, QQ1A.200205.002.2020.02.07.19)

**Comment by thestinger** [comment]
cc @renlord

**Comment by renlord** [comment]
The error was that the code previously generated a random mac address, saved it to the volatile map, but failed to set the new mac address in config.

The workaround worked since it would directly probe the map.
