### ISSUE TITLE
Dialer doesn't show missed calls & Phone doesn't re-connect to mobile network

### ISSUE THREAD

**Issue by beerisgood** [GrapheneOS/os_issue_tracker#181]
If i get a call and have for some reason no connection, - like no signal at all or phone doesn't reconnect to new cell tower, then the Dialer app doesn't show any feedback.
It only display a missed call if phone have connection to tower.
This isn't a big problem, if mailbox is activated. Then a sms show the missed call info at least.

But a more bigger problem is that the phone doesn't re-connect to mobile network, even if mobile internet works. But no (**in- and outcomming**) SMS or calls are possible before flymode was activated. Only mobile network works in my case then.

I can reproduce this every time.
My provider is German o2 (Drillisch)

**Comment by beerisgood** [comment]
I think I found a solution for my problem:
Under settings -> network & internet -> mobile network -> extended (at bottom) -> disable "choice network automatically" (if I translate that correctly from German).

Then I got a notification if phone ist not any longer connected with cell tower.
So at least I got a info, even if the automatically reconnect would be better of course.

**Comment by thestinger** [comment]
> Dialer doesn't show missed calls

I don't think it's supposed to do that.

> But a more bigger problem is that the phone doesn't re-connect to mobile network

File a new issue about this if it's still a problem. Each issue report should be for one issue.
