### ISSUE TITLE
add built-in support for blacklisting domains via the local DNS resolver

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os_issue_tracker#184]
Domain-based filtering can be done without this by configuring a custom Private DNS server or a local DNS service provided by a VPN service app (does not require the app to intercept any traffic). However, it would be nice to support custom local blacklists.

This should be efficient, unlike a hosts file, i.e. it should actually use an existing cache or a new hash table.

Private DNS isn't compatible with domain-based apps, since the DNS traffic is passed through them encrypted. This means users are pushed to disable Private DNS by the apps, and they generally won't provide their own implementation of encrypted DNS.

**Comment by renlord** [comment]
Do you want a user-facing app to allow users to add/remove domains?

**Comment by thestinger** [comment]
It should probablybe in the Settings app whether or not it's implemented as a separate app, similar to Updater.

**Comment by Kein** [comment]
Could DNSCrypt service be used as a local resolver? It can even mimic DOH server for Private DNS and already has built-in extended blacklist support or cloaking.

**Comment by thestinger** [comment]
That doesn't make sense as a way of implementing this.

**Comment by thestinger** [comment]
It's not wanted. The existing DNS-over-TLS implementation is fine and we don't want to add a bunch of complexity for bikeshedding it, sorry.

**Comment by Mattrazol** [comment]
When will this feature be implemented? Is there a roadmap for it?

**Comment by thestinger** [comment]
No, and it won't necessarily be implemented.

**Comment by Mattrazol** [comment]
> No, and it won't necessarily be implemented.

Why? Isn't it important to block malicious trackers websites? Especially for those that are using a VPN and they don't want to use DNS-over-TLS because as it's stated in the FAQ of the website "If you're using a VPN, you should consider using the standard DNS service provided by the VPN service to avoid standing out from other users."

**Comment by thestinger** [comment]
> Isn't it important to block malicious trackers websites?

To what end? Enumerating badness is not a viable approach to privacy. It's not our approach to it. The purpose of this issue is not a proposal to use that approach.

> Especially for those that are using a VPN and they don't want to use DNS-over-TLS because as it's stated in the FAQ of the website "If you're using a VPN, you should consider using the standard DNS service provided by the VPN service to avoid standing out from other users."

In the same way, any kind of filtering can be detected and tested just as a service / website can identify your configured DNS servers.

**Comment by thestinger** [comment]
Enumerating badness is not our approach and the reasoning for adding this would have been harm reduction since users want it and are going to do it via third party software or DNS. However, whether people realize it or not yet, content filtering like this is being obsoleted by gradual ecosystem changes in the approach to serving ads, etc.

This will become increasingly less useful due to DNS record cloaking. CNAME cloaking can also be upgraded to extensions like ALIAS/ANAME records where the authoritative DNS server resolves the name and caches it rather than having clients resolve the CNAME.

I would prefer to have people do this via the existing DNS-based approach rather than integrating something counter to our approach and misleading for users.
