### ISSUE TITLE
Tapping advance under network details disconnects Wi-Fi

### ISSUE THREAD

**Issue by Jawshy** [GrapheneOS/os_issue_tracker#187]
### Bug description
Tapping advance under network details disconnects Wi-Fi. 

### Steps to reproduce
1. Tap settings > network and internet > Wi-Fi> [connected network] > advanced
2. Notice that the Wi-Fi network is disconnected. 

**Actual result:** Shows advanced network details and disconnects Wi-Fi. 
**Expected result:** Shows advanced network details without disconnecting Wi-Fi. 

### Device info
**Device:** Google Pixel 3a XL (aosp_bonito)
**Android version:** 10 (2020.03.04.16, QQ2A.200305.002.2020.03.04.16)

**Comment by renlord** [comment]
The problem was due to frontend and backend not agreeing on RANDOMZATION_ALWAYS values, so everytime the fragment is expanded, it behaves asif the randomization setting has been set to a new value.
