### ISSUE TITLE
Notification-bar keeps pulling down for a few seconds after unlock (often) and during phonecalls (always)

### ISSUE THREAD

**Issue by HairDownThere** [GrapheneOS/os_issue_tracker#188]
Bar disappears on its own after few seconds, gestures on fingerprint-scanner are disabled, pixel 3a. Any ideas?

**Comment by HairDownThere** [comment]
Can reproduce this behaviour, when tapping the status bar while being on the home screen. Notification-bar comes down and flips right back up again. Can somebody confirm this on their device please? Thanks

**Comment by thestinger** [comment]
If you tap on the status bar, it's supposed to do that. It's the design of the UI.

**Comment by thestinger** [comment]
It works the same way in the stock OS and it's not a bug. GrapheneOS isn't going to be redesigning how the UI works.

**Comment by HairDownThere** [comment]
Behaviour ist the same when tapping, not saying it doesn´t do it on it´s own on unlock, but okay ...
