### ISSUE TITLE
Expanding advanced network settings while connected to wifi results in reconnection

### ISSUE THREAD

**Issue by leinsburg** [GrapheneOS/os_issue_tracker#189]
Steps to reproduce:
1. Connect to a wireless AP
2. Settings > Network & internet > Wifi > AP > AP details > Advanced

Device will disconnect before reconnecting, causing a new device MAC address to be generated, if set to "randomized always".

**Comment by thestinger** [comment]
See https://github.com/GrapheneOS/os_issue_tracker/issues/187, this has been fixed already in the development branch.

**Comment by leinsburg** [comment]
Oops, my bad.
