### ISSUE TITLE
stable release manifest should reference revisions by hash instead of tag to avoid needing further signature verification

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os_issue_tracker#191]
At the moment, it's necessary to verify the signature of the tags across all of the repository after syncing. It would be better to refer to revisions by hash instead of by tag to avoid needing more than verifying the signature of the manifest. This will simply fetching and building a stable release.

**Comment by valldrac** [comment]
Please review https://github.com/GrapheneOS/script/pull/2

**Comment by thestinger** [comment]
This is implemented.
