### ISSUE TITLE
Hotspot only works on 2.4 GHz

### ISSUE THREAD

**Issue by w0ken** [GrapheneOS/os_issue_tracker#192]
Hi. The 5 GHz preferred band option to make a hotspot doesn't work. When the hotspot is activated with this option selected it will still use the 2.4 GHz band. This happens on the Pixel 3a with the latest update.

**Comment by TheDuchy** [comment]
I can confirm this bug on the Pixel 3a XL with the latest update. The device uses the 2.4 GHz band even when the 5GHz one is set as preferred.

**Comment by thestinger** [comment]
Is this still an issue on Android 11?

**Comment by TheDuchy** [comment]
I don't have the means to test it out properly on a 5GHz capable machine, but I can confirm that the AP shows up on a 2.4GHz-only receiver. Maybe it has something to do with the new wording: "5.0 GHz Band preferred".

**Comment by w0ken** [comment]
It still is. Tested just now.

**Comment by thestinger** [comment]
So wait, are you saying that 5GHz doesn't work or that 2.4GHz is still there when 5GHz is used? 2.4GHz still being present isn't a problem itself.

**Comment by w0ken** [comment]
I found what's going on. The '5Ghz band preferred' option is actually 2.4Ghz, but with channel bonding. It uses 40mhz channel width versus the 2.4Ghz option which uses 20mhz. And of course it also uses the standard 2.4Ghz 1-11 channels. I don't have another Android device to see if this is a standard behavior, or other devices actually offer real 5Ghz using proper channels, 36 and above.

**Comment by thestinger** [comment]
It's possible that the UI options are just screwed up because they are meant to be adjusted per-device.

**Comment by thestinger** [comment]
@w0ken Also, as I said earlier "5GHz preferred" indicates dual band support. It does not mean that 2.4GHz will be disabled. This earlier comment is not indicative of an issue:

> I don't have the means to test it out properly on a 5GHz capable machine, but I can confirm that the AP shows up on a 2.4GHz-only receiver. Maybe it has something to do with the new wording: "5.0 GHz Band preferred".

There is a dual band support on current devices. Providing a 5GHz hotspot does not imply not providing 2.4GHz at the same time. Presence of 2.4GHz when preferring 5GHz does not indicate a bug.

**Comment by thestinger** [comment]
Which device are you on that this doesn't work? I've tested on a Pixel 4 and with 5GHz preferred, a Pixel 3 connecting to the network ends up using 5GHz. It still broadcasts the SSID on 2.4GHz. It's just how it works. It's dual band.
