### ISSUE TITLE
Seedvault doesn't provide Nextcloud option

### ISSUE THREAD

**Issue by 1989gironimo** [GrapheneOS/os_issue_tracker#195]
Tried the new seedvault app and I think it's really a step forward, but saving the backup or on a thumbdrive isn't really convenient.
In the seedvault repo there was a open ticket regarding cloud support which was closed today and that means it should be supported.. 
So - does seedvault integrated in GrapheneOS don't provide that option?

[Here's the issue from the seedvault repo.](https://github.com/stevesoltys/seedvault/issues/12)

**Comment by thestinger** [comment]
GrapheneOS has the latest release of Seedvault. Read the full thread that you're linking to there. Seedvault supports arbitrary storage provider backends. The cloud storage app needs to implement a storage provider and it will show up as an option in Seedvault. That thread links to https://github.com/nextcloud/android/pull/3905 about this being implemented in Nextcloud. Perhaps you aren't using a recent enough release of Nextcloud. It's not a GrapheneOS issue though.

**Comment by renlord** [comment]
This is completely untrue. I am using nextcloud to store backups at the moment.

**Comment by 1989gironimo** [comment]
> GrapheneOS has the latest release of Seedvault. Read the full thread that you're linking to there. Seedvault supports arbitrary storage provider backends. The cloud storage app needs to implement a storage provider and it will show up as an option in Seedvault. That thread links to [nextcloud/android#3905](https://github.com/nextcloud/android/pull/3905) about this being implemented in Nextcloud. Perhaps you aren't using a recent enough release of Nextcloud. It's not a GrapheneOS issue though.

Using Nextcloud 18.0.2 on my server and 3.10.1 from F-Droid, so I can't really confirm your statement regarding an outdated version, but I'll ask the seedvault devs what might be the issue. Thanks nonetheless! :)

**Comment by grote** [comment]
Just stumbled over this issue and want people to know that Nextcloud support is rather experimental and I wouldn't trust it with my backups as it has severe issues I am currently addressing. Example: https://github.com/nextcloud/android/issues/6726
