### ISSUE TITLE
option to uninstall vanadium

### ISSUE THREAD

**Issue by h2dden** [GrapheneOS/os_issue_tracker#197]
add the option to uninstall vanadium

calendar app is also a very good candidate: such a crapy app

**Comment by beerisgood** [comment]
Doesn't make sense. Vanadium ist most hardened browser.

Also you can disable calendar app. And for simple tasks, it just works. Without crap features

**Comment by h2dden** [comment]
I will never question the security features of vanadium, but the ability to uninstall an app is always a big plus. 
A particar use case could be: an inexperienced user (i.e. child) which would use graphene os to communicate via voice, email, xmpp but not being able to browse the internet (unsafe space).
Irrespective of this particular use case, the option to uninstall any app should be there, especially since in case of vanadium it can be reinstalled with ease.

**Comment by thestinger** [comment]
You can disable system apps. That's equivalent to uninstalling them.

If you want to lock down a profile, use device management.
