### ISSUE TITLE
Media Player UI leaks to other user profiles

### ISSUE THREAD

**Issue by matchboxbananasynergy** [GrapheneOS/os_issue_tracker#2021]
When you're playing audio on any profile, and switch profiles, the media player UI persists on the other profile as well. This happens both for when you're playing something on the owner profile and switch to a secondary user profile, and when you're playing something in a secondary user profile and switch to owner.

Furthermore, in some cases, it is possible to get the media player to actually play audio that originates from another profile in the other profile (For example, you can get the media player from owner to play audio in secondary profile or vice versa), but that is very inconsistent and I've not found a way to consistently reproduce that.

This seems to have started with the latest beta, and is very likely an upstream AOSP QPR2 bug that went unnoticed because it requires secondary user profiles to be triggered.

**Comment by Metr0pl3x** [comment]
Can confirm, replicated with AntennaPod, paired by Bluetooth to car head unit.

**Comment by Metr0pl3x** [comment]
I resolved this by going to Settings and Pin Media Player making sure all users adhered to the Owner with toggles off.

**Comment by ResurFace382500000** [comment]
> This seems to have been addressed upstream and is no longer reproducible on GrapheneOS.

I can still reproduce this issue on my device

**Comment by ResurFace382500000** [comment]
> > > This seems to have been addressed upstream and is no longer reproducible on GrapheneOS.
> > 
> > 
> > I can still reproduce this issue on my device
> > Can we reopen this issue?
> 
> This is a feature not an issue. Why is it an issue to you?

?

**Comment by ResurFace382500000** [comment]
> [@ResurFace382500000](https://github.com/ResurFace382500000) Can you file a new issue with a full description of how you cause it including the app and how you switch users?

no prob
