### ISSUE TITLE
casting not working

### ISSUE THREAD

**Issue by pjvleeuwen** [GrapheneOS/os_issue_tracker#212]
Might be my misunderstanding, might be broken, please help...

I have a Chromecast model NC2-6A5 and my Huawei P10 (stuck at Android 7) can cast from the Google YouTube app and cast the screen via the Google Home app.

With my Pixel 3 XL with a recent GrapheneOS I cannot cast, so it seems:
When I click "cast" in the notification area I get a popup "cast screen to device" which keeps spinning "searching for devices...". Both the P10 and the Pixel are connected to the same WiFi AP.

I did disable some permissions for a couple of apps. Now I think I might have disabled something too much. Which app is relevant for this casting functionality? Any other suggestions what might cause this or how I might go about debugging it?

Without the Google YouTube app I intended to use NewPipe, but that does not provide casting itself. Casting the whole device might be an alternative. I am also interested to learn about alternative ways to put the YouTube content on the TV (for when I need to entertain the kids) :-)

**Comment by thestinger** [comment]
You need to use an app like VLC implementing this since GrapheneOS doesn't include Play Services which is what provides the Chromecast implementation on the stock OS.

**Comment by pjvleeuwen** [comment]
That clears it up, thanks!
