### ISSUE TITLE
Explicitly mention that disabling native code debugging can reduce app compatibility

### ISSUE THREAD

**Issue by matchboxbananasynergy** [GrapheneOS/os_issue_tracker#2125]
Recently, I've seen a few cases where people will break apps by disabling native code debugging without understanding that it will make some apps stop working.

Under the setting, there should be a sentence like "disabling this may reduce app compatibility", so that people are aware.

It is mentioned in the docs, but people won't always read those or may forget.

Perhaps this can be done as part of moving the toggle to ExtSettings, if it hasn't already been migrated.

**Comment by muhomorr** [comment]
Addressed by https://github.com/GrapheneOS/platform_packages_apps_Settings/pull/172
