### ISSUE TITLE
"Block connections without VPN" option gets unset when multiple users use VPNs

### ISSUE THREAD

**Issue by cyanlemons** [GrapheneOS/os_issue_tracker#213]
I have five users on a GrapheneOS installation. Each user has a different VPN profile. All of these users will initially have both the options "Always-on VPN" and "Block connections without VPN" enabled.

I've noticed that throughout normal use, right after switching between users, I will briefly see the following notification:
```
Android System
Disconnected from always-on VPN
Change network or VPN settings
```
This notification will disappear after a few seconds. However, once I check the settings for the same VPN profile, the option "Block connections without VPN" will now be disabled, whilst the "Always-on VPN" remains enabled.

This issue does not affect connectivity or even the VPN connection itself. All the various VPN profiles work as expected. The only problem is that the option always gets unset. I can consistently reproduce this issue simply by alternating through the various users. If I switch through each user, one after another, by the time I get back to the start of the cycle, the first user will have had it's "Block connections without VPN" option reset.

I originally believed this to be an issue with my code when working on an Orbot alternative as previously discussed in #210. However, I have reproduced this problem after removing all my VPN profiles and replacing them with new unrelated VPN profiles for the vanilla WireGuard client for Android.

I am using a Pixel 3a on the latest stable build (QQ2A.200501.001.B2.2020.05.05.02).

**Comment by thestinger** [comment]
This looks like an upstream bug but it might be fixed when we ship https://github.com/GrapheneOS/os_issue_tracker/issues/183.

**Comment by cyanlemons** [comment]
I thought that it may be related as well, but I was under the impression this was already implemented as the [2020.04.13.21 release](https://grapheneos.org/releases#2020.04.13.21) includes "enable VPN lockdown by default" – or am I misunderstanding something here?

If I simply need to enable the beta channel, I'd gladly do so to test this.

**Comment by thestinger** [comment]
That was a mistake, it wasn't released yet.

**Comment by inthewaves** [comment]
Every logout results in this logcat line:
```
SettingsProvider: Notifying for 10: content://settings/secure/always_on_vpn_lockdown
```

My current guess is that when a user is stopped/logged out, [this method](https://github.com/GrapheneOS/platform_frameworks_base/blob/10/services/core/java/com/android/server/connectivity/Vpn.java#L1328-L1338) is called:
```java
    /**
     * Called when the user associated with this VPN has just been stopped.
     */
    public synchronized void onUserStopped() {
        // Switch off networking lockdown (if it was enabled)
        setLockdown(false);
        mAlwaysOn = false;

        // Quit any active connections
        agentDisconnect();
    }
```
the [`setLockdown`](https://github.com/GrapheneOS/platform_frameworks_base/blob/9300e141fe843876876401fda6beab13d40c78d5/services/core/java/com/android/server/connectivity/Vpn.java#L355-L377) method:
```java
    public synchronized void setLockdown(boolean lockdown) {
        enforceControlPermissionOrInternalCaller();

        setVpnForcedLocked(lockdown);
        mLockdown = lockdown;

        // Update app lockdown setting if it changed. Legacy VPN lockdown status is controlled by
        // LockdownVpnTracker.isEnabled() which keeps track of its own state.
        if (mAlwaysOn) {
            saveAlwaysOnPackage();
        }
    }
```
the [`saveAlwaysOnPackage`](https://github.com/GrapheneOS/platform_frameworks_base/blob/9300e141fe843876876401fda6beab13d40c78d5/services/core/java/com/android/server/connectivity/Vpn.java#L550-L567) method
```
    /**
     * Save the always-on package and lockdown config into Settings.Secure
     */
    @GuardedBy("this")
    private void saveAlwaysOnPackage() {
        final long token = Binder.clearCallingIdentity();
        try {
            mSystemServices.settingsSecurePutStringForUser(Settings.Secure.ALWAYS_ON_VPN_APP,
                    getAlwaysOnPackage(), mUserHandle);
            mSystemServices.settingsSecurePutIntForUser(Settings.Secure.ALWAYS_ON_VPN_LOCKDOWN,
                    (mAlwaysOn && mLockdown ? 1 : 0), mUserHandle);
            mSystemServices.settingsSecurePutStringForUser(
                    Settings.Secure.ALWAYS_ON_VPN_LOCKDOWN_WHITELIST,
                    String.join(",", mLockdownWhitelist), mUserHandle);
        } finally {
            Binder.restoreCallingIdentity(token);
        }
    }
```

Will do testing and logging to make sure

**Comment by thestinger** [comment]
This is fixed for Android 11 GrapheneOS from the change by @inthewaves.
