### ISSUE TITLE
[Feature Request] Add: SIM PIN window cancel and show again

### ISSUE THREAD

**Issue by 564gvPAK7z9jZQx** [GrapheneOS/os_issue_tracker#214]
Hello,

this is a feature request for GrapheneOS. 

I know that in Android 11 (AOSP) there is generally no way to cancel the SIM PIN window and enter the SIM PIN again later e.g. in the settings. I heard from a colleague that it could be included in a future Android version. Probably next year (2021).

In iOS there is this possibility to enter the SIM PIN later. Similar to a UMTS/LTE software on Windows or Linux.

In iOS the method works like this, if a sim card is inserted into the iPhone, the SIM PIN window appears. It is possible to cancel the SIM PIN window (tap on cancel button), but the sim card itself remains locked. If you want to unlock the SIM card. You only have to switch the flight mode on and off or dial a number in the phone app and the sim pin window appears again and you can unlock the sim card if you want to. This also works with dual sim.

**Comment by thestinger** [comment]
Why?

**Comment by thestinger** [comment]
I don't see a reason to support this. The SIM PIN is meant to stop someone taking the SIM card out of your phone and using it in another. This doesn't improve it.

**Comment by 564gvPAK7z9jZQx** [comment]
> 
> 
> I don't see a reason to support this. The SIM PIN is meant to stop someone taking the SIM card out of your phone and using it in another. This doesn't improve it.

I think you misunderstood.

This is about the sim pin window. I mean the window and not the sim pin from the sim card.

This is the difference. This is a feature that is generally missing in Android, for user friendly UI.

I have here some requests from users who want this, as well as on iOS or UMTS/LTE software on Windows or Linux.

**Comment by 564gvPAK7z9jZQx** [comment]
> 
> 
> Why?
This is a feature that is generally missing in Android, for user friendly UI.

**Comment by thestinger** [comment]
It should be added to AOSP, not GrapheneOS downstream.

**Comment by thestinger** [comment]
It's not within the scope of what we work on: improving privacy / security, and filling in gaps from not having Play Services. Feature requests that aren't in one of those categories will be closed. It should be done in AOSP, not downstream.

**Comment by 564gvPAK7z9jZQx** [comment]
> 
> 
> It's not within the scope of what we work on: improving privacy / security, and filling in gaps from not having Play Services. Feature requests that aren't in one of those categories will be closed. It should be done in AOSP, not downstream.

I have also heard of users who use many sim cards, because of the privacy.

Because Android does not have this function you always have to remove the sim card from the device if you forget the sim pin.

But not every user has a needle immediately.

You can try it yourself. You are in an emergency situation and want to start your Android device for security reasons, e.g. to take pictures (proofs). But the sim cards are still in the device and you forgot the sim pin at this moment and you don't have a needle to take the sim card out of the device.

Try to get to the Android home screen and open the camera app.

This is not possible, because you cannot cancel the sim pin window/request.

**Comment by thestinger** [comment]
That's way too contrived for us to take an interest in this. I don't see this as a request for a security feature. This should be done in AOSP. GrapheneOS doesn't have developers to spare for making features like this outside of the scope of the project. Convincing me to leave the issue open doesn't mean we would ever implement it anyway. I closed it because we won't accept a patch for it due to it being out of scope, but not closing it doesn't mean anyone would work on it.
