### ISSUE TITLE
Files app / side menu / Downloads

### ISSUE THREAD

**Issue by h2dden** [GrapheneOS/os_issue_tracker#215]
a bit blurry but you get the point

 https://we.tl/t-U6YPdJCi5O

**Comment by thestinger** [comment]
The Download directory isn't the same thing as the Downloads category.

**Comment by h2dden** [comment]
maybe you din t get the point. accessing the same folder from the Downloads category, shows an empty folder. Which is not empty as it can be seen when accessing from the Download

**Comment by thestinger** [comment]
The Downloads category isn't browsing the file system. It's browsing things tagged as being part of the Downloads category because apps did that.

**Comment by thestinger** [comment]
You gave an app access to the legacy Storage permission and it put files in Download, rather than using the official infrastructure for putting them there. My recommendation is to avoid apps with the legacy Storage permission whenever possible and to pressure developers to finally move on from it.

**Comment by h2dden** [comment]
I have in the Downalod folder multiple folder downloaded with LibreTorrent. The folder that I showed in the video features different content when accessed from the Downloads category or by browsing from the Download folder. Another folder created by the same app LibreTorrent has a consistent behavior and features the same content when accessed in a similar way as above. Do you need a video for this to understand?

**Comment by h2dden** [comment]
*multiple folders

**Comment by h2dden** [comment]
the folder with consistent behaviour can be seen in the video already shared: it is called Lemony.Snickets....something

**Comment by thestinger** [comment]
The Downloads category is not supposed to show the full contents of a directory. It is supposed to show the files inside it tagged as downloads. Please listen to what I'm saying. It's not me that's confused.

**Comment by h2dden** [comment]
is not about confusion: the behaviour is different for similar folders

**Comment by thestinger** [comment]
As I said earlier, by granting an app the legacy Storage permission, you're letting it bypass the proper ways of accessing the profile's home directory. Take it up with the developers of this app. I suggest getting them to stop using the legacy Storage permission which has been removed for API 29 (Android 10) unless the app opts into legacy storage access, and at API 30 that is no longer an option. They could avoid causing this usability problem even with the legacy Storage permission but it would be best if they just did things properly.

This is not a bug, it's just how things work. The app is not marking all of the files as downloads.

**Comment by thestinger** [comment]
This isn't a bug report, it's confusion about how the OS and apps work. You should take it up with the app developers. It's wrong that they use the legacy Storage permission. Get them to stop doing that. This is not a bug but rather how it's supposed to work. The Downloads category is not supposed to show every file in directories. It's supposed to show the subset of files that are tagged as downloads. If they didn't use the legacy Storage permission, they wouldn't create confusion like this. Get them to target API 29 and then API 30 once Android 11 is available. Android 11 further improves this by preventing apps from using the Download directory for things that aren't Downloads.

**Comment by h2dden** [comment]
you win. I give up

**Comment by thestinger** [comment]
Try to read and understand what I wrote.

**Comment by thestinger** [comment]
If you want to access files based on their *location*, access the profile's home directory via the entry named after the device. The Downloads category will not list every file in directories. It will only list files that are considered to be downloads, and a file being in the Download directory doesn't mean that it's automatically considered a download. The app is putting files in there itself without tagging them this way.
