### ISSUE TITLE
[minimum supported API level] internal alarm/ clock app stop working

### ISSUE THREAD

**Issue by beerisgood** [GrapheneOS/os_issue_tracker#218]
With new API level change, I got the warning with GrapheneOS internal alarm/ clock app.

And I can confirm that the app stop working in background so it's not usable for e.g. using the alarm.

![Screenshot_20200526-224042](https://user-images.githubusercontent.com/9625159/82974983-85d1e100-9fdb-11ea-9949-f2168979dcd5.png)

**Comment by thestinger** [comment]
I think it should work in the background again after the initial launch. Can you confirm that? It's known that it targets an old API level. It's not an app developed by us. It's one of the AOSP apps.

**Comment by beerisgood** [comment]
> I think it should work in the background again after the initial launch. Can you confirm that? It's known that it targets an old API level. It's not an app developed by us. It's one of the AOSP apps.

Yes, can confirm.
Yesterday I start the app to take a look if I enable my alarm for today.

Today I wake up but alarm doesn't start nor app was active in background.
As it works day before / before the update and I change nothing this must be the reason.

**Comment by 4r7urh** [comment]
I can vaguely recall to have ignored that warning yesterday morning after the update. Yet, on my pixel 3a, alarms were working normally this morning. Maybe the couple of reboots yesterday due to the bluetooth issue (#217) fixed that problem here?

BTW: ugly time to get up in the morning.

**Comment by ahowell8** [comment]
Worked normally this morning with the same popup error as a above. Several reboots due to the bluetooth issue. Pixel 2XL.

**Comment by beerisgood** [comment]
Hmm. Now I clean appdata for alarm/ clock app and it seems to work again.

The funny thing was that even the icon in statusbar for enabled alarm disappeared before that. Which would be the reason why app stop working in background.

I'm testing it now and answer tomorrow if that doesn't fix it.
If it does, users or next update should reset app settings for alarm/ clock app to fix that.

I also doesn't reboot second time before my fix cause I read that too late here.
