### ISSUE TITLE
audio played through speakers although headset connected

### ISSUE THREAD

**Issue by h2dden** [GrapheneOS/os_issue_tracker#219]
Fresh start of system (pixel 3), plug in headset, audio plays just fine. I disconnect the headset and reconnect it: audio is played only through speakers. Disconnect/connect several times: same result. Ironically, the headset is recognized as I manage to control the volume of audio played through speakers from the headset controls...

**Comment by thestinger** [comment]
This sounds like https://github.com/GrapheneOS/os_issue_tracker/issues/217.

**Comment by h2dden** [comment]
not sure is the same: my headset is wired, not bluetooth...

**Comment by thestinger** [comment]
See https://github.com/GrapheneOS/os_issue_tracker/issues/220 then.

**Comment by thestinger** [comment]
But I think these are the same issue and will end up being fixed together...
