### ISSUE TITLE
Wired audio output Inconsistencies

### ISSUE THREAD

**Issue by DylanPy** [GrapheneOS/os_issue_tracker#220]
Myself and [other users](https://old.reddit.com/r/GrapheneOS/comments/grsy8f/wired_audio_output_not_working/) are having issues getting wired audio output to function after the latest release. As of right now, it appears rebooting will temporarily fix the issue for several minutes, but ultimately wired audio output will fail defaulting to the speaker being used.

I can't speak for other pixel variants, but this is affecting my 3XL (Crosshatch). It's unknown if this issue persists with users who have a 3.5mm jack

**Comment by thestinger** [comment]
Help is needed to work on these issues, or no progress can be made and things will probably continue to regress like this.

**Comment by DylanPy** [comment]
While my experience with android debugging is limited, perhaps these specific portions of the logcat file hint at the issue.
```
7115 APM::HwModule: createDevice: could not find HW module for device 4000000 address card=1;device=0
7116 AudioSystem-JNI: Command failed for android_media_AudioSystem_setDeviceConnectionState: -38
7123 AS.AudioDeviceInventory: not connecting device 0x82000000 due to command error 1
7124 EventHub: No input device configuration file found for device 'Google Pixel USB-C earbuds'
7572 UsbHostManager: Removed device at /dev/bus/usb/002/001 was already gone
7573 EventHub: Removing device Google Pixel USB-C earbuds due to epoll hang-up event
```
[logcat.log](https://github.com/GrapheneOS/os_issue_tracker/files/4697788/logcat.log)

**Comment by thestinger** [comment]
Same cause as https://github.com/GrapheneOS/os_issue_tracker/issues/217.
