### ISSUE TITLE
IPv6 link-local address not randomized

### ISSUE THREAD

**Issue by jpds** [GrapheneOS/os_issue_tracker#223]
When I connect to a network with IPv6-connectivity enabled, my device always has the same link-local IPv6 address even with the default fully randomized MAC address feature enabled.

I've tested this across two different v6 networks and while my global IPv6 address is different, the link-local one with `fe80::` is the same.

**Comment by thestinger** [comment]
It's different for each network though, right?

**Comment by thestinger** [comment]
cc @renlord

**Comment by jpds** [comment]
Here's what I currently have for IPv6 addresses:

```
fe80::d89a:72d3:eac0:XXXX
2a01:4b00:9d6b:6e00:ABCD:EFGH:IJKL:MNOP
2a01:4b00:9d6b:6e00:XXXX:YYYY:ZZZZ:FFFF
```

If I cycle my WiFi on and off, I get a new MAC address and naturally a new IPv4 address. However the three IPv6 addresses above remain the same.

I also observed the `fe80::d89a:72d3:eac0:XXXX` at a second IPv6 network I know of earlier today.

**Comment by thestinger** [comment]
Can you try disconnecting it from the network and connecting another device. These addresses are quite possibly chosen by the network, not the phone.

**Comment by jpds** [comment]
I'm currently using IPv6 stateless autoconfiguration on this network in particular, here's my `radvd.conf`:

```
interface eth1
{
    AdvSendAdvert on;
    AdvManagedFlag off;
    AdvOtherConfigFlag off;

    MaxRtrAdvInterval 60;

    prefix 2a01:4b00:9d6b:6e00::/64
    {
        AdvOnLink on;
        AdvAutonomous on;
        AdvRouterAddr on;
        AdvValidLifetime 600;
        AdvPreferredLifetime 300;
    };

    RDNSS 2a01:4b00:9d6b:6e00::2 {
        AdvRDNSSLifetime 120;
    };
};
```

On my laptop, I can only seem to [enable privacy extensions on NetworkManager](https://wiki.archlinux.org/index.php/IPv6#NetworkManager) for my global address on the interface but not the link-local `fe80::` one (this is not tied to the MAC address however).

The thing I find odd however is that I would see `fe80::d89a:72d3:eac0:XXXX` on both networks as they're not related to each other in any way. I will take my laptop there tomorrow to see if it ends up with the same IP too.

I'm not sure if [RFC4941](https://tools.ietf.org/html/rfc4941) is implemented in Android.

**Comment by thestinger** [comment]
You can verify that `net.ipv6.conf.wlan0.use_tempaddr` is set to `2`. I don't think that's the problem. I think the issue could be tied to https://tools.ietf.org/html/rfc7217, i.e. stable privacy addresses. I don't know exactly how this works, but it seems to be supported for Linux 4.4+. I'm not sure how netd decides when to use stable privacy addresses or how it handles the stable secret.

**Comment by thestinger** [comment]
I think this is related to the stable privacy addresses feature though. We could just disable it for the time being if it's an issue.

**Comment by thestinger** [comment]
I do think it's supposed to use a fully random one when using a random MAC address... not sure what's wrong if anything.

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/platform_system_netd/commit/f40656968463db40be6d56543f5079a54326c9ee should address this issue. The problem was introduced by Linux kernel 4.4+ since they added code to use this when available. I'm not sure when this stable_secret is refreshed.

**Comment by thestinger** [comment]
It does sound like it's per-network though.

**Comment by jpds** [comment]
I went and connected to two random open WiFi networks in my neighbourhood and in both cases, I got the same `fe80::` link-local address (they didn't have an other IPv6 connectivity).

The alternative to stable privacy is EUI-64 which _should_ be based on MAC address, may be better in this scenario.

**Comment by thestinger** [comment]
EUI-64 is what's used for Linux kernel < 4.4 and what's used with my commit.

**Comment by thestinger** [comment]
I think this is a case of unnecessarily adopting a Linux kernel feature just because it showed up and not fully fleshing out the implementation...

**Comment by thestinger** [comment]
Should be resolved now, you'll need to let me know if it still happens after the next release which will ship the fix.

**Comment by thestinger** [comment]
I think I've resolved it though. Testing seems to work.

**Comment by jpds** [comment]
I've just installed the new beta release and I can confirm that this is working for the link-local address.

However there is still a `second dynamic` address which Linux assigns that stays the same: https://www.tldp.org/HOWTO/Linux+IPv6-HOWTO/ch06s05.html .

This is the one that's used to establish external connections, so if I go to [ip6.me](http://ip6.me) - cycle my wifi, I still have the same address (while all other addresses have changed).

**Comment by thestinger** [comment]
I'm not sure why that would be the case since privacy extensions are enabled upstream.

**Comment by thestinger** [comment]
You'll need to let me know what has to be done since use_tempaddr is already set to 2 upstream.

**Comment by thestinger** [comment]
This was your original report:

> When I connect to a network with IPv6-connectivity enabled, my device always has the same link-local IPv6 address even with the default fully randomized MAC address feature enabled.
> 
> I've tested this across two different v6 networks and while my global IPv6 address is different, the link-local one with `fe80::` is the same.

Has it regressed due to my changes?

**Comment by thestinger** [comment]
You can confirm in `adb shell` that `net.ipv6.conf.wlan0.use_tempaddr` is `2` using `sysctl net.ipv6.conf.wlan0.use_tempaddr`.

**Comment by jpds** [comment]
This has not at all regressed from your change - that third v6 address was always there - however I assumed that it was derived from the link-local address - hence wondering why it doesn't change when I cycle the connection.

**Comment by thestinger** [comment]
It may be assigned by the ISP / router. Maybe try disconnecting this device and connect a different device. Try connecting to different networks too.

**Comment by thestinger** [comment]
I don't really know how this stuff works because it's pretty complicated and there are different ways to assign IP addresses for IPv6.

**Comment by jpds** [comment]
I think I have figured this out on my laptop. I think the `temp_prefered_lft` and `temp_valid_lft` values require changing from their defaults (1 day and 7 days respectively):

- https://blog.linitx.com/control-privacy-addressing-ipv6-linux/

Some pitfalls are described here: https://home.regit.org/2011/04/ipv6-privacy/

If you have v6 at home with router advertisements, you can see this in action by doing:

```
sudo sysctl -w net.ipv6.conf.wls7.use_tempaddr=2
sudo sysctl -w net.ipv6.conf.wls7.temp_prefered_lft=250
sudo sysctl -w net.ipv6.conf.wls7.temp_valid_lft=300
```

And then:

```
watch ip -6 a s
```

Once your preferred lifetime hits 0, Linux will request a new temporary address and mark the old one `deprecated` (allowing time for connections to close) and then when the `valid_lft` hits zero, it's removed from the kernel.

Could it be worth setting these to 1 and 3 hours by default on Graphene? I saw this suggested here: https://lists.opensuse.org/opensuse-bugs/2012-03/msg00017.html

**Comment by thestinger** [comment]
Maybe we shouldn't be using privacy addresses at all when MAC randomization is enabled?

**Comment by thestinger** [comment]
@jpds Can you open a new issue about this? Since it's a different problem. Pasting your comment here into a new issue with an appropriate title would be good.

**Comment by thestinger** [comment]
@jpds Can you open a new issue about this? Since it's a different problem. Pasting your comment (well, the markdown source) here into a new issue with an appropriate title would be good.

**Comment by jpds** [comment]
> Maybe we shouldn't be using privacy addresses at all when MAC randomization is enabled?

I did think about this, and it's probably better to keep them for things which are outside the local network. Otherwise, a device would connect and visit cnn.com with potentially the same v6 address for days rather than rotating every few hours.

Opened an issue at #235 .

**Comment by thestinger** [comment]
BTW the stable privacy address issue seems to have been addressed upstream for Android 11. They only get used when MAC randomization isn't enabled. I've reverted my commit disabling that feature.

The issue of the default lifetimes (particularly them not being tied to connecting to networks) is probably still an issue.
