### ISSUE TITLE
Pixel 4 and 4 XL Wi-Fi is broken

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os_issue_tracker#228]

**Comment by thestinger** [comment]
cc @paintedman

**Comment by paintedman** [comment]
We can use this code to make Wi-Fi work:

- https://github.com/paintedman/android-prepare-vendor/commit/514fa479bc6106002902f4ebc51f41821d8b6e06
- https://github.com/paintedman/kernel_google_coral_drivers_staging_qcacld-3.0

**Comment by thestinger** [comment]
@paintedman Is it possible to narrow down the userspace workaround any further, or are all of those libraries a problem?

**Comment by paintedman** [comment]
>all of those libraries a problem?
No, I've posted this in case anyone has ideas. Rebuilding an image for each removed file takes a very significant amount of time.

I think we could identify which exact library is broken, and I hope @anupritaisno1 will help me with it.

**Comment by paintedman** [comment]
I figured out that the problem is in `lib64/libwifi-hal.so`

**Comment by thestinger** [comment]
This is resolved.
