### ISSUE TITLE
Display problems with Mullvand VPN only on GrapheneOS it seems

### ISSUE THREAD

**Issue by bungabunga** [GrapheneOS/os_issue_tracker#230]
I have a really strange issue with the latest version of Mullvand VPN (2020.5.beta2), where they prevented clicks to the app if there are other apps drawing on top of it. Since they did that their app's UI is unresponsive to touch.

I've come to think that maybe it has something to do with GrapheneOS, since they tested it on many devices with Android 10 and they had no issues.

I use Pixel 3 with the latest GrapheneOS update.

A link to Mullvand's GitHub issue page: https://github.com/mullvad/mullvadvpn-app/issues/1852

**Comment by tomkel** [comment]
Hm yeah, I'm also on GrapheneOS and I have the same issue

**Comment by tomkel** [comment]
Ah, the issue for me was that I had another screen filter app that was enabled , which was drawing an overlay over all apps. Likely a security feature that mullvad enabled

**Comment by tomkel** [comment]
I'm using Mullvad on GrapheneOS and as long as other drawing apps are disabled, the UI works

**Comment by bungabunga** [comment]
hi, @tomkel, thank you for your comment. it made me do a research and find out that i was actually using an app with the overlay (although i was convinced that i am not). thanks again!
