### ISSUE TITLE
Grey bar at top of screen

### ISSUE THREAD

**Issue by Kartereo** [GrapheneOS/os_issue_tracker#234]
I just happened to notice this

![Screenshot_20200624-023457_1](https://user-images.githubusercontent.com/5624644/85509232-9918a200-b5c3-11ea-9ca0-37f8bd3d5ed5.jpg)

**Comment by beerisgood** [comment]
Which grey bar? Don't see any.

**Comment by thestinger** [comment]
Don't know what you mean. Maybe your screen has a row of dead pixels.

**Comment by Kokokokoka** [comment]
Probably, xe was talking about almost-invisible gradient.

**Comment by Kartereo** [comment]
If you look hard enough you can see it. This picture doesn't do it justice. In person it's very noticeable, I didn't know any other way to capture what I was seeing.

**Comment by thestinger** [comment]
I can't see it.

**Comment by thestinger** [comment]
I see a gradient which makes sense.

**Comment by thestinger** [comment]
I can't see a line. I only see the expected gradient from a lighting effect.

**Comment by Kartereo** [comment]
I was able to get a hold of another phone.

Grey bar at top
![20200625_192056](https://user-images.githubusercontent.com/5624644/85805309-f1fa4e80-b719-11ea-91e8-e4941d1b66b0.jpg)

notification pull down to show no burn in
![20200625_192111](https://user-images.githubusercontent.com/5624644/85805345-05a5b500-b71a-11ea-8864-92e6f85d423e.jpg)

**Comment by thestinger** [comment]
I can't really see what you're trying to show. Are you sure it isn't just backlight bleed?

**Comment by Kokokokoka** [comment]
seems like a backlight bleed (burnout?)/display problem.

**Comment by Kartereo** [comment]
I am sure it isn't backlight bleed. I confirmed this in the second picture.

**Comment by thestinger** [comment]
I can't see what you're trying to show.

**Comment by Kartereo** [comment]
![85805345-05a5b500-b71a-11ea-8864-92e6f85d423e](https://user-images.githubusercontent.com/5624644/85810761-19591780-b72a-11ea-9721-a22ad7355230.jpg)

![85805309-f1fa4e80-b719-11ea-91e8-e4941d1b66b0](https://user-images.githubusercontent.com/5624644/85810771-1eb66200-b72a-11ea-864d-c6ad5972632e.jpg)

**Comment by thestinger** [comment]
It's transparent on the home screen.

**Comment by Kartereo** [comment]
Its not clear on my screen. Is there maybe something I could have accidentally enabled in a themes setting or something maybe?
