### ISSUE TITLE
Disable shutting down or restarting device from lock screen

### ISSUE THREAD

**Issue by TipTopHat** [GrapheneOS/os_issue_tracker#236]
would be cool to have the device ask for the password if someone holds the power button and presses shutdown or reboot, similar to how disabling/enabling airplane mode requires the password at lockscreen. It would prevent someone forcing you to miss notifications or running an important service in the background. Maybe it could be a setting under security options as some people enjoy the convenience.

**Comment by beerisgood** [comment]
Don't think this will work as long pressing power button shut down/ reboot the device anyway.

**Comment by thestinger** [comment]
I don't think we can support this.

**Comment by thestinger** [comment]
@beerisgood is correct.
