### ISSUE TITLE
Any possibility to install on older devices

### ISSUE THREAD

**Issue by kirk86** [GrapheneOS/os_issue_tracker#242]
Hi I was wondering is it's possible to install graphene os in other devices other than pixel, probably older ones like oneplus 2?

Thanks!

**Comment by thestinger** [comment]
https://grapheneos.org/faq#device-support

Please use the IRC / Matrix channel for support questions. The issue tracker isn't for questions.

**Comment by anupritaisno1** [comment]
@kirk86 grapheneos does not boot on the oneplus 2. I have already tried it

Hardened malloc exposes several memory corruptions on both the oneplus 2 and oneplus 3, they are unable to even run the bootanimation correctly and they never boot. Debugging these devices is also very hard

**Comment by kirk86** [comment]
@anupritaisno1 Thank you for the clarification!.
