### ISSUE TITLE
Headphones

### ISSUE THREAD

**Issue by HAhahehehu** [GrapheneOS/os_issue_tracker#245]
Hi

I'm using pixel2, and looks like GrapheneOS got same problem like early versions of Android 8, when i plug in headphones with cable 3,5 mini jack to usb-c (original cable) system recognizes it as charging through usb not as headphones. You need to restart the phone in order to headphones to be detected. Each time headphones are unplugged, system need to be restarted to detect them again.

**Comment by thestinger** [comment]
If you're plugging them in when the screen is locked, that's completely expected unless you change the USB peripheral setting.

**Comment by HAhahehehu** [comment]
No matter if phone is locked or unlocked, problem still exists. USB peripherial setting is in default "off" position.

**Comment by thestinger** [comment]
It's not off by default. It's dynamic by default. If you have it set to off that disables adding USB peripherals except at boot. That's the issue.

**Comment by HAhahehehu** [comment]
English is my second language, plus i got phone in my native language. I was talking about multimedia audio usb option in developer mode that is off

**Comment by HAhahehehu** [comment]
Is that what you meant by USB peripheral setting?
