### ISSUE TITLE
Headphones not detected on Pixel2

### ISSUE THREAD

**Issue by HAhahehehu** [GrapheneOS/os_issue_tracker#246]
I need to ask again

 HAhahehehu commented 11 hours ago

Hi

I'm using pixel2, and looks like GrapheneOS got same problem like early versions of Android 8, when i plug in headphones with cable 3,5 mini jack to usb-c (original cable) system recognizes it as charging through usb not as headphones. You need to restart the phone in order to headphones to be detected. Each time headphones are unplugged, system need to be restarted to detect them again.

 thestinger commented 8 hours ago
If you're plugging them in when the screen is locked, that's completely expected unless you change the USB peripheral setting.

 HAhahehehu commented 29 minutes ago
No matter if phone is locked or unlocked, problem still exists. USB peripherial setting is in default "off" position.

 thestinger commented 18 minutes ago
It's not off by default. It's dynamic by default. If you have it set to off that disables adding USB peripherals except at boot. That's the issue.

 HAhahehehu commented 10 minutes ago
English is my second language, plus i got phone in my native language. I was talking about multimedia audio usb option in developer mode that is off

 HAhahehehu commented 8 minutes ago
Is that what you meant by USB peripheral setting?

**Comment by thestinger** [comment]
USB peripherals setting in the security settings.

**Comment by HAhahehehu** [comment]
I switched phone language to English. I found in Security option called "USB accessories" and option was set to "Deny new..." so problem sorted :) thanks for patience.

**Comment by thestinger** [comment]
@HAhahehehu You should probably have it enabled but in the dynamic mode and make sure to plug in USB peripherals when unlocked.
