### ISSUE TITLE
Turning off Wi-Fi completely breaks the system (Pixel 4 XL)

### ISSUE THREAD

**Issue by Flex1911** [GrapheneOS/os_issue_tracker#248]
1. Disable Wi-Fi scanning for location in Settings.
2. Turn off Wi-Fi.

Device crashes and reboots due to this:
```
07-22 12:27:05.564   762   762 E android.hardware.wifi@1.0-service: Failed to write driver state control param: Operation already in progress
07-22 12:27:05.564   762   762 E android.hardware.wifi@1.0-service: Failed to unload WiFi driver
```
The reason is that it tries to write zero to boot_wlan to shutdown wlan hardware, which is wrong, as boot_wlan can only be triggered once and any subsequent calls will drop EALREADY: https://github.com/GrapheneOS/kernel_google_coral_drivers_staging_qcacld-3.0/blob/10/core/hdd/src/wlan_hdd_main.c#L13359

I made a PR to fix this: https://github.com/GrapheneOS/device_google_coral/pull/3 https://github.com/GrapheneOS/device_google_coral-sepolicy/pull/1

**Comment by thestinger** [comment]
Okay, merged these fixes.
