### ISSUE TITLE
Funding alterenative in BAT(Brave Browser Token)

### ISSUE THREAD

**Issue by lescuer97** [GrapheneOS/os_issue_tracker#249]
it would be awesome if the GrapheneOS project accepted donations in BAT so people could set up a monthly donation or send tips  with their reward tokens and forget about it.
 I know this could be a great method for more people to donate to the project or at least get some more funding. i know every cent counts and i really want to see this project develop

**Comment by thestinger** [comment]
I don't want to support BAT.
