### ISSUE TITLE
add app implementing backup service

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os_issue_tracker#25]
This will likely be based on https://github.com/stevesoltys/backup, which was originally started for use in the previous incarnation of this project, based on my concept for it and suggestions. That means it already closely fits how I want this to be designed.

**Comment by yegortimoshenko** [comment]
Would you consider an encrypted, incremental backup design, provided object storage support (so think more of [Duplicacy](http://duplicacy.com/) rather than Borg)?

**Comment by beerisgood** [comment]
@thestinger 
@renlord 
@stevesoltys released this 1 hour ago:
seedvault 1.0.0
Added: APK backup and restore support with the option to toggle them off

https://github.com/stevesoltys/seedvault/releases/tag/1.0.0
