### ISSUE TITLE
Dark theme broken on settings search bar

### ISSUE THREAD

**Issue by JamsNJellies** [GrapheneOS/os_issue_tracker#252]
Light background when searching
![Screenshot_20200801-140723](https://user-images.githubusercontent.com/39382425/89102447-35bf3280-d401-11ea-9ff9-e476db3f2d78.png)

**Comment by thestinger** [comment]
Still an issue for Android 11.

**Comment by thestinger** [comment]
Still an issue on the 2020.12.08.08 release.

**Comment by kdrag0n** [comment]
The fix for this in the SettingsIntelligence app is available in LineageOS: https://github.com/LineageOS/android_packages_apps_SettingsIntelligence/commit/379b205c0dadc2079563c0539c335666d5fd280c

**Comment by thestinger** [comment]
The base issue is fixed (dark theme). We didn't add the other style changes at the moment. Can address that later if anyone cares.
