### ISSUE TITLE
Selinux hardening is crashing a few apps

### ISSUE THREAD

**Issue by anupritaisno1** [GrapheneOS/os_issue_tracker#253]
The selinux policy hardening crashes certain apps that try to execute native code. Examples are orbot and synching

This seems to be the selinux denial

avc: denied { execute_no_trans } for comm=4173796E635461736B202331 path="/data/app/com.nutomic.syncthingandroid-CrK2Oi_6UwwLkTcdpnHw8w==/lib/arm64/libsyncthing.so" dev="sda13" ino=2573634 scontext=u:r:untrusted_app_27:s0:c104,c257,c512,c768
tcontext=u:object_r:apk_data_file:s0 tclass=file permissive=0 app=com.nutomic.syncthingandroid

**Comment by thestinger** [comment]
I don't understand why this wasn't reported much earlier.

**Comment by thestinger** [comment]
This is fixed and there will be a new release addressing it. However, I'm concerned that it took so long to get a report that apps using native executables via the proper mechanism are broken.
