### ISSUE TITLE
Error Extracting Files From sargo-factory-2020.08.07.01

### ISSUE THREAD

**Issue by carl4315** [GrapheneOS/os_issue_tracker#256]
Not sure if these two things are related: I get an error when extracting the files from the .zip. 'Error Extracting Files' but they show up extracted in the folder. I upload the OS it gets to the "fastbootd" screen on the Pixel then the loading stops and a <waiting for device> Thanks!

**Comment by thestinger** [comment]
You should request support on the IRC / Matrix channel. The issue tracker isn't a support platform.
