### ISSUE TITLE
seedvault backups are not reliable using Nextcloud

### ISSUE THREAD

**Issue by renlord** [GrapheneOS/os_issue_tracker#257]
Just stumbled over this issue and want people to know that Nextcloud support is rather experimental and I wouldn't trust it with my backups as it has severe issues I am currently addressing. Example: https://github.com/nextcloud/android/issues/6726

_Originally posted by @grote in https://github.com/GrapheneOS/os_issue_tracker/issues/195#issuecomment-676628408_

**Comment by renlord** [comment]
Created this issue to track upstream changes.

**Comment by thestinger** [comment]
Seems like this should be fixed upstream now.
