### ISSUE TITLE
Add logout button to logout of current user profile

### ISSUE THREAD

**Issue by inthewaves** [GrapheneOS/os_issue_tracker#258]
https://freenode.logbot.info/grapheneos/20200709#c4343317

> you can also take advantage of profiles already
>
> put sensitive stuff in a profile with a strong passphrase
>
> use a profile with a short PIN for quick use
>
> keep the sensitive profile inactive (logged out)
>
> atm there isn't an explicit logout option in the GUI but you can reboot for now, 
> we could easily add a logout to the power menu
>
> just another thing people have to step up to help implement
>
> logout / purging the keys is already supported
>
> just isn't a button for it in the GUI

**Comment by inthewaves** [comment]
Looking into this, it seems there's already some logout option in the power menu. However, it seems to be meant for managed devices:

https://github.com/GrapheneOS/platform_frameworks_base/blob/10/packages/SystemUI/src/com/android/systemui/globalactions/GlobalActionsDialog.java#L391-L396

LogoutAction:

https://github.com/GrapheneOS/platform_frameworks_base/blob/10/packages/SystemUI/src/com/android/systemui/globalactions/GlobalActionsDialog.java#L719-L733

I've tried removing the `mDevicePolicyManager.isLogoutEnabled() && getCurrentUser().id != UserHandle.USER_SYSTEM` condition, and it seems to logout non-Admin profiles (it will show a "PIN required after device restarts" message if trying to use biometrics after logging out and trying to login after).

However, an exception is thrown if trying to stop the owner:

```plain
--------- beginning of system
   990  2531 I ActivityManager: switching to user 0
   990  2531 I ActivityManager: user #0 is already the current user
  8336  8336 D AndroidRuntime: Shutting down VM
--------- beginning of crash
  8336  8336 E AndroidRuntime: FATAL EXCEPTION: main
  8336  8336 E AndroidRuntime: Process: com.android.systemui, PID: 8336
  8336  8336 E AndroidRuntime: java.lang.IllegalArgumentException: Can't stop system user 0
  8336  8336 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2075)
  8336  8336 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2039)
  8336  8336 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1987)
  8336  8336 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.stopUser(IActivityManager.java:7482)
  8336  8336 E AndroidRuntime: 	at com.android.systemui.globalactions.GlobalActionsDialog$LogoutAction.lambda$onPress$0$GlobalActionsDialog$LogoutAction(GlobalActionsDialog.java:726)
  8336  8336 E AndroidRuntime: 	at com.android.systemui.globalactions.-$$Lambda$GlobalActionsDialog$LogoutAction$3H17sX2I_BqMu2dZ5Dekk1AEv-U.run(Unknown Source:2)
  8336  8336 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
  8336  8336 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
  8336  8336 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
  8336  8336 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
  8336  8336 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
  8336  8336 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
  8336  8336 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:43)
  8336  8336 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
  8336  8336 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338)
  8336  8336 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
  8336  8336 E AndroidRuntime: 	at com.android.server.am.UserController.stopUser(UserController.java:639)
  8336  8336 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.stopUser(ActivityManagerService.java:17578)
  8336  8336 E AndroidRuntime: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3553)
  8336  8336 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2738)
  8336  8336 E AndroidRuntime: 	at android.os.Binder.execTransactInternal(Binder.java:1021)
```

Unsure if we should find a way to get the owner/admin profile to be able to logout, or if there's a better way to do this entirely

**Comment by inthewaves** [comment]
(As a side note: Using this button has also let me reliably reproduce https://github.com/GrapheneOS/os_issue_tracker/issues/213 by logging out of a non-admin profile that has always-on VPN enabled)

**Comment by anupritaisno1** [comment]
There are several things to test

In a userdebug build with root verify that data for user 0 is actually encrypted
Verify that /sdcard is not accessible

**Comment by dznsm** [comment]
Don't think the main/primary user can be logged out. Certainly not designed to be-
`Primary. First user added to a device. The primary user cannot be removed except by factory reset and is always running even when other users are in the foreground`
https://source.android.com/devices/tech/admin/multi-user

**Comment by inthewaves** [comment]
After making some changes to UserController to allow the system user to be stopped (and restarted, otherwise the phone just shows a black screen), I used the logout button after logging in as user 0, then entered the device using `adb shell` and `$ su`.
- `/sdcard` is still an accessible symlink, but `ls /sdcard` prints out ciphertexts.
- Running `ls /data/user/0` shows plaintext directory names for the packages of apps, but `ls -R /data/user/0` shows the contents inside those directory are ciphertexts

Logout behavior for this button is also buggy for user 0. After logging in and waiting and then pressing the logout button, I've observed that it will either
- bring users to Keyguard with the "Unlock for all features and data" message and let the user input as normal; or
- it will show a "Phone is starting..." screen with a progress bar (and I could still access and change the settings using the status bar, including navigating to the Settings app). This screen never goes away, until the screen is turned off and on again (and then at this point the status bar settings and Settings app are no longer changeable without logging in)

**Comment by inthewaves** [comment]
buggy Keyguard behavior fixed by negating a boolean param passed into startUser

**Comment by inthewaves** [comment]
After testing this hidden built-in logout button on non-admin profiles, it doesn't seem like this is acceptable solution.

After pressing the button in a non-admin profile, I can see in the logcat log entries such as

```
D/vold: fscrypt_lock_user_key 10
D/vold: Unlinked key with serial 245269186 ref ext4:8047bb64a757bcda
D/vold: Unlinked key with serial 493316562 ref f2fs:8047bb64a757bcda
D/vold: Unlinked key with serial 041339042 ref fscrypt:8047bb64a757bcda
```

However, I can still find files that are unencrypted in `/data/user/<some nonzero user ID I just logged out of>` via adb shell + su, including directory names, .db files, cache files, etc.

**Comment by dznsm** [comment]
Shame it leaves unencrypted data. I'd still find this useful as it would hopefully still be a quick way to kill all apps in any non-admin user profile.

**Comment by thestinger** [comment]
@inthewaves Might be a bug in ext4 or vold. Perhaps it's just not fully logging them out though.

**Comment by thestinger** [comment]
What happens with users that are naturally logged out via the existing support for that?

**Comment by thestinger** [comment]
Such as when too many users are started.

**Comment by inthewaves** [comment]
From my tests so far on Android 11, I'm not seeing any plaintext for users that are naturally logged out.

**Comment by thestinger** [comment]
We should probably just limit this to only secondary users.

**Comment by thestinger** [comment]
This is now enabled by default for secondary profiles. I don't think it's worth doing something for the owner profile since it's essentially the same as rebooting.
