### ISSUE TITLE
always on feature/timout  for lockdown/screenlock

### ISSUE THREAD

**Issue by churchthecat** [GrapheneOS/os_issue_tracker#259]
Using the fingerprint reader is great for my apps and so on , but its not a good way to use for screen lock for a lot of reasons.
The lockdown feature is good but it requires that I always remember to use it.
How about a always on feature or timer for weak unlock? AOSP has some on this that might be  used in Graphene.
https://developer.android.com/reference/android/app/admin/DevicePolicyManager#getRequiredStrongAuthTimeout(android.content.ComponentName)

**Comment by thestinger** [comment]
There's already a timer. It's not configurable by default via the Settings app but device managers can control it as you can see from that API. https://github.com/GrapheneOS/os_issue_tracker/issues/14 is filed about exposing that as an option in Settings.

https://github.com/GrapheneOS/os_issue_tracker/issues/202 is filed about only using the fingerprint reader for apps. Face unlock already has a toggle for this by default. There's a pull request with initial work on this but I currently lack the time to finish reviewing and editing it to merge it.
