### ISSUE TITLE
brightness sensor stopped working Pixel 3a

### ISSUE THREAD

**Issue by tarek437248** [GrapheneOS/os_issue_tracker#262]
Hey,
So I want to report this problem, started two three weeks ago, after an update (maybe, the update happen in the night, not sure about the relationship between the update and the problem).
So the brightness sensor stopped detecting changes in light, like when I wake up/or before I sleep. I should change it manually.
Also when calling someone the screen stays on when I put the phone on my ear. 
In Settings, it's on automatic.

**Comment by thestinger** [comment]
This sounds like a hardware problem. Unfortunately, not much that can be done about it or to investigate it.
