### ISSUE TITLE
Unable to erase all contacts

### ISSUE THREAD

**Issue by SpaggettiCoder** [GrapheneOS/os_issue_tracker#263]
Settings->Apps and notifications->Contacts->Storage & cache->Clear Storage
Notification that data has been erased but contact list still exists unchanged.
Pixel 3a
Build number QQ3A.200805.001.2020.08.07.01

**Comment by inthewaves** [comment]
I believe the Contacts app that users normally see doesn't actually store the contacts (it has a Contacts permission that can be disabled); another app on the system is used to store the contacts.

Go to Settings -> Apps & notifications -> See all apps -> (In the top right) Show system -> Look for Contacts Storage -> Storage & cache -> Clear storage

**Comment by thestinger** [comment]
Yeah, the Contacts app is just a frontend to the profile's contacts database.
