### ISSUE TITLE
Graphene flashing not working

### ISSUE THREAD

**Issue by GraphNewFag** [GrapheneOS/os_issue_tracker#264]
![screenshot flash-all_bat](https://user-images.githubusercontent.com/70949312/92466805-f4c0f780-f1d0-11ea-8db9-c040d5317ca9.PNG)

I get the attached error message when trying to flash GrapheneOS to my Pixel 3a XL... everything up to this point worked (unlock bootloader etc.)... only the flashing is not working...
Any ideas?

Thanks a lot in advance!

**Comment by thestinger** [comment]
Please ask for support on the #grapheneos IRC / Matrix channel. The issue tracker is strictly for tracking issues, not providing support.

**Comment by beerisgood** [comment]
(as your system looks German):
Du brauchst eine aktuelle Fastboot Version und du musst Fastboot in der Umgebungsvariablen festlegen.  Besten auch via Powershell statt in der CMD.
