### ISSUE TITLE
SetupWizard needs to be ported to Android 11

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os_issue_tracker#265]

**Comment by chirayudesai** [comment]
https://gitlab.com/calyxos/calyxos/-/issues/174

**Comment by thestinger** [comment]
@chirayudesai Any progress yet?

**Comment by chirayudesai** [comment]
@thestinger no, usually we do it last.

Would you have a copy of the build / runtime failure by any chance?

**Comment by thestinger** [comment]
Needs to be done in the next few days or we'll just be dropping it.
