### ISSUE TITLE
switch back to the Vanadium WebView when Chromium 86 stable is out

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os_issue_tracker#267]
It appears that the next release of Chromium will take care of this for us, and we'll be able to start using it again.

Until then, we're using the stock WebView alongside Vanadium.

**Comment by thestinger** [comment]
It has been confirmed that this is addressed by Chromium 86. We're going to wait until it's in the stable channel to use it, and until then we'll ship the stock WebView as a stopgap solution.

**Comment by theaeonsolution** [comment]
Going by the Chromium Dash schedule, it looks like the stable release for 86 will be October 6th.

**Comment by thestinger** [comment]
Chromium 86 is out and @inthewaves has confirmed this works. I'm working on the official builds at the moment.
