### ISSUE TITLE
port hardened_malloc integration to Android 11 and replace Scudo with it in 64-bit processes

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os_issue_tracker#269]

**Comment by vzlcn0** [comment]
Why not using Scudo instead of hardened_malloc for 11?

**Comment by thestinger** [comment]
Why would we use a far less hardened allocator with drastically weaker security properties?

**Comment by thestinger** [comment]
Please read the hardened_malloc README: https://github.com/GrapheneOS/hardened_malloc/blob/master/README.md.

Scudo is a traditional allocator design with inline metadata and similar (but weaker) optional security features bolted on top of it. It's not relevant to whether we need to use hardened malloc, since it's not really a hardened allocator design in the same sense.

**Comment by thestinger** [comment]
This is implemented.
