### ISSUE TITLE
port other Bionic hardening to Android 11 from Android 10

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os_issue_tracker#270]
This issue tracks covering the port of hardening beyond hardened_malloc, which has a dedicated issue already:

https://github.com/GrapheneOS/os_issue_tracker/issues/269

Other troublesome parts of the porting can have their own issues created.

This meta-issue does not cover porting features that we didn't have ported to Android 10, such as older features like the isolated library region that were missing in already in Android 10 GrapheneOS.

**Comment by theaeonsolution** [comment]
Initial Bionic hardening port work https://github.com/GrapheneOS/platform_bionic/pull/6

**Comment by thestinger** [comment]
Done.
