### ISSUE TITLE
port Sensors and Network permissions to Android 11

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os_issue_tracker#271]
The bulk of the work is porting the tricky permission handling code in frameworks/base and PackageInstaller. The Sensors permission also needs the change in frameworks/native, but that's not complicated. Since it's mostly shared, this is covered by the same issue.

**Comment by inthewaves** [comment]
How should the new auto revoking toggle be handled for these permissions?

**Comment by thestinger** [comment]
I don't think it needs special treatment.

**Comment by thestinger** [comment]
It seems that it would work fine with that feature, or without it.
