### ISSUE TITLE
Always-on VPN in multiple profiles causing issues

### ISSUE THREAD

**Issue by ghost** [GrapheneOS/os_issue_tracker#2835]
I'm unable to multiple separate VPNs (Mullvad) on GrapheneOS with Always-on VPN enabled in both of them. Eventually, one of them (Owner for me) disconnects. Mullvad Android app complains I have Always-on-VPN 'enabled in another app' and GrapheneOS throws up a message of "Disconnected from always-on VPN". I reached out to them and received the following reply:

> Disable "Always-on VPN" on one of the profiles, which should resolve the issue. It is only possible to have "Always-on VPN" enabled for an app on one profile at a time. This is an Android limitation.

This is first I'm hearing of it and would appreciate authoritative response on the subject matter. Is this something I need to pursue with them or is it expected behavior?

The closest issue I found is #213, but it doesn't really describe my problem.

**Comment by thestinger** [comment]
That's not correct and sounds like either an app bug or OS bug. Haven't heard of people having this issue before. Which GrapheneOS version are you on?

**Comment by thestinger** [comment]
@scarecrow1636 Please provide more details on your setup.

**Comment by gsture** [comment]
I use 2 mullvad always on vpn connections, 1 for normal apps and 1 for work apps. This works without any problems so I don't think it is the mullvad app that has problems.

**Comment by thestinger** [comment]
@gsture On which OS version?

**Comment by gsture** [comment]
> @gsture On which OS version?

14 (UP1A.231105.001)

**Comment by thestinger** [comment]
The 2nd part of the version is what matters. The first part we set to stock OS value.

**Comment by gsture** [comment]
> The 2nd part of the version is what matters. The first part we set to stock OS value.

Ofcourse, you're right, was in a hurry. Version: 2023121200

**Comment by miles992** [comment]
This might be related to an issue with libwg-go.so, a part of wireguard, afaik Mullvad uses it too. Proton has the same issue. I debugged it a bit, it seems there is an underflow in this lib triggering the bug. You can use MTE to get more infos on it.
