### ISSUE TITLE
Pixel 3XL Sound and Phone Call Issues on 10-Sept Beta Update

### ISSUE THREAD

**Issue by hkp2k** [GrapheneOS/os_issue_tracker#288]
I received the beta update this morning and it appears to have several issues mostly related to sound as far as I can tell.  

1. I am not receiving any sound at all through the headset when trying to play videos through NewPipe or Vanadium (YouTube) or through my podcast app.  Sound appears to be completely broken for me.
2. Phone calls are similar in that I am unable to hear anything when placing phone calls through the native dialer.  Eventually, the phone will lock up with the error message "System UI isn't responding", and requires a reboot.

Thanks for all the work that you do!

**Comment by thestinger** [comment]
Okay, I'll do another release rolling back the kernel changes with the hope that it works around this. It may have been a bad idea to use the Android 11 kernels early.

**Comment by thestinger** [comment]
It may be another problem. It would help if people could give feedback based on the upcoming Pixel 4 beta. Unfortunately, this migration process is not going very well.

**Comment by daneov** [comment]
If I can do anything to help you trace the issue let me know. When trying to call my entire phone freezes and eventually even does a soft-reboot.

**Comment by thestinger** [comment]
The release was cancelled, and a new one is being made, so these issues shouldn't be relevant anymore. This is why beta testing is so helpful.
