### ISSUE TITLE
Bug- Phone calls not working

### ISSUE THREAD

**Issue by HeadyWook** [GrapheneOS/os_issue_tracker#289]
Since recent update, phone calls not working. Cannot make or answer calls. Phone app is crashing. When I receive a call, caller and myself cannot hear each other. When I make a call, the person receives it but I cannot see they answered. Then app crashes. When someone calls I can answer but they cannot hear and I cannot hear.

**Comment by cyrinux** [comment]
Known problem https://github.com/GrapheneOS/os_issue_tracker/issues/288 .
Will be fix in th

**Comment by HeadyWook** [comment]
Got it, just noticed. The issue title threw me off as I did not see "phone" in it. I appreciate the quick feedback.

**Comment by HeadyWook** [comment]
I wonder when fix?

**Comment by cyrinux** [comment]
AFAIK in the next release, kernel problem.

**Comment by thestinger** [comment]
The previous beta release (https://grapheneos.org/releases#2020.09.10.05) has various known issues. There's a new beta release (https://grapheneos.org/releases#2020.09.11.14) in progress to address the problems.

Beta testing is very helpful for identifying these kinds of issues. The release was cancelled before even being close to pushing it to the stable channel.
