### ISSUE TITLE
Can't update Pixel 3a to 2020.09.11.14

### ISSUE THREAD

**Issue by n1m1** [GrapheneOS/os_issue_tracker#290]
After OTA update phone reboots. GrapheneOS reports that it cannot load Android system and data may be corrupt. After a couple of reboots the phone rolls back to 2020.09.10.05. 

The same problem has been reported on [reddit](https://www.reddit.com/r/GrapheneOS/comments/ir3kxb/grapheneos_2020091114_release/g4wwo47/?utm_source=reddit&utm_medium=web2x&context=3) for a Pixel 3a XL as well.

**Comment by thestinger** [comment]
See the response there. The *previous* beta release was cancelled and is the cause of this issue, not the 2020.09.11.14 release.

**Comment by n1m1** [comment]
Excellent, thanks. So, according to 2020.09.11.14 changelog, instead of back up  and wipe out my device, I can wait untill the next stable release based on Android 11. Correct?

**Comment by thestinger** [comment]
Yes, you can disable the Updater until then per the usage guide. It's a major annoyance but it's kinda the purpose of the Beta channel after all. Rolling back the kernel changes isn't really possible without a wipe for the 3a and 3a XL, and since it's the Beta channel we can't dedicate a huge amount of development time to making this friendlier. Since Android 11 will have those kernel changes again, it should upgrade cleanly to that.

**Comment by n1m1** [comment]
> Yes, you can disable the Updater until then per the usage guide. 

Fantastic!

> It's a major annoyance but it's kinda the purpose of the Beta channel after all. 

For sure. Beta releases are supposed to be for testing and bugs: so, when I set the updater on "Beta Channel", I expected this kind of things sooner or later could have happened. And TBH it has not even been particularly dramatic: no data lost, no device brick, no dragons spitting fire flames from the Pixel USB port.   

> Rolling back the kernel changes isn't really possible without a wipe for the 3a and 3a XL, and since it's the Beta channel we can't dedicate a huge amount of development time to making this friendlier. 

Absolutely understandable.

> Since Android 11 will have those kernel changes again, it should upgrade cleanly to that.

Wonderful. Will wait until GrapheneOS is rebased on Android 11.
