### ISSUE TITLE
couldn't find remote ref refs/tags/aosp_sargo

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [GrapheneOS/os_issue_tracker#291]
Hi,

first time building aosp here.
I am trying to follow the build instructions, but getting this message:

As it says: "You likely want to use the most recent stable tag, not the development branch"

So I move on and just do: 

```
mkdir grapheneos-aosp_sargo
cd grapheneos-aosp_sargo
repo init -u https://github.com/GrapheneOS/platform_manifest.git -b refs/tags/aosp_sargo
```

Error: 
```
repo init -u https://github.com/GrapheneOS/platform_manifest.git -b refs/tags/aosp_sargo
Downloading Repo source from https://gerrit.googlesource.com/git-repo
remote: Counting objects: 1, done
remote: Finding sources: 100% (31/31)
remote: Total 31 (delta 11), reused 31 (delta 11)
Unpacking objects: 100% (31/31), 55.05 KiB | 732.00 KiB/s, done.
Downloading manifest from https://github.com/GrapheneOS/platform_manifest.git
fatal: couldn't find remote ref refs/tags/aosp_sargo
manifests:
fatal: couldn't find remote ref refs/tags/aosp_sargo

fatal: couldn't find remote ref refs/tags/aosp_sargo
manifests:
fatal: couldn't find remote ref refs/tags/aosp_sargo

fatal: cannot obtain manifest https://github.com/GrapheneOS/platform_manifest.git

```

**Comment by thestinger** [comment]
There's no `aosp_sargo` tag.

**Comment by thestinger** [comment]
You should get support on the IRC / Matrix channel. The issue tracker is only for tracking issues.

**Comment by thestinger** [comment]
You left the channel before anyone could respond. Someone did post a response after you left.

**Comment by hp8wvvvgnj6asjm7** [comment]
> You left the channel before anyone could respond. Someone did post a response after you left.

I think that I received all the responses.
Maybe it was when my Laptops wifi crashed while  Android Kernel was building.

I had a couple of good hints on the irc. Thank you.
