### ISSUE TITLE
authenticated network time updates

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os_issue_tracker#3]

**Comment by thestinger** [comment]
This could simply fetch the time from a grapheneos.org server via TLS. It doesn't need to be extremely precise. The existing client is already an SNTP client rather than a full blown one.

**Comment by madaidan** [comment]
[Sdwdate](https://github.com/Whonix/sdwdate) might be a good time sync mechanism to use.There's more documentation [here](https://www.whonix.org/wiki/Sdwdate).
