### ISSUE TITLE
redo APN updates from CarrierSettings for Android 10

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os_issue_tracker#308]

**Comment by thestinger** [comment]
cc @daradib

**Comment by thestinger** [comment]
@daradib We're still working hard on the port to Android 11 and this doesn't necessarily need to be ready for the first release. There's a long way to go both in terms of porting over all the features and bringing up device support. This is device-specific so it requires having working device support to actually test it.

**Comment by thestinger** [comment]
@daradib This is starting to come together. There's android-prepare-vendor support for the Pixel 2 and Pixel 2 XL now. Hopefully we get it for the other devices soon including whatever you're using for development yourself.

**Comment by daradib** [comment]
Thanks for flagging me. I have a Pixel 3a on hand that I'll try to test with. I think merging carriersettings-extractor into android-prepare-vendor would be ideal (AOSPAlliance/android-prepare-vendor#28), otherwise I can make PRs to the device repos for 11. I'd like to get any changes done before October so you're able to include them in the first release.

**Comment by ilikenwf** [comment]
@thestinger I would need to update my build environment for testing, but with Visible, would it just be cherry picking, building, and testing that particular commit from the latest stable release?

**Comment by thestinger** [comment]
No, it needs to be regenerated from the new factory images.

**Comment by daradib** [comment]
I'll try to prepare PRs to the GrapheneOS device repos later this week (hopefully by Thursday), similar to those we did for Android 10 but regenerated and with the makefile changes for Android 11. @ilikenwf would greatly appreciate if you're able to test it.

**Comment by thestinger** [comment]
A preliminary version of this has been implemented. It would be helpful if you could review it though @daradib.

**Comment by daradib** [comment]
@thestinger @anupritaisno1 looks great, thank you. The `apns-full-conf.xml` file in each device repo matches the ones I generated from build RP1A.200720.009. The makefile changes also look correct. For Pixel 3+, I believe the reference to `mainline.mk` in the makefile comment should be changed to `aosp_product.mk`, but it's fine as is.

I'll test the next beta build.

**Comment by daradib** [comment]
RP1A.200720.009.2020.09.25.00 looks good. Correct APN and cellular data and VoLTE calling are working on a Pixel 3a and a Pixel 3 XL, tested with and without factory reset, respectively. @ilikenwf Visible should work again.

**Comment by ilikenwf** [comment]
I can confirm that it works! Thank you everyone - I would have tested sooner but hadn't noticed the new build.

**Comment by ilikenwf** [comment]
FYI - I thought there was a regression on this one with yesterday's release, but it took a reboot to get things working properly again after the update, in case anybody else runs into LTE connection issues.
