### ISSUE TITLE
Bluetooth is on by default after installing the latest beta

### ISSUE THREAD

**Issue by Lia-EoT** [GrapheneOS/os_issue_tracker#327]
After sideloading the latest beta preview, the bluetooth was turned on by default, despite it being off prior to sidoading.

**Comment by thestinger** [comment]
That seems strange, because we're definitely still setting `def_bluetooth_on` to `false` and I see where it's used.

**Comment by thestinger** [comment]
I think you must have accidentally pressed on the quick tile at some point. I've tested and this doesn't happen on any of the 8 supported devices for me when upgrading.
