### ISSUE TITLE
[BUG: Theming] Device theme restores itself to default

### ISSUE THREAD

**Issue by heckarman** [GrapheneOS/os_issue_tracker#3276]
I changed the wallpaper and didn't like the initial theme that the `Wallpaper & Style app` set. I changed the color palette to second one from the left (left most color palette is the default one).  

Sometimes, after some hours, after reboot, or when an error occur say kernel crash or something that result in device to hang / not respond, the theme changes to default one.  

I've been observing this since I changed the Wallpaper and started to use non-default theme.

**Comment by Letgamer** [comment]
I got the same issue throughout all updates since October on my Pixel 7. As it is most likely an upstream bug I haven't considered opening a Issue here

**Comment by Letgamer** [comment]
This issue can be closed as it was fixed with the new update to Android 14 QPR2👍
