### ISSUE TITLE
 RP1A.200720.009.2020.09.18.13 Pixel 3A - No Network Connectivity - Not Sure if Missing Visible APN Or Something Else

### ISSUE THREAD

**Issue by ilikenwf** [GrapheneOS/os_issue_tracker#329]
Upon updating from the build that had the incompatible fs issues to this build, the device no longer connects to the mobile network.

**Comment by ilikenwf** [comment]
I ended up wiping and flashing to the latest stable, and all is well there - I'm betting some carrier config stuff isn't pulled in yet or something.

**Comment by inthewaves** [comment]
Likely part of https://github.com/GrapheneOS/os_issue_tracker/issues/308

**Comment by thestinger** [comment]
Closing in favour of #308 with the assumption that this is related. That issue does need to be worked on or the release is going to be made to Stable without it.

**Comment by thestinger** [comment]
It was definitely the APN configuration work that fixed these issues for Visible so that will need to be added back for it to work again. I haven't seen work on it yet and we won't delay the release for it, particularly for devices without maintainers.
