### ISSUE TITLE
Gallery app - crashing after editing (e.g., cropping) image

### ISSUE THREAD

**Issue by HeadyWook** [GrapheneOS/os_issue_tracker#330]
In recent beta release, gallery app is crashing after editing an image. It also deletes the image after crashing.

**Comment by count-null** [comment]
Came here to report this issue as well.
To reproduce: 
- take a screenshot
- edit
- crop
- tap checkmark
- tap save

The gallery app will crash and the screenshot is not saved.

**Comment by thestinger** [comment]
This has been fixed for the next release.
