### ISSUE TITLE
Biometrics to unlock some applications don't work

### ISSUE THREAD

**Issue by NukeManDan** [GrapheneOS/os_issue_tracker#334]
Around the last beta release, I am now unable to unlock _some_ applications with biometrics. The unlock of the device works, as well as https://signal.org specifically, but others do not. The trigger never seems to fire to allow for the print reader to engage. 

Using Pixel3 with build `RP1A.200720.009.2020.09.18.13`

I deleted the fingerprint and removed this from applications not able to detect any more, input a new fingerprint, and now am unable to add a biometric unlock on the applications that had one previously. 

Applications in question: https://bitwarden.com/ and https://element.io/

**Comment by thestinger** [comment]
See previous bugs filed about this, which has been fixed for the next release.

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/os_issue_tracker/issues/326
