### ISSUE TITLE
clock app stopped working

### ISSUE THREAD

**Issue by Saroumane** [GrapheneOS/os_issue_tracker#335]
Hello,

I have a Pixel 3a, build QQ3A.200805.001.2020.09.11.14 since day of release.
This week, stock alarm/clock app stopped working 3 times like for https://github.com/GrapheneOS/os_issue_tracker/issues/218 
2 differences with issue #218  : 
-  I had no popup warning
- when I open clock app after it crashed, I should see the clock icon back in top status bar. Not this time. I had to manually toggle the button (to 'off', then to 'on' again) of my daily alarm (monday to friday) to have the clock icon back.

**Comment by thestinger** [comment]
Try clearing the app data for the clock app.

The app is significantly overhauled in AOSP 11. GrapheneOS based on AOSP 10 is no longer actively developed, so we won't be taking issue reports that are likely not relevant anymore in the current branch.
