### ISSUE TITLE
Google Play Services Notifications Capability not Being Detected by Installed Apps

### ISSUE THREAD

**Issue by AtmosphericIgnition** [GrapheneOS/os_issue_tracker#3354]
Hi, since installing GrapheneOS about a month ago, I have been having issues with my notifications. I have Google Play Services, Google Play Store, and the Google Service Framework installed, network access enabled for all three, and all three are set to "unrestricted" battery access.
Despite this, I'm still not receiving notifications for most of my apps. On first run, Signal shows a dialog saying that it hasn't found Google Play Services on my device, and will need to run a background service for notifications. Apps that run locally (like Tasks) have no issues with notifications, but Signal need to be running a background service for me to receive notifications, and Proton Mail is not sending me push notifications at all.

I have tried factory resetting GrapheneOS (only preserving my e-SIMs), I only installed my messaging apps from the Google Play Store. On my new install, I first installed the Google Services, waited for a moment, rebooted my phone, and only then signed in and installed all my other apps. Are there any troubleshooting steps I could follow? Anything I should look for in my system logs? Thank you.

I tried the following troubleshooting steps in the following order:

- Checked that all 3 Google Services are set to "unrestricted" battery life
- Updated to the newest release of GrapheneOS
- Gave Google Play Services permission to send notifications
- Reinstalled Signal, and other offending applications
- Reinstalled all my applications from the Google Play Store, instead of the Aurora Store.
- Reinstalled all the Google Applications
- Searched the system log (I had no clue what to search for, so I tried things like "Google", "push", "signal", "notification", "crash", but nothing that came up raised any red flags for me.)
- Searched for the issue online, and asked twice in the GrapheneOS Matrix
- Factory reset my phone (preserving only e-SIMs
- Set up GrapheneOS again, first installed the 3 Google Services components, waited for a moment after install, rebooted my phone, then installed all my necessary apps from the Google Play Store.
- Realized I'm still having the issue
- Reinstalled GrapheneOS via the Web Installer
- Set up GrapheneOS again, issue still persists

I'm running the latest version of the Google Services, latest version of GrapheneOS (2024031400) installed via the Web Install on a Pixel 8 Pro. I have memory tagging enabled for all apps. All the GrapheneOS apps are up to date.

I can supply system logs, try different debugging methods, using the ADB, or anything you think might help me solve the issue. After a month of trying to troubleshoot this, I'm officially out of ideas on how to solve this issue on my own, which is why I made this issue.

Thank you for any help, please let me know what further troubleshooting information I can provide.

**Comment by chris42** [comment]
Just as an FYI, it might also be an issue with Signal/Molly. I have the same issue on my Pixel Tablet, however it seems, that only Molly is affected, whilst Whatsapp is working. However it is hard to tell, what is polling and what is using FCM. So might also happening with Whatsapp as well.

**Comment by chris42** [comment]
> @chris42 It sounds like you installed Molly before sandboxed Google Play. Signal can't cope with switching approach based on installing it afterwards. Most apps handle this fine, Signal doesn't.

The tablet was running for weeks already with sandboxed Google Play before installing Molly, so I can cross the wrong install order off the list. As said, it might also be in Molly. E.g. it might mess up in checking for google services. But there is no way to see what is registered and what not, so this is fishing blind.

**Comment by muhomorr** [comment]
@AtmosphericIgnition Which Play services version do you have? Try updating to the latest one offered by Play Store, if you haven't already.

**Comment by muhomorr** [comment]
@AtmosphericIgnition Are you blocking access to Google servers at device or network level?

**Comment by Youngblood50** [comment]
> I do typically use a private DNS server with a few custom rules (blocking Google Analytics, Facebook, and some other common trackers), but even after disabling my DNS completely, and falling back on the ISP DNS server, I'm still not getting notifications.
> 
> I have also gone through the DNS logs, and I could not find anything that raised an immediate red flag.
> 
> I also tested everything on just cellular data with the regular carrier provided DNS server, to no avail.

You need to disable your dns blocking, then reset the app and set it up again from scratch. i did some investigations back in the day where my dns had the same issue. signal for example only tries once to register for push messaging. if it fails, it'll permanently fall back to websocket method
