### ISSUE TITLE
Camera App not working 

### ISSUE THREAD

**Issue by Azazelice** [GrapheneOS/os_issue_tracker#338]
Hi

Connection to camera app error. Can't open the camera app. I have tried reseting cashe and clearing all data.

Any suggestions?

Regards.
D.

![Screenshot_20200927-192359](https://user-images.githubusercontent.com/5130594/94371458-08d48680-00f7-11eb-9c4b-c1f32a0e718d.png)

**Comment by thestinger** [comment]
Also, what happens after a reboot?

**Comment by Azazelice** [comment]
Im currently running "Google play system update 11" on a Pixel 3a. This happened after the latest update (RP1A.200720.009.2020.09.25.00 night before). Restart does nothing.

**Comment by thestinger** [comment]
Can't reproduce this and it doesn't seem like others can either. Not sure what could be different about your device to cause an issue like this.

**Comment by beerisgood** [comment]
On Reddit a user had the same problem but a reboot help him.

**Comment by Azazelice** [comment]
> Can't reproduce this and it doesn't seem like others can either. Not sure what could be different about your device to cause an issue like this.

I'm not sure either. I had Net Guard and DNS66   installed and could not get Net Guard to select any of the host files in it's config. So I decided to uninstall it and saw the update and restarted my phone after the before mentioned update. All has been weird since. The camera app doesn't want to work. I can't install Net Guard anymore. And as I have mentioned before, no amount of restarts will resolve this issue. Maybe if someone can advice me on how I can go about compiling a bug report/log or a tool I can use so that I can mail of to someone? That would be great. Thanks

**Comment by Azazelice** [comment]
> On Reddit a user had the same problem but a reboot help him.

I wish it was that simple :)

**Comment by beerisgood** [comment]
> I can't install Net Guard anymore. 

Did you install the apps from F-Droid? Then read that: https://github.com/GrapheneOS/os_issue_tracker/issues/341#issuecomment-699903065

**Comment by Azazelice** [comment]
> > I can't install Net Guard anymore.
> 
> Did you install the apps from F-Droid? Then read that: [#341 (comment)](https://github.com/GrapheneOS/os_issue_tracker/issues/341#issuecomment-699903065)

Yes, I did
![Screenshot_20200928-211253](https://user-images.githubusercontent.com/5130594/94475525-7c49c700-01cf-11eb-9013-2dc716ddfd8a.png)

**Comment by Azazelice** [comment]
> > > I can't install Net Guard anymore.
> > 
> > 
> > Did you install the apps from F-Droid? Then read that: [#341 (comment)](https://github.com/GrapheneOS/os_issue_tracker/issues/341#issuecomment-699903065)
> 
> Yes, I did
> ![Screenshot_20200928-211253](https://user-images.githubusercontent.com/5130594/94475525-7c49c700-01cf-11eb-9013-2dc716ddfd8a.png)

![Screenshot_20200928-214745](https://user-images.githubusercontent.com/5130594/94478962-51ae3d00-01d4-11eb-99da-95fa050e73ac.png)

**Comment by thestinger** [comment]
Read https://github.com/GrapheneOS/os_issue_tracker/issues/341#issuecomment-699903065 about the issue with some apps in the official F-Droid repository. This is an F-Droid issue and not something wrong with GrapheneOS. v1 signatures are not allowed with API 30+. Android 10 only supported API 29 so it couldn't detect that these apps in the F-Droid repository are broken. It's something that they'll have to fix. There's nothing we can do about it. Also, in the future, please restrict each issue to a single topic.

**Comment by thestinger** [comment]
I removed the off-topic conversation. This issue should be about the camera problems you're having. If you have other issues aside from the known problem of F-Droid having broken builds of some apps, please file separate issues.

**Comment by Azazelice** [comment]
> I removed the off-topic conversation. This issue should be about the camera problems you're having. If you have other issues aside from the known problem of F-Droid having broken builds of some apps, please file separate issues.

Sure, thanks. I was just adding insight to things that might be relevant as I have no idea what could have caused this.

**Comment by Azazelice** [comment]
I will wait for a reply on the camera issue.

**Comment by thestinger** [comment]
Can you get logs after a fresh reboot where this occurs from either the built-in bug report tool or adb logcat?

**Comment by drossbox** [comment]
I had the same problem on a 3a after the upgrade from 10 to 11. More than one restart was required, but after multiple attempts the camera opened instead of crashing - and has been fine since.

**Comment by thestinger** [comment]
If there is something wrong with the state of the camera hardware, you may have to power off and then power back on. A reboot may not entirely reset the state of peripherals if they don't actually end up losing power.

**Comment by thestinger** [comment]
A reboot is not entirely the same as turning it off and on again when it comes to hardware. It sounds like this might be a hardware / firmware issue with the camera. I can't think of any other reason it would happen for a tiny subset of users rather than everyone, when the firmware, OS, etc. is entirely the same across devices and it doesn't appear to be an issue involving any of the persistent state. Seems more like the hardware has somehow ended up in a bad state, maybe after a firmware upgrade, and needs to be turned off and back on again.

**Comment by anupritaisno1** [comment]
use a third party camera app like open camera and try to switch to the front camera or try to see if front camera works during face enrollment

if it works do not bother reporting it as this is a known hardware issue that happens on a few pixel devices. contact google to get your phone repaired

**Comment by Azazelice** [comment]
> use a third party camera app like open camera and try to switch to the front camera or try to see if front camera works during face enrollment
> 
> if it works do not bother reporting it as this is a known hardware issue that happens on a few pixel devices. contact google to get your phone repaired 

Hi
I get a ID:1 code with open camera.
Is this the same as what you where talking about?
![Screenshot_20200930-222859](https://user-images.githubusercontent.com/5130594/94736641-d9c74a80-036c-11eb-872a-f382fe5b8f77.png)

**Comment by thestinger** [comment]
You can't use the camera from multiple apps at the same time.

**Comment by thestinger** [comment]
Power off the device, power it back on again and test with the built-in Camera app.

Power off the device, power it back on and test with the Open Camera app.

Power it off instead of rebooting.

Report back with the results, and if it's not working, you need to provide logs from `adb logcat` or the OS bug report capture tool as I mentioned above.

**Comment by thestinger** [comment]
A new issue should be filed by someone that can provide the necessary information.

**Comment by thestinger** [comment]
> Power off the device, power it back on again and test with the built-in Camera app.
>
> Power off the device, power it back on and test with the Open Camera app.
>
> Power it off instead of rebooting.
>
> Report back with the results, and if it's not working, you need to provide logs from adb logcat or the OS bug report capture tool as I mentioned above.

Please try this and report back here if you can though.

**Comment by Azazelice** [comment]
I have loaded the"sargo" for Pixel 3a android 9 Stock ROM back onto the device to test the camera. It does work but it will not update to the OTA 11 Update. The phone gets stuck in A boot loop. I know this is not a graphene issue and I should not post it here. I just wanted to report on the current status of the camera. Thanks for the help anyways to all that were involved.
