### ISSUE TITLE
Network time synchronization is not working

### ISSUE THREAD

**Issue by skystar-p** [GrapheneOS/os_issue_tracker#340]
Despite "Use network-provided time" option is set in "Date & time" settings, time is not synchronizing with ntp pool. There was an attempt to resolve ntp pool host(2.us.pool.ntp.org), but nothing happened... Rebooting and toggling the option seems no hope. This issue was found after updating system, and still persists.

Device name: Pixel 3
Android version: 11
Build number: RP1A.200720.009.2020.09.25.00

Thank you in advance!

**Comment by thestinger** [comment]
cc @renlord 

I can confirm that this doesn't seem to be working since the Android 11 migration.

**Comment by thestinger** [comment]
Also, with our configuration, it shouldn't be trying to resolve the NTP host.

**Comment by renlord** [comment]
@skystar-p do you have logs?

**Comment by skystar-p** [comment]
@renlord No, what kind of logs do you need? I will try to collect them.

**Comment by thestinger** [comment]
The issue seems to be that it's not using the result. It's doing the HTTPS time checks but as far as I can tell, it's not updating the clock.

**Comment by thestinger** [comment]
Replaced with https://github.com/GrapheneOS/os_issue_tracker/issues/342 which is more specific about what's happening.
