### ISSUE TITLE
Plex not loading

### ISSUE THREAD

**Issue by adtvp** [GrapheneOS/os_issue_tracker#343]
Thanks for responding so quickly. I downloaded Plex from Aurora up until the update it was fine. I don't have many apps on my phone (23 including ones I can't remove) so this issue could be larger.

**Comment by thestinger** [comment]
Can you give a list of problematic apps and where you got them? Is it just Plex?

**Comment by thestinger** [comment]
What exactly happens when you open it?

Can you provide logcat logs from `adb logcat` or the bug report capture tool? You can email it to contact@grapheneos.org. If you use the bug report capture tool within the OS, it will try to share it via an email app if available.

**Comment by adtvp** [comment]
The Plex screen starts up then crashes immediately.

**Comment by thestinger** [comment]
What message does it show when it crashes? You'll also need to provide logcat output.

**Comment by adtvp** [comment]
I hope I uploaded these properly and this is what you need. After the Plex load screen pops up it disappears and I see a blank screen when the going to the open apps page but when I select the application it disappears again.

[logcat_09-28-2020_09-06-22.txt](https://github.com/GrapheneOS/os_issue_tracker/files/5292490/logcat_09-28-2020_09-06-22.txt)
[logcat_09-28-2020_09-08-01.txt](https://github.com/GrapheneOS/os_issue_tracker/files/5292492/logcat_09-28-2020_09-08-01.txt)

**Comment by adtvp** [comment]
Did you need any other information?

**Comment by anupritaisno1** [comment]
not really

**Comment by anupritaisno1** [comment]
```[09-28 09:04:11.223 5894:5980 F/libc]
Pointer tag for 0x49387db360 was truncated.

[09-28 09:04:11.224 5894:5980 F/libc]
Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 5980 (BootManager), pid 5894 (plexapp.android)
```

this seems to be an issue with the plex app 

see https://source.android.com/devices/tech/debug/tagged-pointers

**Comment by thestinger** [comment]
That means this is a bug in the app uncovered by Scudo. Also, we should add support for TBI to hardened_malloc too.

**Comment by thestinger** [comment]
This is implemented by libc in the wrapper around malloc, so this app is broken on Android 11 in general rather than on GrapheneOS specifically. They need to fix the bug or at least disable memory tagging as a short-term workaround until they fix the problem.

**Comment by adtvp** [comment]
Thanks. I forwarded the information to them.
