### ISSUE TITLE
Investigate why memory initialization hardening is broken for pixel 4a kernel and if zero init is fine and only pattern init is broken

### ISSUE THREAD

**Issue by anupritaisno1** [GrapheneOS/os_issue_tracker#345]

**Comment by anupritaisno1** [comment]
Google turned off zero based heap init too so it is very likely there is heap corruption too that we'll need to try to track down

**Comment by anupritaisno1** [comment]
also the commit says usb pd is affected

**Comment by anupritaisno1** [comment]
This is mostly resolved but we are waiting for more response from testers

**Comment by thestinger** [comment]
Going to close this because we don't have confirmation this was ever an issue for zero-based initialization. Google decided to use non-zero-based, perhaps because their kernel team didn't want to use an option supposedly (but not really) marked for removal.
