### ISSUE TITLE
incorrect time after the recent update

### ISSUE THREAD

**Issue by sudoroad** [GrapheneOS/os_issue_tracker#348]
Hi,
I'm using Pixel 3a, OS Android 11. After the 2020.09.25 update, the time has been constantly having a 3-minute error. Hence all codes given by the 2FA app are now invalid. Restart didn't help

**Comment by thestinger** [comment]
See https://github.com/GrapheneOS/os_issue_tracker/issues/342. This is already addressed for the next release.
