### ISSUE TITLE
Problems with USB-C audio pause/resume on A11

### ISSUE THREAD

**Issue by alzxjm** [GrapheneOS/os_issue_tracker#349]
Device: Pixel 4 XL
Version: RP1A.200720.009.2020.09.29.20

I'm experiencing odd behavior seemingly related to audio playback on both the USB-C headphones that came with the phone and with conventional headphones using the OEM USB-C adapter/dongle. These issues began after the upgrade to Android 11 and do not seem to happen on other phones/OS's.

Sometimes if I use the in-line remote to pause audio during playback with the screen locked the USB-C headphones seem to be disconnected: pressing the play button does nothing and when I unlock the phone and use the app to resume playback it will use the device speakers, not the headphones. I have to unplug the headphones and plug them back in.

This behavior does not always happen. Sometimes resume occurs normally. It does not seem to be related to how long I leave audio paused; sometimes playback will continue after several minutes of pause time, sometimes it will fail to resume after only a few moments.

Once or twice, resuming playback with in-line remote has crashed the phone, triggering a reboot. This occurs with several different audio apps.

This behavior does not happen with Bluetooth earbuds.

**Comment by thestinger** [comment]
Does this ever happen when the screen is unlocked? By default, GrapheneOS disables detection of new USB peripherals when the device is locked. Please try disabling that feature to see if that's the cause, which would mean that this isn't a bug.

**Comment by charlesctr** [comment]
I tried with USB-C Headphone on Pixel 3a XL/Bonito.

Allow new USB when unlocked :
 -> When plugin the headphone when phone is unlocked every controls work as expected (Play/Pause/Next/Volume).
-> When plugin the headphone when phone is locked no controls are working and music is played from the phone speaker .

Weird behavior : when unlocking the phone and manually playing the music, a system notification pops up saying : "Android System - Charging connected device via USB". My headphone are simple wired USB-C headphone.

Allow new USB (every time)
 -> When plugin the headphone when phone is unlocked every controls work as expected (Play/Pause/Next/Volume).
 -> When plugin the headphone when phone is locked every controls work as expected (Play/Pause/Next/Volume).

Tested on RP1A.201005.004.2020.10.23.04 ( beta)

**Comment by thestinger** [comment]
> When plugin the headphone when phone is locked no controls are working and music is played from the phone speaker .

This is the expected behavior.

**Comment by thestinger** [comment]
> Weird behavior : when unlocking the phone and manually playing the music, a system notification pops up saying : "Android System - Charging connected device via USB". My headphone are simple wired USB-C headphone.

That seems like a normal quirk of USB-C.

**Comment by thestinger** [comment]
@alzxjm Can you try to figure out if some of this is related to the intended functionality of the USB peripheral feature? It is possible that we have features uncovering unrelated issues tied to upstream bugs in the USB stack, etc.

**Comment by alzxjm** [comment]
I changed the USB settings to "Allow new USB peripherals" and, so far, the behavior in my initial complaint has not reoccurred. Do you suppose that, with "Allow new USB peripherals when unlocked" enabled, perhaps while my audio is paused the audio player app goes to sleep or hibernates? Not sure of the exact term. When this happens, the USB device (my headphones) is "kicked off" because it is not being used.

Then, when I unlock the phone and resume playback manually (i.e. without the headset's in-line controls) it is as if I am trying to start playback without having plugged in a USB headset since my headset has not yet been allowed? I'm not sure how Android handles USB devices when the app using them goes to sleep (if that is indeed what is happening).

Is there anything else I can do to test/evaluate? I will try to get the problem to replicate itself in the meantime.

**Comment by alzxjm** [comment]
OK so as soon as I changed the setting back to "Allow new USB peripherals when unlocked" the behavior re-emerged: while playing audio I locked the phone and, after the phone was locked I used the headset controls to pause music. I waited for a few minutes, hit Play again, and nothing happened. Leaving the headset plugged in, I unlocked the phone and used the app to resume playback, it played through the device speakers as if there were no headphones plugged in.

I imagine this is expected behavior and that the audio app is "letting go" of the USB device after a certain amount of time spent paused. Do you think this is correct?

**Comment by thestinger** [comment]
I think this is the design of the USB device, not the app, OS or phone hardware. It appears to add a new device when you press the buttons, probably to save power.

**Comment by thestinger** [comment]
It sounds like the USB device goes into a suspended state from lack of use and some of the USB devices it exposes disappear. I don't think there's a bug here rather than the feature functioning as intended.

**Comment by dznsm** [comment]
I often listen to music/podcasts/audio books on the usb-c headphones that came in the box with the phone. Noticed some time back that if I paused with the button on the headphone wire, playback wouldn't always resume if I
clicked it again. 
More recently I discovered that pressing it a number of times does,  eventually,  restart the audio.
This is with my Pixel 3XL
