### ISSUE TITLE
A list of features I would like to see added to Graphene OS.

### ISSUE THREAD

**Issue by galyoninion** [GrapheneOS/os_issue_tracker#353]
This is not a bug report, but my request.
I use Graphene OS every day, and I would like to see the following features added in the future.

- block the domain, IP, JavaScript, etc. specified for each application from "Settings> Privacy> Authority Manager> Network".
- 
- Give permission to each authority that appears in "Settings> Privacy> Authority Manager> All Authority". For example, in the case of "files and media", allow "change or delete the contents of the shared storage" and "read the contents of the shared storage" separately.

- A function to give "only this time permission" has been added from Android 11, but it is troublesome to select "only this time permission" every time the app is started, so the app is automatically set to "only this time permission". Prevent notifications from appearing at startup.
-
- Always open new tabs in private tabs from Vanadium settings. It's always annoying to open Vanadium> open a private tab> search.
- 
- Allow Vanadium bookmarks to be saved with html or other extensions like Bromite.

**Comment by renlord** [comment]
@galyoninion This is bad form to create an issue.

Please split feature requests into individual issues.

Your personalised feature requests should be motivated by a broad-audience use case. Leading a feature request with "I would like to see the following features added in the future" does not sound right.

**Comment by thestinger** [comment]
Please file separate issues for each topic.

> block the domain, IP, JavaScript, etc. specified for each application from "Settings> Privacy> Authority Manager> Network".

I'm not sure what you mean by this. How is this different from Settings > Privacy > Permission manager?

> Give permission to each authority that appears in "Settings> Privacy> Authority Manager> All Authority". For example, in the case of "files and media", allow "change or delete the contents of the shared storage" and "read the contents of the shared storage" separately.

I'm not sure what you mean by this either. How is this different from Settings > Privacy > Permission manager?

> Always open new tabs in private tabs from Vanadium settings. It's always annoying to open Vanadium> open a private tab> search.

Vanadium has a separate issue tracker.

> Allow Vanadium bookmarks to be saved with html or other extensions like Bromite.

Should also be on the Vanadium tracker.

**Comment by thestinger** [comment]
Please file separate issues for each topic.

> block the domain, IP, JavaScript, etc. specified for each application from "Settings> Privacy> Authority Manager> Network".

I'm not sure what you mean by this. How is this different from Settings > Privacy > Permission manager?

> Give permission to each authority that appears in "Settings> Privacy> Authority Manager> All Authority". For example, in the case of "files and media", allow "change or delete the contents of the shared storage" and "read the contents of the shared storage" separately.

I'm not sure what you mean by this either. How is this different from Settings > Privacy > Permission manager?

> A function to give "only this time permission" has been added from Android 11, but it is troublesome to select "only this time permission" every time the app is started, so the app is automatically set to "only this time permission". Prevent notifications from appearing at startup.

Not really sure what you mean by this. If you want to grant the permission every time, that's what granting it persistently already does. It would be insecure to automatically grant all requested permissions, even just once.

Also, what is the connection to notifications?

> Always open new tabs in private tabs from Vanadium settings. It's always annoying to open Vanadium> open a private tab> search.

Vanadium has a separate issue tracker.

> Allow Vanadium bookmarks to be saved with html or other extensions like Bromite.

Should also be on the Vanadium tracker.
