### ISSUE TITLE
Secure Power Button

### ISSUE THREAD

**Issue by hpnightowl** [GrapheneOS/os_issue_tracker#354]
It's like whenever a stranger pick my device it should be like it wont be able to turn my device off. It will require the authentication to use the power tile of power menu of my device. it will be somewhat same as we have secured the QS tile at Lock Screen having a keyguard in power menu tiles to.If you want i can elaborate more about it :)

**Comment by thestinger** [comment]
They can just hold the power button, or take apart / break the phone. I don't think this is something we want to do as I don't see any benefit to it.

**Comment by hpnightowl** [comment]
but i mean to say if my friend not a stranger had picked my phone and kept it somewhere after switching it off what if we don't give them access to power button and taking about holding the power button will restart my phone it will not power it off.

**Comment by thestinger** [comment]
I don't understand the purpose of the request. Holding the power button triggers a reboot but then they can boot up the bootloader (outside the control of the OS) and power if off from there. I also don't really understand how powering it off is special. Why is rebooting it okay but powering it off is not? Also, what about just letting the power drain, breaking the phone, etc. I don't understand what you want to accomplish. Doesn't seem to make sense as an OS feature though.

**Comment by thestinger** [comment]
There's nothing "secure" about the proposed implementation. It doesn't have a threat model and doesn't improve security in any way. Just seems like a change for the sake of making a change and adding complexity.

**Comment by hpnightowl** [comment]
ok i got your point
