### ISSUE TITLE
Proper AMOLED black (#000000) dark mode

### ISSUE THREAD

**Issue by gosh-darn** [GrapheneOS/os_issue_tracker#355]
I must say I rather enjoyed having proper black backgrounds on my old Pixel (1st gen with Stock OS). The dark gray on GrapheneOS just does not look as good to me. Would appreciate having the option!

**Comment by SB13X** [comment]
I'd like to add my support but not just for the amoled black settings/QS shade but a colour change option to override the awful teal.

**Comment by Exilion666** [comment]
+1 to pure black dark mode in settings and phone+sms app

**Comment by D3vTs4113** [comment]
> I'd like to add my support but not just for the amoled black settings/QS shade but a colour change option to override the awful teal.
> 
> Something akin to what is implemented by DU: https://github.com/DirtyUnicorns/android_vendor_themes

do you know how to add this theme to our grapheneOS system please?

**Comment by ralph303** [comment]
It's not only a matter of taste, but for my eyes the dark mode (=gray) in GrapheneOS is much more straining for the eyes than a proper dark mode (AMOLED black with white text) like in MIUI for example.
