### ISSUE TITLE
Relatively frequent system UI crashes when an app hangs after android 11 update (3XL)

### ISSUE THREAD

**Issue by dreth** [GrapheneOS/os_issue_tracker#357]
Hello!

I have been having an issue recently in some applications that feels like a memory leak. Where an app hangs and the whole system UI becomes unresponsive for an extended period of time and the options are to wait very very long (sometimes upwards of 20 minutes) or to restart the phone.

This only happens after the update to android 11 (im on the latest update, the patch after the first A11 update, im on stable channel). It happens usually about once a day.

The situations that have triggered the crash in my experience have been:
 - watching stories on instagram
 - using google maps inside vanadium
 - going to relatively heavy websites in vanadium (happened with reddit and the ryanair websites)
 - taking a picture on whatsapp, the moment before sending it there is always a very long delay between the snap and showing the picture itself, but on this specific occurrence the picture just never showed and the phone became fully unresponsive
 - using OSM to navigate to a place in the OSM app from f droid

Apps in the background also relatively often become unresponsive but it doesnt seem to trigger a full UI crash, only active apps ive mentioned

I'm on 3 XL and i can provide logs or reports or anything given that someone tells me how to get them

Thanks!

**Comment by thestinger** [comment]
Doesn't really sound like there's a memory leak involved.

**Comment by dreth** [comment]
well whatever it is, if theres anything i can do to help, id be happy to (:

**Comment by thestinger** [comment]
Is this still an issue with the latest release shipping the upstream October update and other changes?

**Comment by dreth** [comment]
seems to be happening much less often than in the previous one
but i recall one instance of it right after updating, happened specifically while i was in a whatsapp call and tried to take a picture and send while during the call. Had to restart

ill test if it still happens in other applications and report back

**Comment by dreth** [comment]
okay i had 3 instances of this, one on instagram while one story was switching to the next, on slide for reddit while loading a gif and on whatsapp while in a call trying to go back to the chats to forward a picture

the instagram one the app became unreaponsive and made the ui unresponsive but the ui was frozen for much less than usual and recovered with the app being unresponsive. 

in the slide for reddit instance the ui became fully frozen for long enough that i had to restart the phone

i have noticed that a few of the times in the past while the issue occurred i was also in a whatsapp call, as in this last one.

only the last 2 needed a phone restart as the ui was frozen for too long

**Comment by renlord** [comment]
@dreth related?
https://github.com/GrapheneOS/platform_frameworks_base/commit/76722daf78a8e6ef71cae66ca8c6ec71124f174b

**Comment by dreth** [comment]
@renlord It might be related but I'm really not sure.
The UI doesn't exactly crash, it just doesn't respond for a while until it does. Lately it's only happened on instagram when watching stories and using the camera on whatsapp. Not quite sure of the cause, especially instagram though, it almost never happens anywhere else.

**Comment by dreth** [comment]
after the last update this hasn't happened yet, so far so good

**Comment by thestinger** [comment]
Closing since it seems to be fine now. I don't know what could have resolved it.

**Comment by dreth** [comment]
Thank you for the attention when initially reported @thestinger and for all your commitment to GrapheneOS in general man, the world needs more people like you. 
It's all working well now! thanks again!
