### ISSUE TITLE
Android Auto Crash

### ISSUE THREAD

**Issue by chrishobcroft** [GrapheneOS/os_issue_tracker#3572]
I am experiencing repetitive crashes of Android Auto.

Unaware as to whether it's due to the car or the app, but recently it told me about this:

[Android Auto log e2daa8b9059d.txt](https://github.com/GrapheneOS/os-issue-tracker/files/15454533/Android.Auto.log.e2daa8b9059d.txt)

**Comment by muhomorr** [comment]
Are you using wired (USB) Android Auto?

**Comment by chrishobcroft** [comment]
Yes

**Comment by muhomorr** [comment]
This crash indicates that there's a USB connectivity issue, likely due to a bad cable or port.

**Comment by chrishobcroft** [comment]
OK, will try with a new cable and reopen if this persists.
