### ISSUE TITLE
notification/ringtone/alarm sounds don't work without regular sound playing

### ISSUE THREAD

**Issue by privateseabass** [GrapheneOS/os_issue_tracker#359]
I have a pixel 3a, went through a factory reset, a reinstall of graphene from fastboot, tried clearing media storage cache/storage, same with notification sounds cache/storage, and even let some updates come over time to see if this issue got fixed.

I can play music, and my notifications/ringtones/alarms will work, but if videos/music aren't playing, they won't.
Also, speaker phone doesn't make sound, when i've tried it, as well.

Current build: RP1A.201005.004.2020.10.06.02
Release: stable

**Comment by thestinger** [comment]
Maybe one of your speakers is broken.

**Comment by privateseabass** [comment]
Maybe, but wouldn't that mean that my sound for ringtones should never work?
The ringtones play when music is also playing, after all.

**Comment by thestinger** [comment]
Can you please test if one of the speakers is broken?

**Comment by thestinger** [comment]
Your reasoning about ringtones isn't correct.

**Comment by privateseabass** [comment]
I would, I just don't know how to do that kind of test.
I imagine the audio tests of *#*#0673#*#* OR *#*#0289#*#. Neither of these played a sound, but they didn't on my default OS pixel 2, either.

**Comment by thestinger** [comment]
Ideally, you could check whether this occurs on the stock OS. I'm going to have to assume that it's a hardware issue if we don't have anyone else who can replicate this or a way to narrow it down.

**Comment by privateseabass** [comment]
Brought it to a repair shop, so yeah, it was the speaker.
Apologies for taking your time with this.

**Comment by thestinger** [comment]
No problem. It might help someone else.
