### ISSUE TITLE
Many unexpected system restart after android 11 update (Pixel 3A)

### ISSUE THREAD

**Issue by Ju-Brn** [GrapheneOS/os_issue_tracker#361]
### Summary:

After installing the 2020.10.06.02 update, the system reboots unexpectedly without an error message.

### Repetition:

Varies between a few minutes and several hours.

### When:

In any type of situation: screen locked, during use ...

### Other:

Recent notification: "storage system full"
64 GB / 64 GB
20 GB of user data
**46 GB used by android 11 system ...**

Thanks!

**Comment by beerisgood** [comment]
I don't get any unwanted reboots and my system use 13GB.

**Comment by charlesctr** [comment]
On 3a XL did not have any reboot.
Did you find a pattern before a reboot happened ? A list of apps you open ? Or task you do ?
That way maybe we can try to reproduce these steps and have the same behavior as you.

**Comment by theaeonsolution** [comment]
You can either try a factory reset or try to sideload the update https://grapheneos.org/usage#updates-sideloading to resolve the problem. There is not enough information to recreate or confirm this error on my Pixel 3a. I didn't have this issue when I upgraded to 2020.10.06.02.

**Comment by thestinger** [comment]
Are you on the latest release? There were known issues fixed in the upstream October update.

**Comment by thestinger** [comment]
Which release are you on?

**Comment by theaeonsolution** [comment]
My Pixel 3a is on RP1A.201005.004.2020.10.06.02. Been using it as main driver and haven't had any issues with it.

**Comment by thestinger** [comment]
I mean @Ju-Brn.

**Comment by Ju-Brn** [comment]
Thank you very much for all of your answer.

I think the system restarted because the disk was full.

I tried to poweroff and start again (not a reboot) the space used by the system changed from 46GB to 13GB (as reported by @beerisgood).

Since then I no longer have a problem.

@thestinger: my current version is RP1A.201005.004.2020.10.06.02

However I didn't understand why the system used 46GB ... Previous update or update cache not removed ?

**Comment by thestinger** [comment]
I doubt it has anything to do with Updater. Not going to be able to figure out what was happening now, and these are upstream bugs anyway, nothing to do with our changes.
