### ISSUE TITLE
No LTE on Sprint

### ISSUE THREAD

**Issue by Washnugget** [GrapheneOS/os_issue_tracker#364]
I'm on Sprint and I'm am having an Issue with LTE on the Pixel 3. After flashing to the latest blueline-factory-2020.10.06.02.zip I no longer get a LTE signal. If I revert back to stock ROM, the LTE signal is there. I've tried flashing GrapheneOS over top of the following stock ROMS 10.0.0 (QQ3A.200805.001, Aug 2020), 11.0.0 (RP1A.200720.009, Sep 2020), 11.0.0 (RP1A.201005.004, Oct 2020) ROMS with no joy.

edit: I would also like to add I tried both stable and beta versions.

**Comment by thestinger** [comment]
Sprint has been discontinued and no longer provides proper support for devices. You should switch to the regular T-Mobile network or another carrier with support for standard LTE.

**Comment by Washnugget** [comment]
I understand Sprint merged with T-Mobile and what I'm understanding from their customer service department is the merger won't be complete for at lease a few years meaning Sprint users will still have Sprint accounts and will stay on their network until then. I flashed LineageOS 17.1 over Android 10 in the meantime and everything works just fine. I guess Sprint users will have to wait a few years until the merger is complete in order to use GrahpheneOS. Which kinda sucks.

**Comment by thestinger** [comment]
Or use a carrier with standard LTE that does not require remote access backdoors (which LineageOS includes) to activate devices on their network properly. If you care about privacy and security, it's hard to understand why you would want to use Sprint.

**Comment by Washnugget** [comment]
I wasn't aware of that. I don't use my phone hardly much and pay $30 a month for unlimited everything that's why I use Sprint. I'm looking to switch networks now as I got the Pixel 3 to put GrapheneOS on it. In your opinion, which network would you consider to be the most secured and works best with Graphene?
