### ISSUE TITLE
Pixel 3a reboots sometimes when user profile is changed

### ISSUE THREAD

**Issue by Lalu-sys** [GrapheneOS/os_issue_tracker#368]
Behaviour as discribed above, running latest beta release

**Comment by thestinger** [comment]
You'll need to provide more information. This isn't happening for others so you need to narrow down what about your installed apps, OS configuration, etc. is causing the issue. It could be a hardware problem. Try to get logs showing what happened. Also, you need to distinguish between a reboot and an issue like the system UI restarting.

For now, I have to assume this is the same issue as https://github.com/GrapheneOS/os_issue_tracker/issues/357 unless there is more information to distinguish it from that.
