### ISSUE TITLE
voice calls - counterpart sounds on wrong device

### ISSUE THREAD

**Issue by 4r7urh** [GrapheneOS/os_issue_tracker#371]
Pixel 3a, Version: RP1A.201005.004.2020.10.06.02
On incoming or outgoing voice calls the counterpart sometimes is heard on wrong speaker. 

- By default in a call, voice is heard through internal speaker. Sometimes you hear the other side through the loudspeaker when call is accepted or started
- If you have a bluetooth headset connected, mostly that is used. Sometimes you hear the other side through the internal or loudspeaker when call is accepted or started
- If you are on a call with at bluetooth headset connected and another app makes an announcement during the call (e.g.route direction for navigation, road hazard warning), sometimes voice over bluetooth stops and moved to internal speaker and microphone

In each case you can manually assign the call back to the proper microphone&speaker. But this poses a risk if you have to change back to the hands-free device of the vehicle while driving.

I have no clue how to reproduce this, it happens randomly about 10% of the calls

**Comment by thestinger** [comment]
Please test on the November release that's in the Beta channel right now.

**Comment by 4r7urh** [comment]
I've been testing with 2020.11.05.18 for some days now, issue hasn't occurred any more with that release.
BT devices are 2 BMW cars and 2 different plantronics headsets.

BTW, even with the older releases audio always was playing, it never happened to me that no sound could be heard at all.
Thank you for the great work
