### ISSUE TITLE
Pixel 5 support?

### ISSUE THREAD

**Issue by prestonvanloon** [GrapheneOS/os_issue_tracker#374]
I couldn't find an issue to track support for Pixel 5, so I am creating one here.

Is there any plan to support Pixel 5?
Has any progress been made? If so, how can we track progress?

Thanks!

**Comment by thestinger** [comment]
See https://grapheneos.org/faq#device-support.

Devices need to have a maintenance team to develop and maintain support for them. No one has even started on it for the Pixel 5. Pixel 5 and Pixel 4a 5G are also currently supported via a device-specific branch in AOSP and we're unwilling to use those so official support will have to wait until the next maintenance release at a minimum.

There's absolutely no guarantee that we'll support every Pixel phone. If there's no maintenance team, there won't be support for it. We don't track support for new devices in issues if there's no team working on it.

**Comment by prestonvanloon** [comment]
Perfect, thanks for that response!
