### ISSUE TITLE
Issues for certain Apps to connect to Internet over WiFi

### ISSUE THREAD

**Issue by skaldesh** [GrapheneOS/os_issue_tracker#375]
Today a new problem emerged, where my email, cryptolytics and DAVx5 apps can no longer connect to the Internet while I am on WiFi. But other apps like Threema or Fennec work without problems.  

Is somebody else experiencing these connection issues? Any steps I can take to debug the problem? I am not too experienced in this.  

The things I have tried:
- Reboot
- Hardclose apps and restart them
- Reset WiFi connection
- Check App permissions
- Check APN setting for Mobile data (it is configured exactly like my mobile carrier says it should be...)

**Comment by beerisgood** [comment]
Did you check your DNS settings ?

**Comment by thestinger** [comment]
Please keep issues to a single topic. Carrier issues with mobile data are off-topic for this issue.

**Comment by thestinger** [comment]
Reset your network settings to the default in the Settings app to wipe all of your custom changes and connect to your Wi-Fi network again.

**Comment by thestinger** [comment]
Also, make sure you aren't using a VPN app that's at fault. Wiping the network settings will undo all of that customization though.

**Comment by skaldesh** [comment]
I reset my network settings and connected to my WiFi again. Same behaviour, my Cryptolytics / Fairmail / DAVx5 apps can all not connect to the internet, while Fennec / Threema / Signal can.   
I have no VPN app

**Comment by skaldesh** [comment]
> Did you check your DNS settings ?

No. I never changed them, I am sure of that. And if I did, I guess the reset I just did would have reset those as well

**Comment by thestinger** [comment]
Also make sure you haven't done something like disabling the WebView.

**Comment by skaldesh** [comment]
I only have the system's native WebView and can not disable it, as far as I know.

**Comment by thestinger** [comment]
It is possible to disable so make sure you haven't done that in Apps & notifications -> Show system apps. Also check developer options for changes you may have made. Turn off developer options to reset some of the options.

**Comment by skaldesh** [comment]
I did as you said. WebView is not disabled and I restarted my phone with devOps turned off. Still the same issue :(  
It is so weird, I just checked my NextCloud App (does not connect), Jitsi Meet (does connect) and Spotify (does not connect)

**Comment by skaldesh** [comment]
Ok, I may have discovered something.  
I tried to reinstall the Cryptolytics app from F-Droid to see, if that fixes anything. When installing it, I got the warning that this App was built for an older version of Android (and it still did not work).  
Checking Jitsi, it does not emit that warning on install (so I guess the devs have already updated it).  
Spotify is also "too old".  
Threema and Signal have been updated and are working.  

Could this be the reason? Maybe someone here could check that and download "Cryptolytics" from F-Droid. It simply displays the current value of crypto currencies like bitcoin, ether, etc. I have version "1.0.0"  

My Spotiy version is "8.4.0.539". Pretty old, I'll try to update that and see, if that fixes things

**Comment by thestinger** [comment]
> I got the warning that this App was built for an older version of Android

That's not relevant.

**Comment by thestinger** [comment]
Have you disabled certificates authorities? That's another potential configuration issue.

**Comment by skaldesh** [comment]
I wanted to go with "Fennec" to "github.com", but got hit with an "Address not found" error.  
Navigating to "wikipedia.org" or "google.com" works.

**Comment by thestinger** [comment]
That makes it clear that this is a DNS issue. Do you have this problem across multiple networks?

**Comment by skaldesh** [comment]
I can test that in an hour with a different WiFi. Will report back then. Thanks for helping me, btw @thestinger :)

**Comment by thestinger** [comment]
It sounds like your Wi-Fi network has broken or filtered DNS.

**Comment by skaldesh** [comment]
Since I am in the same network with my laptop and currently writing with you, I doubt that.

**Comment by thestinger** [comment]
That doesn't imply that your laptop is using the same DNS servers.

**Comment by skaldesh** [comment]
I checked the DNS on my Laptop and it uses the one provided by the router. My phone has the same configuration for this network

**Comment by skaldesh** [comment]
Solved. Another Wifi worked, so I checked what the difference was. Apparently my router had some issue, after a restart everything works again.  
Sorry for the incovenience
