### ISSUE TITLE
Make flash-all script check if fastboot exists before checking the version

### ISSUE THREAD

**Issue by anupritaisno1** [GrapheneOS/os_issue_tracker#376]
Currently both the windows and Linux script do not check if fastboot actually exists before checking the version, resulting in errors like:

```
./flash-all.sh: line 17: --version: command not found
./flash-all.sh: line 17: [: -ge: unary operator expected
fastboot too old; please download the latest version at https://developer.android.com/studio/releases/platform-tools.html
```

Not only is it confusing for an end user to understand, it makes the user think that the fastboot version is wrong instead of fastboot not being found in the PATH and doesn't point them to what the error actually is

**Comment by anupritaisno1** [comment]
I can fix the Linux part but I really don't know about how this can be done for Powershell. Some help will be needed for the windows script

**Comment by maximbaz** [comment]
```sh
if ! command -v fastboot > /dev/null; then
    echo >&2 "fastboot not found, aborting."
    exit 1
fi
```

```powershell
if (-Not (Get-Command "fastboot" -ErrorAction SilentlyContinue)) { 
    Write-Error "fastboot not found, aborting."
    Exit 1
}
```
