### ISSUE TITLE
Pixel 3 - Device Randomly Rebooting Since RP1A.201005.004.2020.10.23.04

### ISSUE THREAD

**Issue by Algebro7** [GrapheneOS/os_issue_tracker#378]
I'm not sure if this is a coincidence, but my Pixel 3 has been suddenly rebooting without any kind of warning several times a day since I installed this update. There is no consistent action I'm performing or app I'm using when it happens--it will just freeze for a second, and then reboot. It also happens when the phone is idle in my pocket or charging overnight.

Let me know if there's any particular log or other information I can provide that would help troubleshoot.

**Comment by thestinger** [comment]
Could be a coincidence but we did add back all the SELinux hardening so it could be caused by that. I don't think anything else could have caused it.

When you say rebooting, do you mean the whole device restarting including going through the verified boot notification about loading another OS again? Or is it only the System UI that restarts?

**Comment by Algebro7** [comment]
It goes back to the "Your device is booting an alternative operating system" warning and I have to unlock it with my password for it to finish starting up, so it's definitely a whole device restart.

**Comment by thestinger** [comment]
It's probably difficult to get any logs then without a userdebug build and/or debug cable, etc. unfortunately.

**Comment by Algebro7** [comment]
That's what I was afraid of. I have a test device I can flash a userdebug build on but I don't have a debug cable. What would the process be for catching the appropriate logs on a system crash?

**Comment by thestinger** [comment]
You should keep an eye on whether this happens with our November Android update release that's going to be pushed out soon. It might be that the issue is resolved upstream. If not, we can try looking into it further.

**Comment by thestinger** [comment]
Please test on the November release that's in the Beta channel right now.

**Comment by thestinger** [comment]
This is now in the stable channel.

**Comment by Algebro7** [comment]
I'm running the latest stable and haven't had any crashes in several days, so it seems to have worked itself out.
