### ISSUE TITLE
Create an App to edit the host file

### ISSUE THREAD

**Issue by cenapatop** [GrapheneOS/os_issue_tracker#382]
I want to edit the host file.

To route some Ip's to another Ip without using a VPN app and to Block adware too

But I dont want to root my device like in that way -> https://www.androidsage.com/2018/06/12/hosts-txt-providers-list-for-adblockers-on-android-phones/

Some configuration should be allowed over an special app.

**Comment by beerisgood** [comment]
You can use NextDNS (available in settings) for that.

**Comment by thestinger** [comment]
In the future, please check the existing issues before filing a potential duplicate: https://github.com/GrapheneOS/os_issue_tracker/issues/184.

> I want to edit the host file.

There is no dynamic hosts file. As an implementation detail, there's an immutable hosts file in the system image. The system image is read-only and verified by verified boot.

A VPN service app can provide a local DNS server without intercepting any traffic. It's also possible to configure a custom DNS-over-TLS server. An explicitly configured DNS-over-TLS server must have a valid certificate, so you need to use a VPN service app to use a local DNS server.

> root my device

That would not be GrapheneOS anymore and doesn't change the fact that there isn't a dynamic hosts file for you to edit.
