### ISSUE TITLE
[Feature] Better boot verification with sim card

### ISSUE THREAD

**Issue by cenapatop** [GrapheneOS/os_issue_tracker#383]
My idea is that the bootloader and other changeable areas will saved on the sim. When you enter the sim code, grapheneos reads the sha256 out, and checkit.

The netzwork should be disabled till the user is sim unlocked

**Comment by thestinger** [comment]
I don't see how this could improve security. I recommend reading about verified boot and attestation.

**Comment by thestinger** [comment]
The firmware including the bootloader is verified from the immutable root of trust. It is possible for the firmware rollback version to be increased by the vendor to prevent downgrades if they fix a verified boot security issue. The bootloader verifies the OS either with the hard-wired OEM key or if it supports alternative OSes, the configured Android Verified Boot key. The Android Verified Boot key can only be set in fastboot mode and is not something the OS could overwrite. There's also a rollback index for the OS. On a Pixel, the bootloader lock state, verified boot key and rollback index are stored on the Titan M along with additional enforcement via SoC security features.

**Comment by thestinger** [comment]
By the time the UI is available to unlock a SIM card, the OS is already verified and loaded. What is there for the OS to verify with state on the SIM card at that point? I don't understand what the use case could possibly be for it. Assuming that data can be stored on it is also making a major assumption, and it cannot be assumed that a SIM is being used and is going to be present on every boot. In general, it does not seem like a useful proposal or one that is workable. If you want to request features you need to provide more details on what would be provided by the feature. No threat model means the issue will just be closed. We don't implement privacy and security theater without an actual purpose. There are plenty of useful features to implement and we aren't interested in doing theater for marketing like many companies selling phones including the former sponsor of this project.
