### ISSUE TITLE
Camera app not able to take more than one picture on the Pixel 4a due to autofocus bug

### ISSUE THREAD

**Issue by PPmzp4** [GrapheneOS/os_issue_tracker#385]
On pixel 4a build RP1A.201105.002.2020.11.05.18, the phone's camera app is not able to take more than one picture. 
After the first shoot, when I press the white camera icon, I've got the picture sound but this one is never saved and the icon stays grey. To bypass the issue I have to exit the application and come back to it. Then I can take another one first shoot picture.  

Appp permissions are set as the following:
- Sensor -> Allow
- Microphone -> Allow Only While Using The App
- Camera -> Allow Only While Using The App
- Files and media -> Allow all

Please, let me now if you need other information to investigate on this issue.

**Comment by thestinger** [comment]
Can't replicate this issue.

**Comment by PPmzp4** [comment]
I found an additional detail. The bug occurs when HDR is enabled. But does not when HDR is disabled.

**Comment by PPmzp4** [comment]
After further tests, I finally found out that the bug is related to the autofocus. When you take a picture and the autofocus is not "stabilized" yet, you can reproduce the bug. For instance like shooting a very close object.

**Comment by anupritaisno1** [comment]
Seems like intended behavior the way it is described

**Comment by thestinger** [comment]
It's not intended.

**Comment by mrxx0** [comment]
I tested the latest AOSP build for the 4a with https://flash.android.com/ and the camera app has the exact same behavior, It's not related to GrapheneOS.

**Comment by thestinger** [comment]
Please test on the 2020.12.08.08 release.

**Comment by mrxx0** [comment]
> Please test on the 2020.12.08.08 release.

Tested on 2020.12.08.08 and it is the same. Still not working.

**Comment by mrxx0** [comment]
Tested on 2021.01.05.03 and it is the same. Still not working.

**Comment by mrxx0** [comment]
2021.01.23.03 seems to fixe the issue, @PPmzp4 can you confirm ?

**Comment by PPmzp4** [comment]
Hi @mrxx0 and @thestinger,

First of all, thank you for tracking this bug. 

Unfortunately, the issue still persists on 2021.02.07.17 release, with and without HDR  :\.

**Comment by thestinger** [comment]
Unable to replicate this on 2021.03.02.10.
