### ISSUE TITLE
Unable to play audio to AirPods via Bluetooth

### ISSUE THREAD

**Issue by VSfz3kkDwtjm4LAD2R24** [GrapheneOS/os_issue_tracker#386]
Hi, I'm using a Pixel 4 XL on RP1A.201105.002.2020.11.05.18. It seems like the system won't stream audio to my AirPods Pro. I tried to re-pair and re-start the phone but none fixed the issue. If I recall correctly, I used to be able to play audio on GrapheneOS based on Android 10.

I also have a Bluetooth speaker and another pair of headphones and they work just fine when paired with my Pixel 4 XL. AirPods work without issues on stock Android 11 on my Pixel 3a and Apple devices.

**Comment by thestinger** [comment]
Looks similar to https://github.com/GrapheneOS/os_issue_tracker/issues/371.

**Comment by VSfz3kkDwtjm4LAD2R24** [comment]
Thanks for the reply. However, no matter how I try to switch output between devices, it's impossible to hear anything on my AirPods.

**Comment by thestinger** [comment]
Please test on the 2020.12.08.08 release.

**Comment by thestinger** [comment]
Please test on the 2020.12.08.08 release.

**Comment by VSfz3kkDwtjm4LAD2R24** [comment]
It's now working properly. Thank you for the help!
