### ISSUE TITLE
Native Chinese keyboard: pinyin, handwriting

### ISSUE THREAD

**Issue by gitbq** [GrapheneOS/os_issue_tracker#387]
Living graphene os so far. Thanks for all the work on this amazing project!!

One thing difficult to track down is any kind of open source Chinese keyboard. This is one area where android in general falls short. Very few Chinese keyboards are easy to use. The only one that seems to work any good when using multiple languages is the Google keyboard.

Is there any chance of including a Chinese keyboard from the the aosp in graphene os?

**Comment by thestinger** [comment]
AOSP doesn't include a standard Chinese keyboard anymore. It has legacy repositories for it that are no longer used. The only option would be including a third party open source keyboard, and it wouldn't be any better bundled with the OS. I don't think we can do anything about this. At most you could request that we include an existing open source keyboard to have support for this out-of-the-box, but you could just install it yourself with no loss of functionality.

**Comment by thestinger** [comment]
https://android.googlesource.com/platform/packages/inputmethods/PinyinIME/ hasn't been developed for a long time.

https://android.googlesource.com/platform/packages/inputmethods/OpenWnn/ was the Japanese input method and was abandoned and removed from AOSP more recently.

LatinIME is no longer actively developed either but is still included in AOSP and gets some bug fixes and minor improvements since AOSP needs a functional and secure keyboard.

**Comment by thestinger** [comment]
The user-facing apps in AOSP are sample apps that are intended to be replaced by forks of the OS. It isn't a place to get these kinds of apps, but rather the apps from there need to be gradually replaced. We need to replace Calendar, Gallery, Music and other apps.

Some of them like Contacts, Dialer, Messaging, DeskClock, etc. are still actively developed and don't need to be replaced.

If an app isn't included already, then it's very unlikely it's actively developed and still useful at all.

**Comment by gitbq** [comment]
No worries. Thanks for the clarification.
As far as Chinese pinyin input goes there are very few if any open source keyboards. 
I have installed "google pinyin input" via the Aurora store and disabled the network access. From a safety perspective is this enough to use this keyboard with relative peace of mind?
