### ISSUE TITLE
Restrict Clipboard Access

### ISSUE THREAD

**Issue by 2br-2b** [GrapheneOS/os_issue_tracker#388]
It would be nice if there were a permission for accessing the clipboard. In iOS, the phone notifys you when an app accesses the clipboard; we could make it so that the app just gets an empty string or Null if it doesn't have access.

This is important because sometimes, people copy sensitive data (like passwords and the like), and giving an app access to this could end up being a security vulnerability and even potentially lealing users' location ([source](https://www.mysk.blog/2020/02/24/precise-location-information-leaking-through-system-pasteboard/) , though for ios). Just look at all the iOS apps caught accessing users' clipboards without permission listed at https://www.techradar.com/news/its-not-just-tiktok-another-53-ios-apps-will-snatch-your-clipboard-data

Maybe either in addition to/instead of having this, we could also add a notification (like in iOS).

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/os_issue_tracker/issues/347 is already filed in the tracker.

Clipboard access is already restricted to the focused app and selected keyboard. Disabling clipboard access for apps outright with a toggle is not a usable or good design. It's not the approach that we intend to take. Please read the existing issue filed on the tracker. Permission toggles are a last resort when there are not better approaches providing case-by-case consent and user control over data.

**Comment by thestinger** [comment]
I don't see a good reason to add a notification. It doesn't improve privacy and doesn't provide a user with a way to do something about it. It would be a waste of our resources.

**Comment by 2br-2b** [comment]
I thought I had already searched and not found anything like that. I'll add to the current issue. Thanks!
