### ISSUE TITLE
System updater still checks for updates when VPN set to always on but no network available

### ISSUE THREAD

**Issue by bossmann47** [GrapheneOS/os_issue_tracker#3921]
When having a VPN set to always on but no network connection, the system updater still checks for new updates and fails, throwing the error in the notification.

**Comment by ignoramous** [comment]
> [https://developer.android.com/reference/android/net/VpnService#setUnderlyingNetworks(android.net.Network[])](https://developer.android.com/reference/android/net/VpnService#setUnderlyingNetworks(android.net.Network%5B%5D)).

Rethink does use the `VpnService#setUnderlyingNetwork` API (when *Configure* -> *Network* -> *Use all available networks* is turned ON), and in our tests, even when Rethink sets an empty array `[]` to it, no network status really changes for tunneled apps in Android 10+. On an Android 8 device, however we noticed that other tunneled apps correctly report a network loss. 

https://github.com/celzero/rethink-app/blob/66302dfd08022f7e263b71c9541906251a2d3f01/app/src/main/java/com/celzero/bravedns/service/BraveVPNService.kt#L1024

Unsure what's up, really. I wouldn't be surprised if AOSP has progressively *changed* the way this API has worked.

**Comment by Frmd-git** [comment]
Is this an upstream issue that needs to be tackled by Google?

**Comment by ignoramous** [comment]
> Is this an upstream issue that needs to be tackled by Google?

I'd say so, but I don't have the time to build a "minimally reproducible app" to demonstrate this. In our experiments, the changes in behaviour wrt `setUnderlyingNetworks` is pretty stark across Android versions; and in the last Android version that we checked (Android 13 on a OnePlus device), `setUnderlyingNetworks(emptyArray)` did not send any "no network available" signal to installed apps, like it should have (or like I expect it to).

If you're technical enough, you can build Rethink with [`FAIL_OPEN_ON_NO_NETWORK`](https://github.com/celzero/rethink-app/blob/8526a32635d981fc6580b1472b7e8dcebbf5eae6/app/src/main/java/com/celzero/bravedns/service/BraveVPNService.kt#L173) to `false` and test it on Graphene. May be, we should make it in to a user-configurable switch.

**Comment by ignoramous** [comment]
> If you're technical enough, you can build Rethink with FAIL_OPEN_ON_NO_NETWORK to false and test it on Graphene. May be, we should make it in to a user-configurable switch.

Prompted by thestringer, in the upcoming Rethink DNS + Firewall version `v055o`, we're *turning OFF* "fail open on no network" by default (which should `setUnderlyingNetworks([])`, when there's no network available with default gateway).

**Comment by mattcheau** [comment]
@ignoramous What effect will that have (or do you expect it to have) in general on outbound network data/traffic/packets?

**Comment by ignoramous** [comment]
> What effect will do you expect it to have on outbound network data/traffic/packets?

No packets are sent to the `tun` device (that Rethink holds & reads/writes packets from/to) with `setUnderlyingNetworks([])`, but Chrome & others think DNS is down (not that the device itself is *offline*).

Interestingly, when we add an "obsolete" network to `setUnderlyingNetworks()`, Chrome & WhatsApp both report device being *offline*.

**Comment by ignoramous** [comment]
Hi Daniel,

> Perhaps it's missing [https://developer.android.com/reference/android/net/VpnService#setUnderlyingNetworks(android.net.Network[])](https://developer.android.com/reference/android/net/VpnService#setUnderlyingNetworks(android.net.Network%5B%5D)).

This API is unuseable when "Block connections without VPN" (Lockdown) is turned ON. After Rethink integrated using this API, users (ones using GrapheneOS specifically where VPNs are *Lockdown* by default) have been reporting all sorts of connectivity issues.

We have at least 1 way to consistently reproduce connectivity loss in [`v055o`](https://github.com/celzero/rethink-app/releases/v0.5.5o):

(instructions copied from https://github.com/celzero/firestack/issues/171#issuecomment-3172927576)
1. Make sure "Block connections without VPN" for Rethink is turned ON (from Android's VPN settings page).
2. Turn OFF "Do not stall on network loss" (this is the default) in Rethink (from *Configure* -> *Network*).
3. Check if there's internet connectivity (for example, by loading an uncached website in Vanadium).
4. Turn OFF all data networks (like WiFi and Mobile), if turned ON.
5. Wait 5s. Try to check if there's internet connectivity (there shouldn't be as there's no network available).
6. Turn ON WiFi and/or Mobile data.
7. Wait 5s. Observe there's no internet connectivity still.
8. Turn OFF "Do not stall on network loss" in Rethink (as in step 2).
9. Wait 5s. See that the apps now successfully connect.

What Rethink does differently when "Do not stall on network loss" is turned OFF is to:
1. Set an empty array when no validated Internet-routing networks exist.
2. Set an ordered array of Network objects when multiple validated Internet-routing networks (WiFi, Mobile, USB, etc) exist.

**Comment by ignoramous** [comment]
Hi Daniel,

An update: We got past the stalling behaviour (on all our test devices running Android 12 and above, with VPN in Lockdown), by calling [`VpnService.setUnderlyingNetworks`](https://developer.android.com/reference/android/net/VpnService#setUnderlyingNetworks(android.net.Network%5B%5D)) on ALL [LinkProperities](https://developer.android.com/reference/android/net/ConnectivityManager.NetworkCallback#onLinkPropertiesChanged(android.net.Network,%20android.net.LinkProperties)) and [NetworkCapability](https://developer.android.com/reference/android/net/ConnectivityManager.NetworkCallback#onCapabilitiesChanged(android.net.Network,%20android.net.NetworkCapabilities)) changes (previously, we only changed underlay network if [our app's built-in per-network connectivity checks](https://github.com/celzero/rethink-app/blob/9435e29c716d8f0f83040ec20042d55530452b0a/app/src/main/java/com/celzero/bravedns/service/ConnectionMonitor.kt#L1102) detected any existing network losses / new network availability). Setting underlay networks as aggressively isn't required for when VPN is *not* Lockdown, per our tests (that is, by setting underlay networks only on network availability / loss was enough).

**Comment by mattcheau** [comment]
> Setting underlay networks as aggressively isn't required for when VPN is _not_ Lockdown, per our tests (that is, by setting underlay networks only on network availability / loss was enough).

Makes sense.

Are GOS devices included in "all our test devices running Android 12 and above"? (I.e., should this issue now be fully resolved?)

And did your testing drill down into or reveal any specific [LinkProperties](https://developer.android.com/reference/android/net/LinkProperties) or [NetworkCapabilities](https://developer.android.com/reference/android/net/NetworkCapabilities) changes that were contributing to network 'stalling' or were otherwise problematic?
