### ISSUE TITLE
Disable camera/microphone access after timeout

### ISSUE THREAD

**Issue by monsieuremre** [GrapheneOS/os_issue_tracker#3931]
GrapheneOS gives the option to automatically disable bluetooth and wifi after a timeout.

It also gives the option to universally disable camera and/or microphone access with a toggle. This is done with relative ease by the user, manually.

Intuitively, it should possible to combine these two features to have a timeout to disable camera or microphone access. Access to these is through the system and the system knows the last time of access. If there has been no access for a certain time period, the system could toggle off access. This would be just like the bluetooth or wifi implementation.

I cannot think of any technical reason that would block this feature.

I would see value in having this option.

**Comment by k0n5n** [comment]
I would also support this feature, for some apps I allow camera/microphone access while using them, and when i open them again a few minutes later they immediately access the camera and/or microphone unless I manually disable it globally after using the app
