### ISSUE TITLE
SetupWizard/Seedvault - Selecting the Nextcloud restore option crashes SetupWizard

### ISSUE THREAD

**Issue by Bungeetaco** [GrapheneOS/os_issue_tracker#396]
When going through the SetupWizard on a new install of GrapheneOS and opting to restore data from a previous installation (Seedvault), 3 options are presented: Local Storage, USB & Nextcloud.

1. The Local Storage option in this case seems like it cannot be used, as it requires the .SeedVaultAndroidBackup folder to be copied back to the device, and there is no option to enable USB file transfer while setup is on-going.

2. The USB storage option requires an OTP plug, and it's unclear what format the device must be formatted as in order to be recognized during this step. (I tried copying the .SeedVaultAndroidBackup to a FAT32 SD card, which wasn't recognized)

3. The Nextcloud option requires that the Nextcloud app be installed. As a vanilla install of GrapheneOS does not have an appstore like Aurora of F-Droid, it seems like it is unable to download and install the app. This in turn causes the SetupWizard to crash, requiring a device reboot to start the setup over. This seems to imply that this option is currently broken.

**Comment by thestinger** [comment]
> When going through the SetupWizard on a new install of GrapheneOS and opting to restore data from a previous installation (Seedvault), 3 options are presented: Local Storage, USB & Nextcloud.

You should file these as issues for Seedvault. It's not developed as part of GrapheneOS.

> The Local Storage option in this case seems like it cannot be used, as it requires the .SeedVaultAndroidBackup folder to be copied back to the device, and there is no option to enable USB file transfer while setup is on-going.

There may end up being support for restoring at any time rather than only via the Setup Wizard which is probably why it's designed this way. You can manually launch the restore activity via `adb shell` using `am` for the time being.

> The USB storage option requires an OTP plug, and it's unclear what format the device must be formatted as in order to be recognized during this step. (I tried copying the .SeedVaultAndroidBackup to a FAT32 SD card, which wasn't recognized)

This should work fine. You should figure out why it's not working. FAT32 USB OTG devices are supported. The phones come with an adapter for this.

> The Nextcloud option requires that the Nextcloud app be installed. As a vanilla install of GrapheneOS does not have an appstore like Aurora of F-Droid, it seems like it is unable to download and install the app. This in turn causes the SetupWizard to crash, requiring a device reboot to start the setup over. This seems to imply that this option is currently broken.

You could transfer it from there to a flash drive in order to restore though.

**Comment by Bungeetaco** [comment]
Thank you for the quick response Daniel, I was able to restore my backup using the activity launcher as suggested.
Appreciate all the hard work!
