### ISSUE TITLE
How do I type in Japanese?

### ISSUE THREAD

**Issue by ToshiKawata** [GrapheneOS/os_issue_tracker#399]
Dear GrapheneOS issue tracker community

Hi I just installed GrapheneOS and trying to type in Japanese and can someone advise me how I can do this ?

Thanks for your time.

Sincerely
Toshi

**Comment by thestinger** [comment]
You need to install a keyboard with support for it. There isn't one included in the Android Open Source Project.

You should ask on the #grapheneos Matrix / IRC channel instead of here.

**Comment by ToshiKawata** [comment]
So is there any way to type in Japanese with GrapheneOS?

Toshi

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
月曜日, 11月 30, 2020 9:01 午前に、Daniel Micay <notifications@github.com>は書きました：

**Comment by thestinger** [comment]
Yes, install a keyboard with Japanese input support.

**Comment by ToshiKawata** [comment]
Thank you for your reply.

Could you please advise me how I can install a keyboard ?

**Comment by thestinger** [comment]
You need to get support on the IRC / Matrix channel. This isn't a support platform.

**Comment by ToshiKawata** [comment]
Sorry for bothering you.
Is Matrix or IRC on GitHub ?

**Comment by thestinger** [comment]
See https://grapheneos.org/contact.

**Comment by thestinger** [comment]
See https://grapheneos.org/contact#community.

**Comment by ToshiKawata** [comment]
I managed to install Japanese keyboard :)
Thank you for developing GrapheneOS !

Toshi

**Comment by tripu** [comment]
@ToshiKawata: do you mind sharing your solution?

**Comment by tripu** [comment]
> Install one of the available Japanese language keyboards for Android.

@thestinger: I thought of that. But is there any that is free / open source / private / safe to use?

**Comment by tripu** [comment]
Mozc on F-Droid is not compatible with my (brand new) device, and it was last updated &ldquo;five years ago&rdquo;. I can't find it on Aurora (ie, Google Play).

**Comment by FintasticMan** [comment]
I've just tried using Gboard for typing in Japanese, but while I can type hiragana, it doesn't show any suggestions and a toast pops up saying (in Japanese) that the Japanese language pack is not installed. I've tried searching the web for ways to fix this but to no avail. I feel like it could be due to the Google Play sandbox, as it does work fine on a stock Pixel. Any suggestions?

**Comment by FintasticMan** [comment]
There doesn't seem to be any way to install language packs. For now, I've switched to using SwiftKey (without the network permission), which does work correctly.
