### ISSUE TITLE
Suzy-Q debug cable

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os_issue_tracker#4]

**Comment by thestinger** [comment]
This is now available from a retailer:

https://www.sparkfun.com/products/14746

No longer going to be having custom cables made anymore.

**Comment by thestinger** [comment]
The retail ones don't work with Pixel phones.

**Comment by thestinger** [comment]
This is going to be resolved.

**Comment by Kokokokoka** [comment]
If there will be such a cable, I want to know where one can buy it.

**Comment by thestinger** [comment]
There aren't currently plans to make it available for purchase, but maybe that could happen later.
