### ISSUE TITLE
replace boot animation

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os_issue_tracker#40]

**Comment by thestinger** [comment]
This should be implemented now.

**Comment by harut420** [comment]
Hello, how to change bootanimation ? i was wondering if there is a simple zip file to changes, but i do not find it . any suggestions ?

**Comment by thestinger** [comment]
There's a bootanimation zip, but there is none by default. The default is not an actual boot animation with frames but rather a hard-wired bit of code to render text with a glossy animation.

**Comment by LuckyArthas** [comment]
I want change GrapheneOS bootloader animation.
Please let me know how to do.

**Comment by thestinger** [comment]
It's not configurable. It's part of the OS. It's shown long before data is mounted.

**Comment by lichi0223** [comment]
You can simply change the png file under frameworks/base/core/res/assets/images.
If no zip files are found under expected locations, bootanimation would use files android-logo-mask.png & android-logo-shine.png and apply some animation effect.
