### ISSUE TITLE
Can not make a cellular call

### ISSUE THREAD

**Issue by ToshiKawata** [GrapheneOS/os_issue_tracker#401]
Dear GrapheneOS team

I an writing to ask for your advice to enable cellular call. 
My default call app does not work as it immediately finishes call when I make a call,  nor accept any call.

SMS message and calls with signal is available.

I would appreciate it if I could hear your advice to fix this problem.

Sincerely

Toshi

**Comment by dznsm** [comment]
Do you have your preferred network set to 4G only?
Unfortunately VoLTE (Voice over LTE) is not configured for all carriers and this is the behaviour you will see if that is the case for your carrier.
Unfortunately it can be a bit complex getting all the necessary configuration correctly set up. You can see what is involved in this issue https://github.com/GrapheneOS/os_issue_tracker/issues/153

**Comment by ToshiKawata** [comment]
My SIM card is configured to use LTE and having read the link u posted, I need to set APN manually to configure voice call ?

**Comment by thestinger** [comment]
You can't use the LTE only mode if you don't have VoLTE support.

**Comment by thestinger** [comment]
Please use the IRC / Matrix channel for support and file an issue here if you can't resolve the problem through configuration changes.
