### ISSUE TITLE
Unable to install GrapheneOS on 4a due to a newer bootloader

### ISSUE THREAD

**Issue by Seferi** [GrapheneOS/os_issue_tracker#402]
Hi,

I have a brand new pixel 4a. I installed all the system updates on stock os before going for graphene as recommended on the GrapheneOS install section. I ran flash-all.sh but it failed due to bootloader being newer (5.0.3) then the recommended version (5.0.2). Should I just wait until an update arrives and then flash again? I appreciate if you could point me to the right direction. Thanks.

**Comment by thestinger** [comment]
That shouldn't be a problem unless the flashing process is failing to flash the firmware.

Please get support on the IRC / Matrix channel:

https://grapheneos.org/contact#community

The issue tracker isn't used to provide support, and this isn't a bug report or feature request.
