### ISSUE TITLE
Dialer (4a): Obey Dark-Design

### ISSUE THREAD

**Issue by fred0r** [GrapheneOS/os_issue_tracker#403]
i'm currently using RP1A.201105.002.2020.11.27.15 on a Pixel 4a.
it would be nice if the Dialer would also have a Dark Background, when the 'Dark Design' is selected.
There seems no Option to conf the Dialer to another Color.

**Comment by thestinger** [comment]
We're not going to develop this as part of GrapheneOS. It should be done in AOSP.
