### ISSUE TITLE
Switching back to a running profile causes the screen contents to be exposed before unlock

### ISSUE THREAD

**Issue by Opening-Button-8988** [GrapheneOS/os_issue_tracker#4044]
Occasionally when I switch profiles, and back to the original profile that remains running in the background, the contents of the screen, such as the last used app or the home screen are exposed before unlocking that profile. I had biometrics enabled for both profiles.

Pixel 7, Build 2024091900.

**Comment by WaleedMortaja** [comment]
It is **not** Pixel 7 specific. Pixel 6a (with GOS) is affected as well.

**Comment by WaleedMortaja** [comment]
@Opening-Button-8988 Can you provide the link for the upstream issue or its duplicate?
