### ISSUE TITLE
Increase SeedVault backup timeout to 10 minutes 

### ISSUE THREAD

**Issue by vbooka1** [GrapheneOS/os_issue_tracker#4054]
Hello, please change the default timeout for creating a backup of a single app from 5 minutes to 10.
Maybe add an option to change the default timeout to an arbitrary value in Expert Settings or via `adb`?

For example, this app weights 8+ gigabytes and its data consists of thousands of files, so a backup attempt fails with a timeout:

```
09-23 22:33:33.345  1551 24206 D BackupManagerService: Calling doFullBackup() on com.divessi.ssi
...
09-23 22:38:33.377  1551  3591 D BackupManagerService: Timeout message received for token=641a14ad
09-23 22:38:33.377  1551  3591 V LifecycleOperationStorage: [UserID:0] Cancel: token=641a14ad
09-23 22:38:33.377  1551  3591 W PFTBT   : Full backup cancel of com.divessi.ssi
```
It takes 20 minutes to make a backup via `adb`, but I think 10 minutes will be fine for the majority of users because most of them will not download this much data.

More info might be here: https://github.com/seedvault-app/seedvault/issues/147

**Comment by Victor239** [comment]
This looks like [it's been resolved](https://grapheneos.org/releases#2024102400).
