### ISSUE TITLE
Make "time.grapheneos.org" configurable

### ISSUE THREAD

**Issue by eht16** [GrapheneOS/os_issue_tracker#407]
I appreciate much using a different time update service than the standard Android one.

It would be even better to have the default time server `time.grapheneos.org` being configurable by the user so one can use even independent of grapheneos.org.

Changing the DNS target doesn't work because of TLS verification (this is good).

I don't necessarily request a GUI option to configure it, something like `settings put global time_server` or so would be fully sufficient.

**Comment by thestinger** [comment]
It's configurable via the resources already, which you can adjust via an overlay for your builds. If you aren't making your own builds with your own signing keys, update server and attestation app / server, then you depend on our infrastructure. I don't see a reason to treat the time server differently than the things inherently depending on specific infrastructure.

This secure network time update implementation is specific to GrapheneOS. The protocol may be improved in future versions of the OS by making a more specialized API than using the low precision date header. The server has to remain backwards compatible with older versions of the OS but not vice versa. If you set this to another server, it's going to break when we improve the protocol. We're not going to keep backwards compatibility with servers implementing an older version of the protocol. It would needlessly complicate the implementation and we don't have the resources to spare supporting legacy versions of protocols. This is another reason that this kind of change has to be made as part of making your own builds. You can add support for a new protocol version to the server before you push out the release taking advantage of it.

**Comment by thestinger** [comment]
In general, we're also not interested in settings only available to developers. The only reason to add those is something that's useful for OS or app development. ADB access is for developers, not as a way to expose advanced features to power users. Using it in production isn't recommended and we can't officially support it beyond development use. Maintaining a feature that's only available to developers just doesn't make sense for us.

You would need to come up with a clear reason that this would be useful *despite* the inherent need to make your own builds with your own keys to replace the other infrastructure. It doesn't really seem useful to treat this as a special case.

Similarly, we're not going to offer user-facing configuration for arbitrary connectivity check servers, especially with all of the caveats involved in making it work properly. There are 4 separate settings that need to be set properly, 1 to an HTTPS URL and 3 of them to different HTTP URLs and those need to be on a domain without HSTS. Every normal domain should have HSTS to that implies registering a domain *specifically* to provide the connectivity check service. This is not the kind of thing that we can verify based on user input. Sure, it's possible to configure these as a developer via ADB, but we strongly recommend against messing with settings that way and it is not something that the code needs to be designed to handle. Invalid configuration for settings via ADB is a self-inflicted issue via developer tools. The only values considered valid are the ones we offer in the Settings app, and anything else will be interpreted as it being set to the default. It's unrealistic to support arbitrary configuration of under the hood settings via developer tools.
