### ISSUE TITLE
Require user input to enable "Wi-Fi control" permission

### ISSUE THREAD

**Issue by ahfuckme** [GrapheneOS/os_issue_tracker#409]
I was surprised to see that the "Wi-Fi control" permission can be enabled by apps without any user input, and it often is. I only just discovered that, on my device, Signal, WhatsApp, Instagram, and even the Camera app all had this turned on. The permission states (emphasis mine):

> Allow this app to turn Wi-Fi on or off, **scan and connect to Wi-Fi networks**, add or remove networks, or start a local-only hotspot.

Given the fact that there are [global maps of all Wi-Fi networks](https://nitter.net/Snowden/status/1175431946958233600#m), it would seem prudent to request user input before enabling this permission, as it could give apps a rough estimate of your geolocation by scanning and analyzing the networks in your area, even if location services are disabled.

The management of this permission can be reached by navigating the settings as follows:
```
Apps and notifications > Advanced > Special app access > Wi-Fi control
```

**Comment by thestinger** [comment]
This permission doesn't work the way you seem to think it does. It requires user consent to do these things.

> Given the fact that there are global maps of all Wi-Fi networks, it would seem prudent to request user input before enabling this permission, as it could give apps a rough estimate of your geolocation by scanning and analyzing the networks in your area, even if location services are disabled.

No, it cannot be used to do that. Please read the documentation on the Location permission.
