### ISSUE TITLE
Bluetooth auto turn off

### ISSUE THREAD

**Issue by Exilion666** [GrapheneOS/os_issue_tracker#411]
I found a great feature on CalyxOS in bluetooth settings there are options to turn off bluetooth after sertain time if not connected. For such privacy/security focused OS like GrapheneOS it would be another useful feature

**Comment by blobless** [comment]
I suggest using Greentooth until this feature is ported: https://gitlab.com/nbergman/greentooth

**Comment by Exilion666** [comment]
Greentooth is good, but sometimes it does not work, maybe it goes to deep sleep, even with battery optimisation disabled, it would be great to apply it as system feature

**Comment by Exilion666** [comment]
Realisation in CalyxOS
https://gitlab.com/CalyxOS/calyxos/-/issues/124

**Comment by beerisgood** [comment]
Auto disabling bluetooth would stop Covid-19 warn app.

**Comment by Exilion666** [comment]
If you need BT stay on, you can just NOT turn this feature on

**Comment by beerisgood** [comment]
> Greentooth is good, but sometimes it does not work, maybe it goes to deep sleep, even with battery optimisation disabled, it would be great to apply it as system feature

You can try https://f-droid.org/repo/com.mystro256.autooffbluetooth

**Comment by Exilion666** [comment]
Feature is allready realised, but following bug occurs:
When screen is on/phone awake bluetooth turn off feature works as supposed. If screen is off for longer time and bluetooth is disconnected, bluetooth stays on.
Could some daemons go in deep sleep?
Tested in calyx this problem is not present

**Comment by thestinger** [comment]
Calyx doesn't enable the modern power management.

**Comment by thestinger** [comment]
If the feature is flawed and there isn't work to address it, then I'll probably end up removing it. It likely wasn't written to properly handle the modern power management system on Android. CalyxOS works like Android 5 and earlier. If the code was only written to work in that environment, then it makes sense it would have issues elsewhere.

I don't know what's wrong with it. Someone will have to work on that, or I'll remove it.

**Comment by thestinger** [comment]
@Exilion666 Filed https://github.com/GrapheneOS/os_issue_tracker/issues/528 as a new issue about this. So far, the person working on this has been unable to reproduce the problem that you're reporting. You'll need to provide clear instructions on how to reproduce the problem and please make sure it's not a misunderstanding or problem on your end.

**Comment by thestinger** [comment]
Multiple people have been unable to replicate the problem. Are you running unmodified GrapheneOS?

**Comment by thestinger** [comment]
Multiple people have been unable to replicate the problem. Are you running unmodified GrapheneOS? Please give more information in the new issue filed about it.
