### ISSUE TITLE
Adding Fairphone 3/3+ support

### ISSUE THREAD

**Issue by lescuer97** [GrapheneOS/os_issue_tracker#414]
Hi!, i was wondering if there could be a discussion about adding the Fairphone for supported devices on this Os, i think that with it's awesome reparability score and for what i seen lockable again bootloader (link below) it would be a good match for this project.

https://support.fairphone.com/hc/en-us/articles/360048646311-Manage-the-bootloader-of-your-FP3-FP3-

Best Wishes and merry christmas!.

**Comment by beerisgood** [comment]
Weak secured devices aren't supported.
https://grapheneos.org/faq#device-support

A re-locked Bootloader is only one from many factors.

**Comment by louipc** [comment]
Thanks for your interest in GrapheneOS.
However, support for new devices is a very low priority, and preference would be given to new Pixel devices with extensive security features in hardware and up to date Android/AOSP support. Unfortunately it seems that Fairphone does not even offer Android 11 yet, which means extensive work which makes no sense for GrapheneOS. I'd encourage you to pressure Fairphone to bring Android 11 support at a mere minimum.
Good luck.

**Comment by the-vampiire** [comment]
Now that FP4 has been announced with android 11 is there any interested in bringing graphene to it?

**Comment by thestinger** [comment]
GrapheneOS is based on Android 12 and there won't be releases for Android 11 anymore. The migration of all our features to Android 12 is being finished.

**Comment by daniu-de** [comment]
I'll misuse this to air my anger:
Grapheneos gives us paranoid users the possibility to live without google - great - but it does this forcing us to buy a google device - do you understand that this alone is paradox? However worse in my eyes is that this devices all do not have sdcard slots but rely on "the cloud". Guess what? Paranoid people do not like "the cloud" and love to use huge local storage which is always and everywhere available. That does not make any sense. I bet lots of people care much less about secure boot than about this. Why not give us an OS clearly stating that it does have security flaws but can be used with a chosen device with sdcard slot

Or - finally come up with more news concerning the cooperation with an oem to come up with own hardware. For example it would be pretty important to know if this oem device is supposed to have a sdcard slot or if I could just forget about grapheneos for now

**Comment by r3g-5z** [comment]
This isn't a place for conspiracy talk.
