### ISSUE TITLE
Please, make the instruction better - than you have on your site, if possible.

### ISSUE THREAD

**Issue by overtube** [GrapheneOS/os_issue_tracker#416]
Or make an shell/bash for auto-build to target platforms.
It will help a lot to popularize the distribution.
something like as installation with Proot on Termux, there quickly and without pain. 
D:
I tried to build for x86-64 architecture, but after two attempts to download the code, which took almost 10 hours and ended with errors - I feel rage and pain somewhere in the bottom of my ass. 
slice of a terminal output posted on project issue tracker

**Comment by overtube** [comment]
And I need sorry for this, maybe errors on fetch sources not critical, because sources downloaded & located on work machine, after long fetch and downloading.

**Comment by thestinger** [comment]
The build instructions work properly. I don't know what you expect us to improve. You aren't clear about that. I don't understand why you're talking about Termux.

**Comment by thestinger** [comment]
It looks like you have a poor internet connection and you're trying to fetch the sources for an entire operating system which is quite large. The fetching is done by Git via repo. It's not something we implemented. The servers are the AOSP and GitHub ones, but that's not the issue. Regardless, it's not something that's in scope for the issue tracker here and isn't an issue with our instructions. I'm not really sure what you're trying to do anyway.

**Comment by ypid** [comment]
It is WIP but HashbangOS has build scripts available to build GrapheneOS. Ref https://github.com/hashbang/os/issues/47 for more details.

**Comment by overtube** [comment]
Thank - forgive me, and thanks for the reply, maybe I should have been more careful and yes I have 2.5 Mb/s internet speed.
