### ISSUE TITLE
Hotspot issues in 2024102100

### ISSUE THREAD

**Issue by oppressor1761** [GrapheneOS/os_issue_tracker#4175]
P8P 
The first and the most serious issue is Hotspot sometimes is unusable. Steps:(not 100% reproducible. If not, repeat step 2-3 or let hotspot be on for longer in step 2)
1. Restart
2. Turn on hotspot
3. Turn off hotspot manually. Then there's a error log like #3502
4. Turn on hotspot again. If failed, retry for multiple times.
Actual behaviour: hotspot can not be turned on unless I restart the phone. 

The second issue:hotspot cannot be turned off automatically even there's no other device connecting to it.

**Comment by muhomorr** [comment]
Is this still an issue after 2024102400 update?
