### ISSUE TITLE
Bonito kernel modules

### ISSUE THREAD

**Issue by test-acc-vaccym** [GrapheneOS/os_issue_tracker#418]
CONFIG_MODULES=y
CONFIG_MODULE_UNLOAD=y
CONFIG_MODULE_FORCE_UNLOAD=y - CONFIG_MODVERSIONS=y

these options should be disabled for bonito

**Comment by thestinger** [comment]
cc @anupritaisno1

**Comment by thestinger** [comment]
This is a regression that likely happened as part of the port to Android 11.

**Comment by thestinger** [comment]
This is implemented and appears to be working properly. Can be beta tested with the rest of the release.
