### ISSUE TITLE
USB-3,5" incompatibility issue

### ISSUE THREAD

**Issue by DD8372812** [GrapheneOS/os_issue_tracker#419]
On my Pixel 4 with GrapheneOS 12.12.2020 my USB->3,5" adapter does not work. I bought it with the guarantee that it's compatibe with a Pixel 4. When I plug in the adapter, an Android-System Message appears: "an analogue accessory was found but it is not compatible with the phone" (translated into english).

Should it work with current release? Did I maybe bought an incompatible cable?

**Comment by thestinger** [comment]
Sounds like a low quality quality not following the USB specifications.
