### ISSUE TITLE
switch to 4 level page tables for larger address space

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os_issue_tracker#42]

**Comment by thestinger** [comment]
This mostly worked in an attempt to do it on the Pixel 3 and Pixel 3 XL, but unfortunately caused issues for the video driver, leading to flickering and repeated errors / crashing so it was reverted for the time being:

https://github.com/GrapheneOS/kernel_google_crosshatch/commit/8ee1b0671bde8000716a7033000ab274aba66a3b

**Comment by thestinger** [comment]
This mostly worked in an attempt to do it on the Pixel 3 and Pixel 3 XL, but unfortunately caused issues for the video driver, leading to flickering and repeated errors / crashing so it was reverted for the time being.

**Comment by anupritaisno1** [comment]
Hey can I see your patch for this one?

**Comment by thestinger** [comment]
It's just a configuration option for the kernel (change number of page table levels to 4 and increase the address space size). You can do it via `make nconfig` or manually and then `make config` to make sure it worked.

**Comment by anupritaisno1** [comment]
Thanks I found it

**Comment by thestinger** [comment]
This is implemented.
