### ISSUE TITLE
TracFone sim - data not working

### ISSUE THREAD

**Issue by RiverCub** [GrapheneOS/os_issue_tracker#420]
I'm contacting about a issue I'm having on a pixel 4 XL not connecting for data access using a TracFone SIM card. The network settings page says that it connected to the Verizon network, although I get no data connectivity. The data icon  shows good strength but doesn't have internet access. Although phone and texting  works as expected.

When I initially set up the phone it defaulted to the Global "Preferred Network type," although I have tried it on LTE(recommended) but with no luck. When I contact TracFone support they indicate that they detect a problem with the network and indicate that they have fixed it but the data never starts working.

When I move the SIM card over to a OEM pixel device, it still doesn't work initially but if I text TracFone support with the data issue, they again indicate they detect there is an issue, and indicate that they have corrected the problem and then my data starts working correctly on the OEM device. The stock OEM pixel indicates in the network settings that it is connected to the TracFone network instead of Verizon as was indicated with GrapheneOS on the other pixel.

When I move the SIM card back to the GrapheneOS pixel I again have no data and in networking it says that the device is connected to the data Network on Verizon although I get no actual data connection to the internet.

I've switched back and forth several times repeating the steps above and each time get the same results. Although I am not familiar with what all negotiations go on between the phone and the network it seems that a flag is set at Verizon and they block my data connection. Apparently TracFone support is able to recognize that the flag is set and attempts to reset it with no luck apparently unless it's on the OEM phone. 

Has anyone else had a similar issue with TracFone Sims? Is there anything on my end that I can do to remedy the situation?

RQ1A.201205.008.2020.12.12.03

**Comment by thestinger** [comment]
Can you try resetting the network settings via the Settings app? Maybe try manually configuring the APNs too.

**Comment by RiverCub** [comment]
I've tried switching the preferred network type between LTE and global with no effect on data. Doesn't appear that the network is something that I can set myself in the settings app at least.

Not familiar with manually configuring the APNs. Although I'm certainly willing to try with guidance. Can anyone point me to a reference?

**Comment by RiverCub** [comment]
Whatever is happening it is something that TracFone support is able to detect on the network. I'm wondering if Verizon isn't just blocking either my specific Sim when it's on GrapheneOS. I wasn't having a problem when I was using a Verizon sim initially but that's no longer an option as I close that account. I might have to get a temporary pay as you go Verizon sim and see if that has the same problem. When I initially switch to the TracFone Sim it did work for a day or two before it stopped working. Well actually probably the first time that I did some heavy data access is when it stopped working. Initially it was saying LTE right beside the strength bar but that no longer appears.

**Comment by thestinger** [comment]
The next release of GrapheneOS will have a bunch of extra carrier configuration. This issue might be fixed as part of that.

**Comment by 17netters** [comment]
I had a similar issue last month. I also use a Tracfone (using Verizon sim), and when I ran out of data, (and then re-added more) it didn't reconnect to LTE. I ended up putting the sim in a different phone. I did the same exact thing that RiverCub did (call tracfone, they update apn settings, etc) in my GrapheneOS phone, but no luck. I ended up swapping the SIM in another phone and had Tracfone try again, and then LTE started working again. At that point, I swapped the it back into my grapheneOS (Pixel 3XL), and LTE worked again. At this point in time, mms multimedia messages don't download, but they can be sent.

RiverCub, I also tried going to the phone app and dialing *#*#4636#*#* which brings you to a testing page, and you can click "Phone Information" and it'll give you some details about the network connection. In that page, you can actually change the preferred network type, which actually got it partially working for me a couple months back (changed it to like CDMA/EvDo or something similar, but it put it in roaming mode). Maybe it might help.

currently on RQ1A.210105.003.2021.01.05.03

**Comment by thestinger** [comment]
The next release will have updated APNs and CarrierConfig vendor.xml.

**Comment by thestinger** [comment]
Please check if this works on the latest release.

**Comment by 17netters** [comment]
Can confirm, MMS messages are fully working, as well as the mobile data. In addition, it looks like the Tracfone APN has also updated successfully.
