### ISSUE TITLE
recover default wallpaper lost with build RQ1A.210105.002.2021.01.05.03

### ISSUE THREAD

**Issue by Saroumane** [GrapheneOS/os_issue_tracker#421]
Hello,
I updated today my Pixel 3a to build RQ1A.210105.002.2021.01.05.03
I lost the default wallpaper, background became black. According to what I found about the update, it's intended.
I may be silly but I liked the default wallpaper.
Any way to recover it ? I didn't found it on the net. (Maybe I don't have the right keywords)
Thanks.

**Comment by thestinger** [comment]
https://raw.githubusercontent.com/GrapheneOS/platform_frameworks_base/8398e8261e451358b779514569825ae7a94ef579/core/res/res/drawable-sw600dp-nodpi/default_wallpaper.png is the highest resolution version of it. It's the default AOSP wallpaper for Android Nougat and later. We wanted something better fitting the aesthetic of GrapheneOS and for the time being a black wallpaper is a good fit. Maybe we'll put a dark grey graphene pattern on it or something along those lines. It'll essentially remain a black wallpaper though.

**Comment by beerisgood** [comment]
Maybe this wallpaper can be used?:
https://www.reddit.com/r/GrapheneOS/comments/ka0be4/grapheneos_wallpapers_1080x2340/
