### ISSUE TITLE
Shortcuts disappear in secondary profiles

### ISSUE THREAD

**Issue by Lppsoeht** [GrapheneOS/os_issue_tracker#4222]
Since the #453 fix this issue seems to happen less frequently, but it still happens. I'm only using settings shortcut but I can imagine the same behaviour for every type of shortcut.
Cannot replicate when exactly it does happen, sometimes after a reboot, sometimes after closing the profile, sometimes shortcuts last more.

**Comment by sbucek** [comment]
Can confirm on pixel 8, all shortcuts from Vanadium/Brave browsers and some widget shortcuts are gone.

**Comment by sbucek** [comment]
Correct, only shortcuts and PWAs disappeared, sorry for confusion.

**Comment by AxFaure** [comment]
Hi ! For the record, this issue seems to be related to #3677 in which I mention a way to replicate the bug.
