### ISSUE TITLE
Pixel 4a kernel compilation uses to much memory

### ISSUE THREAD

**Issue by lucaszanella** [GrapheneOS/os_issue_tracker#423]
Forgive me if this is not the right place, but I'm following the build guide for GrapheneOS. 

On building the kernel for the Pixel 4A for release RQ1A.210105.002.2021.01.05.03, I get stuck at `vmlinux.o` and then it consumes all my 16gb of RAM (should be enough) and then crashes:

![Screenshot from 2021-01-15 22-20-21](https://user-images.githubusercontent.com/6632321/104793145-04a0a780-5780-11eb-8ed4-7f903f87e2a3.png)

The only thing different I did was

`./build.sh `

instead of

`./build.sh sunfish`

because `./build.sh sunfish` didn't do nothing, it immediately returns.

**Comment by thestinger** [comment]
That's not enough memory to build the Linux kernel with full LTO. It's enough to build the OS with the prebuilt kernel.
