### ISSUE TITLE
Prevent apps from listing installed apps

### ISSUE THREAD

**Issue by 2br-2b** [GrapheneOS/os_issue_tracker#424]
Right now, any app can view a list of all installed apps. While this functionality is  necessary for apps like Fdroid, not all apps should be able to list your installed apps.

Should there be a way to provide a dummy list or a blank list to apps?

Maybe there could be a way to prevent certain apps from being listed.

It already possible to achieve similar functionality by making another user, but it would be nice if there was an easier way to do this.

**Comment by thestinger** [comment]
It's not possible to implement this as a standalone feature. It doesn't fit into how the application model works. There are other ways to discover apps than via APIs for listing them. See https://github.com/GrapheneOS/os_issue_tracker/issues/156 for the issue tracking implementing a feature covering everything that would be needed for it to work. If you search closed issues, you'll see multiple people have filed similar issues closed as invalid / duplicates.
