### ISSUE TITLE
Clock position in status bar

### ISSUE THREAD

**Issue by neunzehnachtneun** [GrapheneOS/os_issue_tracker#425]
Hi, I recently moved from lineageos to graphene and I have to admit, it is great. There is only one minor feature I miss a lot.

In LOS it is possible to set the clock position from right position to center and left. I would really appreciate seeing this feature in grapheneos.

Thank you and cheers!

**Comment by thestinger** [comment]
This kind of thing isn't within the scope of what we implement.

**Comment by neunzehnachtneun** [comment]
That's a pity. Thank you anyway!

**Comment by bilogic** [comment]
I certainly understand it is best to keep the project scope tight and that it is about security and privacy, but it also occured to me that the underlying theme here is to "take back control", but this UI is not in our control.

Would it make sense if the UI scope is just limited to the status bar?
