### ISSUE TITLE
Visual Notifications on Apps

### ISSUE THREAD

**Issue by AgentGaryBrown** [GrapheneOS/os_issue_tracker#426]
Hello,

I am so certain this is not the right place to post this but I am not sure where to go yet. New to GrapheneOS on a Pixel 4a. So far working pretty well. Just curious about some things. Like I do not have any indication that an app has a new message for me with like a little bubble or whatever and I also have no way of know that I have any voicemails. Is there something I can change somewhere in settings that will help with the visual indications? I am on Verizon.

And if you do decide to yell at me for posting a "how to" question here, please let me know if there is another forum for that type of thing. Thank you and I appreciate all your work.

**Comment by thestinger** [comment]
See https://grapheneos.org/contact#community. You should questions on the Matrix / IRC channel.

The question doesn't make sense to me. Notifications are shown in the status bar and in the notification tray including on the lockscreen. Notification dots next to app icons are also shown by the default launcher. Voicemail depends on how the carrier chooses to show it.
