### ISSUE TITLE
SMS inconsistency across user profiles

### ISSUE THREAD

**Issue by VSfz3kkDwtjm4LAD2R24** [GrapheneOS/os_issue_tracker#429]
Hi, I'm running RQ1A.210105.003 on Pixel 4 XL. I've been noticing a strange behavior that if there're multiple profiles set up with SMS/calling enabled for non-admin users, sometimes new messages are not synced under the non-admin profiles.

For instance, an SMS message sent from another user would not be shown under profile B until I have to switch back to profile A (admin) to see the notification and go to the message app, then jump back to profile B to see the message app being updated.

This happened under both those scenarios:
A: stock message app in admin profile, Signal in another profile as default SMS app (frankly Signal doesn't even update anything at all from a particular timestamp even I manually switch back and forth. This could be due to Signal's own separated implementation of SMS)
B: stock message app in admin profile, QKSMS in another profile as default SMS app

I'm now also using stock message app in my active non-admin profile to monitor if the problem still occurs and may update below.

Any insights or help would be appreciated. Thanks.

**Comment by thestinger** [comment]
Signal is known to have broken support for SMS when using multiple profiles.

**Comment by VSfz3kkDwtjm4LAD2R24** [comment]
I wasn't aware of that. Thanks for the info. I'll be using stock message for now.

**Comment by thestinger** [comment]
Do you have any issues using *only* the stock Messaging app?

**Comment by thestinger** [comment]
Do you have any issues using only the system Messaging app?

**Comment by VSfz3kkDwtjm4LAD2R24** [comment]
I haven't used SMS extensively since yesterday, but for a couple of messages I tested with my another phone, it seems like there aren't any issues. The messages would be delivered normally.

**Comment by thestinger** [comment]
I think this is an issue with these apps rather than the OS and it also happens on the stock OS and AOSP. It's possible that it's an OS issue causing third party SMS apps to not work properly in secondary profiles, but if it is, it's not something specific to GrapheneOS.

**Comment by thestinger** [comment]
See https://github.com/signalapp/Signal-Android/issues/5151 for an example.

**Comment by VSfz3kkDwtjm4LAD2R24** [comment]
I see. Again, thanks a lot for the info!
