### ISSUE TITLE
Can't Answer Calls from Locked Screen

### ISSUE THREAD

**Issue by sjcyrn** [GrapheneOS/os_issue_tracker#434]
Cannot answer calls from locked screen on Pixel 4:

- Need to slide up the 'answer call' icon at least 3 or 4 times until call is answered. 
- Cannot pick up late without missing calls

Screen Recording: [https://u.pcloud.link/publink/show?code=XZHD2bXZVb6nmMGvbXf7JNXmR3W90YjjvDrX](https://u.pcloud.link/publink/show?code=XZHD2bXZVb6nmMGvbXf7JNXmR3W90YjjvDrX)

**Comment by thestinger** [comment]
I don't think this is a bug but rather you're not doing the gesture the way it wants.

**Comment by sjcyrn** [comment]
@thestinger I've tested it a lot more since your comment, and I think you're right. I have to make a faster swipe gesture when answering. 

I apologize for opening this issue. I've recently switched to Graphene from iOS. Thank you so much for GrapheneOS. Love it!
