### ISSUE TITLE
Long press on Signal app icon behaves differently from all other apps (doesn't show "App info")

### ISSUE THREAD

**Issue by leoheitmannruiz** [GrapheneOS/os_issue_tracker#4353]
I originally posted this at https://github.com/signalapp/Signal-Android/issues/13793. The issue was closed, with the statement that it "is likely a weird bug with the launcher". Any ideas?

---

When I long press on apps I get a pop up that says "App info". It's got a little "i" in a circle icon. When I click this icon I am shown the "App info" screen for that app in my system settings.

This is the case for every app on my phone, except for Signal.

When I long press on Signal, I get a similar pop up. However, it doesn't say "App info". It does show the same icon. I can only get to the system settings screen by clicking on the icon, not where I expect text to be. Also, when long pressing on the icon, a little pop up is shown that says "App info". This is not the case for any other app.

![normal](https://github.com/user-attachments/assets/0137bdb9-f469-472d-9ca5-7fcd61cbe8c3)
![bug](https://github.com/user-attachments/assets/a67d0e29-dd4b-4752-805d-9ca555187a3a)

**Comment by randomwithnoname** [comment]
GrapheneOS uses the AOSP Launcher so it's likely not their fault. Someone should check if the issue also exists on the Pixel Launcher (stock OS). Pixel Launcher is a fork of the AOSP Launcher and both are maintained.
