### ISSUE TITLE
Pixel 4a update to 2021.02.02.09 hanged on reboot

### ISSUE THREAD

**Issue by skagreek** [GrapheneOS/os_issue_tracker#436]
Used a daily release of 2021.01.23.03 without any major issues. It ran the auto-update to 2021.02.02.09 and I was asked to reboot. On reboot, it hanged at the GrapheneOS boot screen. I went through recovery and did a new install, but curious why the reboot failed. A friend said it could be from not waiting long enough during the update, but it said the update was complete and to reboot.

**Comment by ypid** [comment]
> A friend said it could be from not waiting long enough during the update, but it said the update was complete and to reboot.

Sounds like you were misunderstanding your friend. I think what your friend meant is to wait on the GrapheneOS boot screen. What said the update was complete?

I remember I had this, it took 5 minutes on the boot screen after the upgrade. But that was from Android 10 to Android 11 and using my own customized build.

**Comment by skagreek** [comment]
Interesting, thank you. If I remember properly, there was a notification saying it was complete and needed a reboot. I actually didn't know it was doing the update until that notification said it was complete. 

You're right on the boot screen though. I only waited 2-3 minutes and the GrapheneOS logo was actually animated. I just assumed it was stuck on an animated boot logo. I now know to wait a little longer.
