### ISSUE TITLE
Pixel 4's 16MP rear camera not detected/cannot use as primary module.

### ISSUE THREAD

**Issue by carboncopy1** [GrapheneOS/os_issue_tracker#437]
Phone model: Pixel 4
GrapheneOS release: RQ1A.210205.004.2021.02.02.09

Cannot use the 16MP (i.e. main) rear camera for photos/ module not detected. 

Steps to replicate:
1. Install OpenCamera.
2. Attempt to toggle between two rear facing cameras. 

Photos taken in either the default camera app or OpenCamera have been at 12.9MP, with no option to increase the resolution to 16MP and force a change to the 16MP module. Within OpenCamera, the toggle button does not allow for switching to the 16MP module: Camera ID = 0 always for rear facing camera.

**Comment by thestinger** [comment]
That sounds like a limitation of the camera apps, not with the OS. Is Open Camera able to use this camera on the stock OS? If not, it should really be reported to them, not to us. It's not the kind of feature we're going to add to the AOSP Camera app.

**Comment by carboncopy1** [comment]
It is only a problem that appears on GrapheneOS. For some reason, your default camera app and even OpenCamera does not detect the primary 16MP module on the Pixel 4.

**Comment by thestinger** [comment]
So you're saying that on the stock OS, Open Camera can use this extra camera?

**Comment by carboncopy1** [comment]
Yes, that is correct. Correction to my intial post: please note that the 16MP sensor is part of the telephoto lens and not the _primary_ 12MP wide angle.

**Comment by anupritaisno1** [comment]
I am the pixel 4 maintainer. I regret to inform you that I am unable to reproduce your issue as the steps to reproduce are rather vague 

What do you mean by "Attempt to toggle between two rear facing cameras."? How do you do that on stock?

Screenshots are appreciated

**Comment by carboncopy1** [comment]
Hi thanks for looking into it. I have misunderstood how the two camera modules are toggled (main handing over to telephoto). I am happy to report that everything appears to be working fine and that the app auto toggles to the telephoto when the zoom slider moves past 2.0x. Sorry for the confusion.
