### ISSUE TITLE
Customize how often the phone requires a password instead of biometrics

### ISSUE THREAD

**Issue by An-anonymous-coder** [GrapheneOS/os_issue_tracker#4377]
Occasionally, the phone will require you to enter your password if you haven't entered it in a while and have relied exclusively on biometrics. It would be nice to customize how often these requests are made (every day, every hour, etc.). This is different from an auto-reboot, and is more similar to an auto-lockdown.

**Comment by treequell** [comment]
> Yeah, I'm not sure what the "timeout" refers to either.

I believe timeout refers to the delays following multiple incorrect unlock attempts. For more details refer to:

https://grapheneos.org/faq#:~:text=The%20OS%20stores,delay%20(1%20day)
