### ISSUE TITLE
Pixel 4xl powers down randomly and wont power back on without the charger.

### ISSUE THREAD

**Issue by ElRomeo** [GrapheneOS/os_issue_tracker#438]
For the past week my Pixel 4xl has been randomly shutting down, works well most of the time when the charger plugged in (cuts out in videos and voice notes when charging) and the only way to turn it back on is with the charger. Sometimes the charger logo appears on screen with a question mark in the battery symbol. 

Is there anyone that can help?

Thanks a lot

**Comment by thestinger** [comment]
This is almost certainly a hardware issue. It sounds like you need a new battery, or least there's something wrong with the connection. This isn't happening for other users and it's extremely unlikely that it's tied to GrapheneOS.

You should try getting the battery replaced.
