### ISSUE TITLE
request: different fingerprints for options

### ISSUE THREAD

**Issue by fred0r** [GrapheneOS/os_issue_tracker#439]
it would be nice to be able to define one sprecific fingerprint for 'unlock screen' and another fingerprint just for 'confirm in apps'.

**Comment by thestinger** [comment]
I don't think this is something we want to implement. We do want to add a toggle for disabling using fingerprint unlock as a whole while still having it available for apps to use for authentication, similar to what exists for face unlock.

**Comment by fred0r** [comment]
my side of view is:
i've only added fingerprints of my wife, while i use a passphrase.
instead of emteriing the (to her unknown) passphrase - she could unlock the phone.
or is that what 'profiles' are for?

**Comment by thestinger** [comment]
It makes more sense for her to have her own user profile. The device can't be unlocked with a fingerprint on first boot or after 48 hours since the last primary unlock anyway.

**Comment by fred0r** [comment]
ok - thx

**Comment by thestinger** [comment]
After the initial unlock of the owner profile, other user profiles can be used until reboot. User profiles are useful even without actually having multiple users. They're each an isolated workspace with their own instance of apps and other data.
