### ISSUE TITLE
Conversation xmpp app.

### ISSUE THREAD

**Issue by SupremeBarmaley** [GrapheneOS/os_issue_tracker#440]
Pixel4a GrapheneOS, Conversation app work only after reboot, then work couple hours and again incoming/out coming call doesn’t work(on a screen I can see incoming call for example, but app couldn’t set connect, after reboot again everything work, but only few hours). On another android devices everything work properly.

**Comment by thestinger** [comment]
This sounds like a network issue or app bug. You'll need to put some effort into resolving the issue and explain what you've tried to resolve it.

**Comment by SupremeBarmaley** [comment]
I tried to change some configure files on my server. I use wireguard with pihole on one server and xmpp server on another one. This solution work without any bug on phone with custom ROM (LineageOS) also on a stock ROM.

**Comment by thestinger** [comment]
There's no problem with UDP in GrapheneOS.

**Comment by thestinger** [comment]
Your issue is not reproducible.

**Comment by thestinger** [comment]
You need support, not the issue tracker. It's not a GrapheneOS bug / problem.
