### ISSUE TITLE
Cannot add new APN with Mint Mobile

### ISSUE THREAD

**Issue by solaslux** [GrapheneOS/os_issue_tracker#443]
Pixel 3 XL, build RQ1A.210205.004.2021.02.07.17, 
Unable to add new APN as requested by Mint Mobile, MVNO of T-Mobile.
After recent update to OS, previously added "Ultra" APN no longer present in APN list.

Aside from APN access not working, when VPN is connected via VPN app, no internet access. Internet works with wireguard app connected. I've sent email to VPN company asking if their app is due for update and explained issue. Added since it might be related. No word back yet.

I've tried to reset my APN settings to default, reset my Wireless settings, and of course, restarted my phone. I cannot see my previously added APN nor can I add a new one. Specifically, when adding a new APN, go through the steps, hit save - it doesn't appear in the APN list and the search option doesn't reveal it either. 

Without VPN, connection works well even without the APN as instructed by carrier - the defaulted APN functions for data and MMS. Problem is why VPN app doesn't work - is it related to APN change?

Low priority since functionality is not inhibited provided previous manual setup of always-on VPN is changed to wireguard app.

**Comment by thestinger** [comment]
Carrier configurations can set how much can be modified via APN configuration. It's possible that it's not intended to be manually modified for your carrier so it isn't available. As long as it's all working fine. The APNs and carrier configuration are updated via GrapheneOS.  You should try getting logs from `adb logcat` to see if anything is going wrong. The issue may really be a lack of user interface to report that configuration isn't available.

I don't really understand what you're reporting with the VPN. It sounds like everything is working fine aside from the VPN app likely not working without Play services. There's little we can do especially without knowing the app or having any other details like logs.

**Comment by solaslux** [comment]
Apologies, VPN app is mullvad, ver 2020.8-beta1 (current). To elaborate, I filed this on graphene bugtracker because the VPN app will connect over WiFi but not over data. 
The app version is older than current grapheneOS version and it did function 3+ days ago when I noticed a strange inability to connect to the internet while on data. Disabling VPN allowed it. I got around to troubleshooting it today and found my APN had been changed. 

I included the admittedly confusing bit about wireguard app because it does allow the internet to function while connected to the same mullvad server. The VPN app hasn't changed and the wireguard app hasn't changed. But the OS has in this timeframe. 

I have also emailed the carrier, but I suspect I won't get much help from their IT. 

I'll reply back with the results from adb logcat when I have the opportunity.

**Comment by thestinger** [comment]
It's possible the VPN app disables sending data over a metered connection itself.

**Comment by thestinger** [comment]
Try marking the Wi-Fi network as metered?

**Comment by solaslux** [comment]
I marked WiFi as metered and it still shows connected and allows internet. Thanks for the suggestion.

**Comment by southwestgit** [comment]
Pixel 3a latest build. I can also confirm the loss of entered APN. Two Graphine updates ago my Mint APN was working fine. I used the recommended settings on their website and it visibly showed. Now it is visibly gone and the provided APN on sim gives lower LTE speeds.

**Comment by zizari** [comment]
Just commenting to follow, I am a new GrapheneOS user, I have Red Pocket Mobile and I am also encountering this issue.  Pixel 3a latest version.

**Comment by benflap** [comment]
Same Issue with Pixel 4a latest build.
 
For me I pressed “Reset to Default” and after that I couldn’t see or my carriers APN or add it again. I did a wifi, mobile, and bluetooth reset but that did’t work.

Hears what I got from running `adb logcat`:

```sh
02-21 16:23:19.994 23949 23949 D ApnEditor: getUserEnteredApnType: changed apn type to editable apn types: default,supl,mms
02-21 16:23:20.053  2368  2648 D TelephonyProvider: insert: exception android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: carriers.apn_set_id, carriers.mnc, carriers.mmsc, carriers.mmsport, carriers.mvno_match_data, carriers.numeric, carriers.owned_by, carriers.mcc, carriers.carrier_enabled, carriers.carrier_id, carriers.proxy, carriers.protocol, carriers.port, carriers.profile_id, carriers.roaming_protocol, carriers.bearer, carriers.mvno_type, carriers.apn, carriers.user_editable, carriers.mmsproxy (code 2067 SQLITE_CONSTRAINT_UNIQUE)
02-21 16:23:20.061 23949 23988 E ApnEditor: Can't add a new apn to database content://telephony/carriers
```

**Comment by anupritaisno1** [comment]
@benflap please mention your country/carrier

**Comment by benflap** [comment]
USA, Mint Mobile

**Comment by anupritaisno1** [comment]
The mullvad client application is a beta. It is recommended to instead generate configuration files and load those up in wireguard

The official wireguard client also updates more frequently than mullvad so you get fixes for issues faster

**Comment by zfnmxt** [comment]
Pixel 4a, USA/Mint Mobile.

Same issue--I'm unable to set the APN and Mullvad is now broken (both of these things used to work). 

The official Wireguard client doesn't work either. I tried OpenVPN over TCP and it works in a semi-borked way (have to often reconnect). Over UDP it doesn't work at all, like Wireguard.

Sorry for the lack of specifics, I can add any log/debugging info needed (just tell me what).

**Comment by thestinger** [comment]
So far, everyone with this issue appears to be on Mint Mobile.

**Comment by darktelco** [comment]
Pixel 4, Latest stable build, US, Mint Mobile.  No need to override APN and it's not an option any longer with this particular carrier.

Am able to get normal LTE speeds unless in a belljar.

@zfnmxt Wireguard works fine when I build my own VPN endpoint using standard Wireguard tools (UDP and TCP).

If you are having issues with Mullvad you may want to look at the configuration in their OpenVPN/Wireguard setup.  Have a look at Keepalive settings on either protocol.  In areas where LTE is extremely latent and introduces jitter tuning the keepalive can help.

**Comment by zfnmxt** [comment]
@darktelco Thanks for your helpful comment. Looks like setting `keepalive` to a non-zero value fixed the issue and I'm able to use Mullvad via the Wireguard app.

**Comment by thestinger** [comment]
BTW, we're aware that certain carriers intend to have editing APNs disabled. It's not unexpected.

**Comment by thestinger** [comment]
Going to close this since it's intended and we can have a generic issue about choosing not to respect this kind of carrier setup.

**Comment by linuxhelper** [comment]
My mobile data was not working either. Same issues w/ the APN on the Pixel 4a and Mint Mobile. But, I emailed Mullvad support this conversation and behold. An answer 🥰

Set the MTU value to 1280 in the Mullvad app and it's working again.

![Mullvad Issue](https://user-images.githubusercontent.com/50037005/111377086-80727f80-865d-11eb-8514-4a95506e997a.PNG)

**Comment by linuxhelper** [comment]
In a somewhat related problem—I noticed I was unable to split my Android screen between two apps when trying to enter Mint Mobile's APN settings.

Switching the system navigation from 2-button to 3-button or gesture navigation didn't give me a split screen option. Is this feature missing or am I getting it wrong?

**Comment by thestinger** [comment]
Doesn't seem related. You do split screen by pressing the icon in the recent apps screen.

**Comment by linuxhelper** [comment]
> 
> 
> Doesn't seem related. You do split screen by pressing the icon in the recent apps screen.

Thank you. I would have never figured that 😅

**Comment by johnmaher443** [comment]
I understand that this was closed, but I'm having this exact same problem with the latest stable release of GrapheneOS, Pixel 5, and Mint. Maybe not exact, because I have no Internet access via cell regardless whether I try to add an APN (never adds it) or Reset to default.

**Comment by lanhar1** [comment]
Chiming in to say that I was having this same issue. New install of GrapheneOS on a Pixel 4a (5G), hopped on wifi, put in my sim card and it would not load and APN settings could not be saved. I loaded up Surfshark as that is what I use for VPN and once I was connected I was able to enable it mobile data and 5G activated and I was all set to go.

**Comment by Charon92** [comment]
Chiming in as a UK user with the same problem on a different network.

I am on Honest Mobile (similar to Mint Mobile), using Mullvad VPN and had the same problem. Fixing it required turning off VPN, turning off Wi-Fi and manually selecting internet through the mobile network. Standard APN of GAMMA worked even though their site says it needs to be `name: Honest, apn: gamma`.

**Comment by j0ma** [comment]
Chiming as another US-based Mint Mobile user.

Phone: Google Pixel 3a
OS: newest GrapheneOS build, though my problem has been occurring for about half a year now.

Problem: I'm unable to change the APN settings to make my MMS and data settings work while in Canada. When in the US, the regular T-Mobile APN seems to work fine, but not while I'm outside the country. When I was visiting Finland, everything also worked fine, so I'm not sure what is different about Canada. Every time the problem boils down to not being able to change the APN settings to add the custom APN/edit an existing one.

For what it's worth, when I use my Mint Mobile SIM card with stock Android, everything seems to be working just fine. But while on GrapheneOS, I'm only able to send and receive texts and regular calls.

Very bizarre!

**Comment by bigOconstant** [comment]
I'm also having the same issue with mint mobile newest graphene os and a pixel 6a. It's extremely unfortunate I already bought a whole year of mint mobile.

**Comment by solaslux** [comment]
> @bigOconstant Follow the instructions on the Mint Mobile website, just make sure to set the MVNO type as GID and the MVNO GID as 756D

Sadly, I've not been able to add an APN manually. I can go through the steps to create and save an APN but then it never shows up in my APN list to choose. 

Did you make any other changes to enable actually getting 
manual APNs?

**Comment by Davy1992** [comment]
@solaslux Some guy on reddit said:

> Don't change the MNC. Android reads the MNC from the SIM and only shows APNs with MNCs matching the SIM's.

He was right, I left the MNC value at default and it works!

**Comment by solaslux** [comment]
> 

This is not something I can test since, even though I've changed to Pixel 6 pro since creating this topic, I cannot add a new APN nor can I edit the single APN that is provided by what I assume is grapheneOS and/or the eSIM.

I currently have carrier settings version tmobile_us-40000000138.54

Following these instructions: [https://www.mintmobile.com/help/how-to-configure-android-settings/](url) does not work and has not worked for many years. I can go through all of those steps but when I choose to save the new APN, it closes the dialogue and returns to the APN selection page and my new APN is not present.

You're on mint and you're able to edit your APN or add new ones?

**Comment by Davy1992** [comment]
> You're on mint and you're able to edit your APN or add new ones?

Yes, but only when I leave the MNC at the default value of 240 in my case. [I was following this guide.](https://www.mintmobile.com/help/how-to-configure-android-settings/)
And I had the same issue as you, where after saving the APN would just disappear on two different phones running different android versions (Pixel 6a android 12 and OnePlus 7T android 11).

FYI: I switched from T-Mobile to Mint only few days ago, and I'm using physical SIM cards not eSIM.
I run some speedtests on both the T-Mobile and Mint APN's and I cannot tell the difference (both are shit 2-16 Mbps).
@solaslux
