### ISSUE TITLE
Audio USB C to 3,5 mm

### ISSUE THREAD

**Issue by kaschmirrr** [GrapheneOS/os_issue_tracker#446]
Hello,
when i plug in my car audio (3.5mm) via usb type c adapter on my pixel 4 it displays a error message (compatibility error). But on my xiaomi mi 9 the adapter works fine, so its not a hardware fault. Can this be fixed in Graphene or is this Pixel related?

**Comment by sempervictus** [comment]
I've seen this problem as well, kind of annoying, but easily remedied with a bluetooth tether (with the receiver mating up to the 3.5mm jack).

**Comment by thestinger** [comment]
You need to use a *digital* USB-C adapter such as the one that comes with the phone. Pixels explicitly do not support analog USB-C audio, only digital USB-C audio. That means the adapter needs a DAC. You're trying to use an analog adapter.
