### ISSUE TITLE
Fingerprint Sensor Breakage After Last Update

### ISSUE THREAD

**Issue by sempervictus** [GrapheneOS/os_issue_tracker#447]
Using a Pixel 4, on GrapheneOS since the day it was purchased, and it looks like the last update did something to either the FP sensor interface or the software stack atop it. Fingerprint sensor works for the first 3-5 checks after a reboot, and after that fails consistently at any angle of touch. A few months ago it appeared to become more strict on the angle at which i've had to apply my finger to the pad, and has had a miss rate of maybe 10-20% (not the end of the world), but now its just straight locked out after the first few passes requiring entry of the full decryption password every time i pick up my phone (something i prefer not to do under the watchful gaze of datacenter surveillance equipment and have to do often).
Quick search through issues didn't show anything like this - any chance i'm standing on a well-known bug with some simple configuration/software fix, or is this something requiring actual debugging? If the latter, what if any data can i provide (i should still have your contact and pubkey) to assist?

**Comment by thestinger** [comment]
The fingerprint unlock system dynamically adjusts every time you successfully unlock. If you're gradually moving which part of the fingerprint you use, it will forget how to unlock the way you used to do it. You can gradually retrain it to unlock with a different part of your finger if you do that.

**Comment by thestinger** [comment]
Can you just try registering the fingerprint again if it's not working?

**Comment by thestinger** [comment]
Alternatively, it could be a gradual hardware failure, or perhaps the sensor has something on it, etc.

**Comment by sempervictus** [comment]
Thanks - sensor cleaned, not counting out hardware failure, re-enrolling and will observe its behavior.

**Comment by thestinger** [comment]
IIRC, the fingerprint sensor is basically a close range infrared camera. The face scanning on the Pixel 4 and 4 XL is a long distance 3D version of the same thing. They dropped that for the newer generations because people didn't really prefer it over fingerprint scanning overall and it was a lot more expensive to include. Maybe they'll go back to it if the price comes down or if they ever launch very high end Pixels.

**Comment by thestinger** [comment]
@sempervictus You mean a Pixel 4a right?

**Comment by anupritaisno1** [comment]
The pixel 4 doesn't have a fingerprint scanner

Please clarify if you meant pixel 4 or pixel 4a

**Comment by sempervictus** [comment]
I believe it's the XL. Wiping the prints and re-enrolling seems to have fixed it.

**Comment by thestinger** [comment]
I'd guess it had something weird on it and the dynamic learning really screwed it up over time.
