### ISSUE TITLE
RQ1A.210205.004.2021.02.06.05 internet wifi mobile network no longer works

### ISSUE THREAD

**Issue by greifm** [GrapheneOS/os_issue_tracker#448]
In RQ1A.210205.004.2021.02.06.05 according to changelog:

> rework the GrapheneOS HTTPS-based network time updates to enforce certificate expiry based on the OS build date for the whole certificate chain to avoid failing to fix significant time sync issues while still having a reasonable expiry check

Issue is due to system time & date; incorrect

Fix: 
Reset time & date manually (in clock), update to RQ1A.210205.004.2021.02.07.17

**Comment by thestinger** [comment]
This issue would have only occurred if the network connection to time.grapheneos.org broke when it first attempted to connect to the server. 2021.02.07.17 fixes it to handle this properly. The issue was in some added error reporting code.
