### ISSUE TITLE
out/build_number.txt doesn't match output target files

### ISSUE THREAD

**Issue by sjdrc** [GrapheneOS/os_issue_tracker#45]
After building, out/build_number contains ```eng.sebast.20190417.085712```
(the build user is sebastien)
Running
```
source script/envsetup.sh
./script/release.sh
```
errors out not being able to find the the output folder.

Changing out/build_number to contain ```eng.sebastien``` allows be to do a full release successfully.

**Comment by thestinger** [comment]
It sounds like you did multiple calls to make, with a different build number set for one of them. The only part that's from GrapheneOS is the tiny script/envsetup.sh script, which does this:

```
export BUILD_NUMBER=$(cat out/build_number.txt 2>/dev/null || date --utc +%Y.%m.%d.%H)
echo "BUILD_NUMBER=$BUILD_NUMBER"
```

The release script doesn't really take into account what eng builds do. It's intended for userdebug (development) and user (production). I don't think an eng build is meant to properly enforce the security model for verified boot / signing anyway.

**Comment by sjdrc** [comment]
Yeah you're right, this has nothing to do with GrapheneOS, It's happening with AOSP builds too. I actually don't know why it's creating eng builds. All I'm doing to build is
```
lunch 'aosp_taimen-user'
make -j$(nproc) target-files-package brillo_update_payload
```
Same thing if I do choosecombo instead. Odd.

**Comment by thestinger** [comment]
Follow the legacy build instructions in https://github.com/AndroidHardeningArchive/documentation/blob/master/building.md.

**Comment by thestinger** [comment]
You need to make sure you're passing it like `choosecombo release aosp_taimen user` and also clear away any existing build by removing `out/` if you want a production build.
