### ISSUE TITLE
(coral) libsurfaceflinger deleted?

### ISSUE THREAD

**Issue by vzlcn0** [GrapheneOS/os_issue_tracker#451]
is this intentional or by mistake?

https://github.com/GrapheneOS/device_google_coral/commit/c0e188b92c428c68c0fa1856d71c8f448b989cf4#diff-a26bde0bee491cf64863777a09e60c5be3fe45a52d049d3b1ea2e6f05a902124L447

**Comment by thestinger** [comment]
It's not intentional but it's simply a list of pinned files as an optimization and this part of the configuration is unused on GrapheneOS since we don't use the ART JIT.
