### ISSUE TITLE
Issues with horizontal orientation on Signal Private Messenger

### ISSUE THREAD

**Issue by j76645** [GrapheneOS/os_issue_tracker#452]
When using Signal in portrait mode while taking a photo the view finder looks normal. However, when rotating to landscape mode the view finder is distorted and nearly useless. It seems like it's changing which camera it is using when changing orientation. 

Also, in both portrait and landscape mode you cannot hold down the picture button to take a video. 

I apologize if these issues are not GrapheneOS specific. I don't know enough to know where to submit this issue. 

Issue found on Pixel 4XL with latest update to GrapheneOS and Signal.

**Comment by inthewaves** [comment]
Signal marks Pixel 4 XL as a device to not use CameraX with, but Signal uses CameraX for video recording inside the app, hence why you cannot record in the app.

https://github.com/signalapp/Signal-Android/blob/master/app/src/main/java/org/thoughtcrime/securesms/mediasend/camerax/CameraXModelBlacklist.java#L12

**Comment by thestinger** [comment]
Appears to be Signal issues, not GrapheneOS related issues.

**Comment by thestinger** [comment]
Ask them to update CameraX to the latest version and revert https://github.com/signalapp/Signal-Android/commit/3636ae76677ded687f0a45e18294ea3fc8bda851.
