### ISSUE TITLE
Can't get SMS to ring - obly vibrate

### ISSUE THREAD

**Issue by zvl12** [GrapheneOS/os_issue_tracker#459]
Main profile as well as secondary, incoming text messages (SMS) only vibrating, while all set correctly to ring AND vibrate.

Only have this issues with SMS

**Comment by thestinger** [comment]
SMS never rings. A notification sound is different from that. It sounds like you disabled this via the notification channels. I don't think there's an issue with GrapheneOS but rather you changed the configured in some way that it doesn't play a sound. You'll need to go into Settings and make sure you didn't change the notification channels, etc.

**Comment by thestinger** [comment]
Please bring this up in #grapheneos and ask others for help figuring out the cause.

**Comment by zvl12** [comment]
> Please bring this up in #grapheneos and ask others for help figuring out the cause.

In the Element/riot.im page ? or you are referring to another page ?

**Comment by thestinger** [comment]
I mean in the Matrix channel (Element), yes. I think this needs to be investigated as a potential configuration issue before treating it as a potential bug.

**Comment by zvl12** [comment]
see here 2 screenshots how its configured, to me cofiguration seems ok
(i have the same problem on 4a and 4a5G)

![Screenshot_20210220-001919](https://user-images.githubusercontent.com/79111846/108567934-d62f6280-7311-11eb-84fe-ed1c74c8e0df.png)
![Screenshot_20210220-001941](https://user-images.githubusercontent.com/79111846/108567937-d7608f80-7311-11eb-9226-c34c50f624be.png)
