### ISSUE TITLE
replace Calendar app

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os_issue_tracker#46]

**Comment by nutts0** [comment]
Would this fit? https://github.com/SimpleMobileTools/Simple-Calendar

**Comment by thestinger** [comment]
No, it needs to be a frontend to the calendar service. I don't intend to bundle more than the minimum set of apps for compatibility, and it wouldn't be able to replace AOSP Calendar, defeating the purpose of the issue.

**Comment by losuler** [comment]
[Etar Calendar](https://github.com/Etar-Group/Etar-Calendar) would be a good choice in that case then, would it not?

**Comment by thestinger** [comment]
@losuler  If it was still being quite actively developed and maintained, it would. It's not really what it once was though.

**Comment by beerisgood** [comment]
The internal calendar under Android 10 now miss the option menu so no one can addd new entrys.
Other Reddit guys confirm that: https://old.reddit.com/r/GrapheneOS/comments/d8z29p/calendar_crash_since_update/f1dvyr1/

Any ideas?

**Comment by thestinger** [comment]
I think the best approach is to disable the launcher activity and leave it as is, with a recommendation to use Etar or something else.

**Comment by thestinger** [comment]
See https://github.com/GrapheneOS/os_issue_tracker/issues/226 instead.
