### ISSUE TITLE
Android 11 Easter Egg

### ISSUE THREAD

**Issue by Pauler221** [GrapheneOS/os_issue_tracker#461]
First of all thank you for the great OS, it is awesome!
My question is: Is it possible that the cat easter egg is not working on GrapheneOS? I activated it in the settings but cannot start collecting cats.
Greetings

**Comment by thestinger** [comment]
After unlocking it, you need to hold power, go to device controls and enable the controls. It's different than it was in the past. They made it take advantage of the fancy new device controls menu in the global action dialog accessed via holding power.

**Comment by Pauler221** [comment]
Trank you!
