### ISSUE TITLE
Pixel 5 eSIM not working

### ISSUE THREAD

**Issue by FML128** [GrapheneOS/os_issue_tracker#462]
The eSIM which already is enrolled on the device is not recognised.

**Comment by thestinger** [comment]
This is tracked by https://github.com/GrapheneOS/os_issue_tracker/issues/159 already. eSIM isn't officially supported yet. The workflow of setting it up in the stock OS and then installing GrapheneOS can work but isn't something we officially support. You may need to use the debugging menu to set it up properly.

**Comment by codethief** [comment]
Hi @FML128, could you clarify: You installed your carrier's eSIM through your stock ROM, then installed GrapheneOS and the eSIM was no longer working, even after following [these steps](https://github.com/GrapheneOS/os_issue_tracker/issues/159#issuecomment-765451235)? I'm asking because I'm thinking about buying a Pixel 5 and the question whether eSIMs (and thus dual SIMs) work is a major factor in that decision.

**Comment by thestinger** [comment]
That's not really expected/intended to work yet and just seems to happen to work for most people. Can't guarantee it will continue working or that it works with all carriers, etc. We consider implementing proper eSIM support to be a priority and have funding available for it once we find a developer with the necessary skills/experience who has time available and wants to be paid to implement it.

**Comment by codethief** [comment]
@thestinger Thanks for the heads-up! I am aware of that risk and just ordered a Pixel 5 regardless – let's see how it goes. :)

**Comment by 0xattr** [comment]
@codethief  Did it work for you on your Pixel 5? I ordered a Pixel 5 too. Can you give an update about your experience with the Pixel 5 and Dual SIM? 
What I was wondering about: during flash workflow of Graphene OS one have to unlock the bootloader, but that would reset the device to factory - shouldnt that wipe the eSIM informations too?

**Comment by codethief** [comment]
@0xattr Yes! :) See https://github.com/GrapheneOS/os_issue_tracker/issues/159#issuecomment-812959152 for the details.

> but that would reset the device to factory - shouldnt that wipe the eSIM informations too?

Apparently it doesn't. It's probably because the eSIM is stored in a separate flash memory or something.
