### ISSUE TITLE
No response when tapping YubiKey via NFC

### ISSUE THREAD

**Issue by VSfz3kkDwtjm4LAD2R24** [GrapheneOS/os_issue_tracker#465]
Hi, I'm running RQ1A.210205.004.2021.02.19.15 on Pixel 5.

I have a YubiKey 5 NFC, and the system doesn't seem to have any response when tapping it on the back via NFC. Neither does it authenticate in browsers when plugging the security key directly via USB when logging in a website, tested under both Vanadium and Firefox. The only thing it does is to bring up the installed Yubico Authenticator to use OTP when I plug the key in the USB port.

On Pixel 4 XL running stock Pixel Android, both NFC and USB authentication work without a problem. I wonder if this had anything to do with some bundled support in Play Services. Any insights would be appreciated, thanks!

(The NFC reads and functions properly on Pixel 5 when using it with my NFC-supported headphones.)

**Comment by flawedworld** [comment]
FIDO U2F support is handled by Google Play Services. This likely explains your issue.

**Comment by thestinger** [comment]
See https://github.com/GrapheneOS/Vanadium/issues/61.

**Comment by VSfz3kkDwtjm4LAD2R24** [comment]
Understood. Thank you for you replies!
