### ISSUE TITLE
No other apps allowed to take pictures

### ISSUE THREAD

**Issue by mpelley92** [GrapheneOS/os_issue_tracker#466]
I updated to 2021.02.23.15 this morning on my Pixel 3 XL.

I read the changelog about changing the default flash operation, decided to check that out. 

The default camera app takes pictures fine, however, Open Camera returns a "serious camera error" when capturing, and Genius Scan crashes entirely.

I'm not sure if this change is by design or if its an issue with my operating system.

I've tried clearing storage on all three apps and it makes no difference.

**Comment by thestinger** [comment]
We're making a new release addressing the problem. Unfortunately, users who encountered this on the Beta channel didn't report the issue. We'd asked for help testing the camera on the Pixel 3, Pixel 3 XL, Pixel 3a and Pixel 3a XL and we interpreted the lack of any feedback to mean that there were no issues on those after 2 days of asking for help with it.

**Comment by thestinger** [comment]
BTW, greatly appreciate that you're reporting it. Please keep doing that. Ideally, we need people who use the Beta channel to do this.

**Comment by mpelley92** [comment]
You're very welcome. I will join the beta testing team if it helps. I use GrapheneOS as my daily driver so I have more than enough equity in it, helping would be my pleasure.
