### ISSUE TITLE
Edit: it looks like this issue was already solved. Some apps are unable to take photos on Pixel 3xl 2-19 beta update

### ISSUE THREAD

**Issue by ChickenThief** [GrapheneOS/os_issue_tracker#468]
Apps can access the camera and can take photos, but there is no working send button on the native texting app, and no send button at all on whatsapp and facebook.The camera freezes after that. Videos still seem to be supported. Affected apps include Whatsapp, Facebook messenger, and the phones native texting app. Signal was not affected. It also temporarily freezes the camera function on the app, but it unfreezes after clicking random buttons. The apps themselves still work after taking a picture.

 After taking a picture in whatsapp, the screen displays the picture but won't display anything useful to do with the picture. after clicking the back button and going back to the camera, it shows a grey screen. I restarted my phone, and updated whasapp, neither helped.

**Comment by beerisgood** [comment]
@ChickenThief see https://github.com/GrapheneOS/os_issue_tracker/issues/466

Also joining beta helps detecting bugs faster.
