### ISSUE TITLE
replace or remove Email app

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os_issue_tracker#47]

**Comment by ort163** [comment]
Why? Would be nice to know the reason. Thanks for the great work

**Comment by nutts0** [comment]
Maybe because email is by default  insecure and there is no way to fix it

**Comment by thestinger** [comment]
The AOSP email app isn't actively developed and is included in AOSP as a sample of an Email app rather than intended to be actually used in production, similar to Calendar.

**Comment by losuler** [comment]
[FairEmail](https://github.com/M66B/open-source-email) would be a good replacement, would it not? I'm not aware of any other Email app that takes security as seriously.

**Comment by madaidan** [comment]
[K-9 Mail](https://k9mail.github.io/) would be a good replacement.

**Comment by sihoang** [comment]
I think this is a good first issue for me to pick up even though it's low priority. @thestinger please kindly make a final call on what email app to use or elaborate on the acceptance criteria.

**Comment by sihoang** [comment]
I'd vote for K9 but if you think removing the email is better, I am fine with that as well.

**Comment by renlord** [comment]
PRs replacing the default email app with K9 are welcome.

**Comment by nutts0** [comment]
Why not fairemail

**Comment by beerisgood** [comment]
I agree with nutts0. FairEmail is much more maintained and works with Android 10. K9 is still on support implementation for Android 8+ (missing background service for push) ...

**Comment by renlord** [comment]
so I've gone ahead to try to remove the email package, it appears that both

packages/apps/Bluetooth/tests/unit/Android.mk
packages/apps/Gallery2/gallerycommon/Android.mk

depend on `emailcommon` which is provided through `packages/apps/Email`, so removing it outright requires some refactoring.

From a maintanability standpoint, this adds work for rebasing in future releases.

I suggest we leave it as it is. Users are free to sideload whatever email apps that best suit their use-case anyways.

**Comment by thestinger** [comment]
It's fine to still have it in the source tree.

**Comment by renlord** [comment]
I removed it in my repository: https://github.com/renlord/platform_packages_apps_Email

Please transfer it across to the organization if the changes are ok.

**Comment by thestinger** [comment]
This has been removed.
