### ISSUE TITLE
Camera - Pixel 4a 5G Wide Angle lens not being used.

### ISSUE THREAD

**Issue by skagreek** [GrapheneOS/os_issue_tracker#474]
Device: Pixel 4a 5G
Build: RQ1A.210205.004.2021.02.26.16

There are two back lenses on this device, a normal lens, and a wide angle lens. Under the stock Android 11 Camera app, there is a feature where you can select and FORCE the use of the wide-angle lens by selecting the [.6x] slider/pill in the camera app. This will take an ultra-wide (and very obviously wide) photo. In addition, while it's on [.6x], when you place a sticker on the normal lens, it does not block that normal lens, which means it is using the wide lens only (as seen in the linked photo below).

There is an additional 1x and 2x selection in the stock Android 11 camera app as well. Since there are 2 lenses, if the 1x or 2x are selected, it simply uses the one normal lens for 1x, and does a digital zoom using the same lens (not using the wide lens of course). Again, when you place a sticker on the wide lens, the 1x and 2x are not blocked, so it's using the normal lens only. 

I know that GrapheneOS is focused on top-level security, so the camera app is simple and minimal. The wide lens is really a valuable features, and the numerous other apps that I tried fail to see the wide lens. Even the Open Camera app only sees the normal lens with no option to switch to wide, even in stock android. 

As usual, thanks for all the hard work!

[3 photos, wide, normal, and zoom](https://user-images.githubusercontent.com/78545967/109735392-8ce3dc00-7b77-11eb-87f8-2d5d413d7fa0.png)

**Comment by thestinger** [comment]
> stock Android 11 Camera app

AOSP is the standard Android base, not the stock OS on a Pixel.

**Comment by thestinger** [comment]
> stock Android 11 Camera app

AOSP is the standard Android base, not the stock OS on a Pixel. The standard Android 11 Camera app is the one that we ship. Google Camera isn't the standard Android camera app. It's part of what Google adds for Pixels.

**Comment by thestinger** [comment]
I don't think this is within the scope of GrapheneOS unless we're missing functionality in the stock OS. The Camera app isn't going to be developed by us into an app with parity with Google Camera and definitely not in a hardware-specific way.

**Comment by thestinger** [comment]
I don't think this is within the scope of GrapheneOS unless we're missing functionality in the OS itself rather than an app. The Camera app isn't going to be developed by us into an app with parity with Google Camera and definitely not in a hardware-specific way. I don't think developing a camera app specialized for specific Pixel phones is a good use of our time and it doesn't need to be developed by us. It's not our focus at all, and people have the mistaken idea that we're strongly attached to Pixels when we really aren't.

**Comment by Adriankhl** [comment]
I am also investigating this issue. And I believe it is OS related?

Open Camera support the "Multiple cameras" feature (https://opencamera.org.uk/help.html#faq). As reported in this thread (https://sourceforge.net/p/opencamera/discussion/features/thread/255c1fe3/?page=0), some phone works and some don't. A guy in that thread suggested that adding `camera.aux.packagelist=org.codeaurora.snapcam,com.android.camera,com.miui.cit,net.sourceforge.opencamera` in `build.prop` fixes this. 

FreeDcam (https://github.com/KillerInk/FreeDcam) also suppose to support multiple camera but I couldn't get it to work.

If it involves `build.prop` or exposing hardware in some way to third party app, then I think it is only solvable at the OS level on an unrooted device?

**Comment by thestinger** [comment]
It doesn't work because Open Camera doesn't support the way it works on Pixels.

**Comment by thestinger** [comment]
Same issue in the stock OS. Not a GrapheneOS issue. Not a permission / privilege issue.

**Comment by skagreek** [comment]
Can confirm it has nothing to do with GrapheneOS as I got the wide lens to work using Google Camera Port.

**Comment by Adriankhl** [comment]
@skagreek Yeah I got that to work too. It is unfortunate that Google Camera needs at least a fake service (https://github.com/lukaspieper/Gcam-Services-Provider) to run so it is not ideal to have it on GrapheneOS. I will see if I can help fixing opencamera.

**Comment by Adriankhl** [comment]
A small update on this, I made a semi-functional open camera version (https://github.com/Adriankhl/opencameraR/releases/tag/WIP-20210319), zooming works with the slider, but multi-touch is not working probably.
