### ISSUE TITLE
Recent update breaks voice call functionality

### ISSUE THREAD

**Issue by centromere** [GrapheneOS/os_issue_tracker#477]
After upgrading to RQ2A.210305.006.2021.03.02.10 on a Pixel 4a, voice call functionality does not seem to work. Specifically, when I dial a number the phone app gets stuck on "Calling...". No ringing is heard. SMS and LTE (web browsing, etc) work just fine. I see in the release notes that the CarrierConfig was updated. Perhaps that could be related? I am using T-Mobile.

**Comment by beerisgood** [comment]
did you try resetting APN settings?

**Comment by thestinger** [comment]
@centromere Is it possible that you're using LTE only mode but you don't have working VoLTE?

**Comment by centromere** [comment]
@thestinger My `Preferred network type` is `LTE (recommended)`. My APN is "T-Mobile US".

**Comment by thestinger** [comment]
Have you tried resetting APN settings as suggested?

**Comment by centromere** [comment]
From the `APNs` window, I used the `Reset to default` context menu option and calling now seems to be working.
