### ISSUE TITLE
Bluetooth phone no audio in vehicle

### ISSUE THREAD

**Issue by bbhead** [GrapheneOS/os_issue_tracker#478]
RQ2A.210305.006.2021.03.02.10

Can connect to car audio through Bluetooth and make calls.  Person on other end can hear me, but I can't hear them. Was able to send/receive phone calls previously in this vehicle with this Pixel 4a running GrapheneOS and had no problems. Also, able to connect Pixel5 (non-grapheneOS) and send/receive phone calls as normal. 

I tried turning vehicle off, disconnecting and reconnecting w Bluetooth on phone.

**Comment by thestinger** [comment]
This could be caused by dropping the workaround for the audio DeviceDescriptor bug. Does it play out of the wrong speakers or not at all? Can you please try rebooting and attempting it again a bunch of times?

**Comment by bbhead** [comment]
I will try in a little bit.  Need to find a place to stop vehicle.

**Comment by thestinger** [comment]
Also, have you tried pairing again?

**Comment by bbhead** [comment]
I did restart vehicle, restarted phone, and repaired a few times.  It works now. This last time I tried listening to music first and that worked, and then made a phone call, could hear and talk fine.

**Comment by thestinger** [comment]
Don't think we can do much about this now. I think this is probably just typical Bluetooth issues. Perhaps a bug uncovered by hardened_malloc, but it's hard to know.
