### ISSUE TITLE
SIM card not recognised on Pixel 2

### ISSUE THREAD

**Issue by metronidazole** [GrapheneOS/os_issue_tracker#479]
I just flashed grapheneOS (Version: RQ1A.210205.004.2021.02.14.11) on my Pixel 2 to test VoLTE functionality and my SIM card was not recognised. Mobile network is greyed out in settings, and I don't receive a prompt to unlock the SIM. I tried an alternative SIM too with no success. I tried erasing the device and trying again but no success.

Flashing back my previous AOSP-based image restored SIM functionality.

**Comment by thestinger** [comment]
It's unclear why that would happen for you since other people aren't having any issues on the Pixel 2. No one else has reported any issues. It sounds like you may not have completely installed GrapheneOS.

Regardless, the Pixel 2 and Pixel 2 XL aren't officially supported anymore and we don't take issue reports for them or provide support.

**Comment by thestinger** [comment]
We only provide extended support releases for existing users on those devices. Those aren't the official GrapheneOS releases and those devices aren't covered by this issue tracker or supported by our main branches and tags.

This is the first time we're hearing someone say that their SIM card isn't recognized on them, but it's way past the point that we would have a reason to look into what's wrong. Chances are you just did something wrong.

Also, we didn't ship CarrierConfig vendor.xml for those devices so I wouldn't expect VoLTE to work with most carriers as it does for the official GrapheneOS releases on officially supported devices.

**Comment by metronidazole** [comment]
It flashed 100% successfully as there were no errors in the fastboot output. Plus I don't see how it could have failed given it booted with verified boot. I downloaded the build from https://grapheneos.org/releases#walleye-stable which is an official release.

In any case, I don't actually care. It was just pointing out the bug for the benefit of grapheneOS - I never intended to use grapheneOS beyond a quick flash/test.

**Comment by thestinger** [comment]
It doesn't sound like a bug. It works for all the remaining users on it who haven't migrated off and everyone else who has installed it to test. I find it hard to believe that SIM card functionality doesn't work and yet thousands of remaining users haven't mentioned anything. Regardless, removed the labels for Pixel 2 from this tracker months ago along with closing anything specific to them so it's way too late.

**Comment by thestinger** [comment]
It doesn't sound like a bug. It works for all the remaining users on it who haven't migrated off and everyone else who has installed it to test. I find it hard to believe that SIM card functionality doesn't work and yet thousands of remaining users haven't mentioned anything. Regardless, we removed the labels for Pixel 2 from this tracker months ago along with closing anything specific to them so it's way too late.

**Comment by thestinger** [comment]
It doesn't sound like a bug. It works for all the remaining users on it who haven't migrated off and everyone else who has installed it to test. I find it hard to believe that SIM card functionality doesn't work and yet thousands of remaining users haven't mentioned anything. Regardless, we removed the labels for Pixel 2 from this tracker months ago along with closing anything specific to them so it's way too late to request things related to expanding carrier support or something along those lines.

**Comment by thestinger** [comment]
Adding CarrierConfig vendor.xml is something we never got around to doing for Pixel 2 but I see no way that could cause a SIM card to not work and even if it was possible it just doesn't interest me. It's an obsolete, insecure device and our extended support releases do the job of working properly for all our users on them. None have reported any issues with their carriers, and we don't need to expand support to new carriers for them at this point.

**Comment by brozynam** [comment]
I have the same issue actually. Would appreciate support if possible.
