### ISSUE TITLE
Guage battery widget broken by RQ2A.210305.006.2021.03.06.00 update

### ISSUE THREAD

**Issue by mcrocker** [GrapheneOS/os_issue_tracker#481]
After the RQ2A.210305.006.2021.03.06.00 update restart on a Pixel 4, the Gauge Battery Widget 2020 version 6.0.13 fails and, eventually produces a message that it failed to start. The desktop widget actually renders and even stays on the screen if the option to close the app is chosen,  but the notification does disappear in that case.

**Comment by mcrocker** [comment]
The app play store URL is https://play.google.com/store/apps/details?id=net.hubalek.android.gaugebattwidget

**Comment by thestinger** [comment]
This has nothing to do with the update. You'll need to report app bugs to the app developers.

**Comment by mcrocker** [comment]
Thanks for the awesomely quick response. I was unsure if it belonged here and was reticent to reduce your S/N ratio. However since the release was so close to the last one, where the widget worked fine, and very little in the changelog looked like it came from the upstream AOSP, I figured there was a decent chance the widget failure was related to one of those changes.

Much to my surprise, there seem to be no alternatives to this app, let alone open source alternatives, though something like it is near the top of my list of apps I would like to write myself.

Thanks for all the great work that makes GrapheneOS so amazing.

**Comment by thestinger** [comment]
It definitely wasn't broken by the last release. You should try reinstalling the app and investigating possible reasons it might not be working. It definitely wasn't broken by 2021.03.06.00. It's also unlikely it was broken by the earlier release, and if it actually was, it'd very likely be broken for the stock OS too.
