### ISSUE TITLE
Multi-User App install 

### ISSUE THREAD

**Issue by Pauler221** [GrapheneOS/os_issue_tracker#484]
I set up a second user but whenever I try to install an app that’s already present on the owners profile it says “app not installed”. I am trying to install the same exact version as on the owners profile. How can I use some of the same apps like on the owner profile but on another user profile? Normally you’d just have to just “install” it again even though it’s not really installing it again but just activating it for the user. Is this a bug?

**Comment by thestinger** [comment]
No, it's not a bug. You're trying to install an older version of the app which isn't permitted. You aren't saying which app it is but I'll guess that it's F-Droid because they intentionally take the user hostile approach of publishing an out-of-date apk as the main one on their site.
