### ISSUE TITLE
Fallback option to force-enable IMS

### ISSUE THREAD

**Issue by Man-with-Arrow** [GrapheneOS/os_issue_tracker#495]
First off, here's a shortened explanation of how (from my reading and testing) IMS works. The following prerequisites must be met:

1. Carrier must support it on an infastructure level (we can assume this is true, VoLTE will become mandatory over the next few years as 2/3G networks are being sunsetted).
2. Device must support it - both software (given) and hardware (for us, this means Pixels - which support it).
3. Your account (SIM) must be flagged as IMS-enabled (user-dependant).

If these are all met, the carrier checks the device against a list of supported devices (not all carriers have such a list) and either provisions it - or doesn't. If the carrier provisions the device, VoLTE and VoWifi toggles will appear in the Settings app - and the user can enjoy IMS services.

This last part (carrier provisioning) is where the mess is. Some carrier do this via an APK, some through the Play Store, and others through CarrierConfig... 

The thing is, it's very simple to bypass this part. [Adding (or changing) a few lines in build.prop](https://gist.github.com/chenshaoju/ec18f2081cb12f85752f4c8259b54b9a) forces the toggles to appear in the Settings app - enabling the toggles will forcefully provision the device, and IMS *will work*. This has been widely verified (look for XDA threads on force-enabling VoLTE on Oneplus devices) and I've tested it myself using a Oneplus 3T - both on stock firmware and LineageOS.

This could be implemented either as an augmentation of the current CarrierConfig, as a toggle in developer options / network menu ("Force-enable IMS toggles"), or just plain enabled for all devices.

It's not perfect, and the idea may need some work, but it's much better than users being unable to continue using their device just because their carrier arbitrarily won't provision their device.

**Comment by thestinger** [comment]
This looks like a pretty bad hack and I don't think it's something we want to support. There could be serious consequences for force enabling this and users are going to blame the OS for offering something that's completely broken and not marked that way. In general, this just doesn't seem like something we want to do. As you said, VoLTE will become mandatory and carriers have to start supporting it properly.
