### ISSUE TITLE
Airplane mode doesn´t turn off location

### ISSUE THREAD

**Issue by TheBiostarfly** [GrapheneOS/os_issue_tracker#496]
I noticed that on my Pixel XL 3 when I turn my phone into Airplane mode the location isn´t turned off. I´m not quite sure if its intendet that way or its an bug. All other services are turned off e.g. Wifi, phone network, Bluetooth.

**Comment by beerisgood** [comment]
why closing and open same issue again?
https://github.com/GrapheneOS/os_issue_tracker/issues/497

**Comment by TheBiostarfly** [comment]
Sorry for that. For some reason I created two issues.

**Comment by thestinger** [comment]
It's not supposed to turn off location.

**Comment by thestinger** [comment]
GNSS is receive only and there's a toggle for location services in general rather than specifically GNSS.
