### ISSUE TITLE
Add an option to trigger the Flashlight by long-pressing the power button.

### ISSUE THREAD

**Issue by Tutturuuu** [GrapheneOS/os_issue_tracker#498]
This feature is included in LineageOS and VERY useful. Seems easy to implement but very useful.

**Comment by thestinger** [comment]
Don't really want this feature and it's not in-scope for what we work on.

**Comment by beerisgood** [comment]
> This feature is included in LineageOS and VERY useful. Seems easy to implement but very useful.

You can easily start flash light from even locked phone with tiles / quick settings in status bar.

**Comment by Peter4487** [comment]
FWIW this would be a very valuable addition for me, too. It allows using the phone as a flashlight one-handed without looking at the screen. I appreciate that it's far from core to GrapheneOS's mission. Thank you for your work!

**Comment by thestinger** [comment]
It's not wanted.
