### ISSUE TITLE
Make changing permissions involve less steps

### ISSUE THREAD

**Issue by crass** [GrapheneOS/os_issue_tracker#503]
Currently in the app permission settings, to change a setting, the permission must be select which takes one to another screen to deny or allow that permission. It would be nice to be able to toggle the permission on the screen with all the other permissions. This would make toggling permissions quicker. Since allowed and denied permissions are grouped ow, we could have toggled permissions move to the other group while the screen is active, to preserve that behavior. Or don't do that and reorder when the screen is navigated to the next time.

I have a feeling that there may be a good reason that this is currently not done this way. If so, I would love to hear it. Also, didn't see a similar issue where this was discussed.

**Comment by thestinger** [comment]
That's not possible. Many of these have 3 states and location has 4 states. It was switched away from toggles for a reason.
