### ISSUE TITLE
Can not disable default Messaging app

### ISSUE THREAD

**Issue by crass** [GrapheneOS/os_issue_tracker#504]
I would like to disable the default Messaging app to remove it from the app drawer. But this does not seem possible.

**Steps to reproduce**
1. Go to App info for Messaging app
2. Force stop app
3. `Disable` action is still disabled

I've also tried to disable the app through adb without success. Here's the output and exception code.
```
$ adb shell pm disable --user 0 com.android.messaging

Exception occurred while executing 'disable':
java.lang.SecurityException: Shell cannot change component state for com.android.messaging/null to 2
        at com.android.server.pm.PackageManagerService.setEnabledSetting(PackageManagerService.java:21055) 
        at com.android.server.pm.PackageManagerService.setApplicationEnabledSetting(PackageManagerService.java:20856)
        at com.android.server.pm.PackageManagerShellCommand.runSetEnabledSetting(PackageManagerShellCommand.java:2151)
```

Is there a reason why the Messaging app can not be disabled?

**Comment by thestinger** [comment]
It's not supported by AOSP. If SMS is implemented / available, there has to be an app dealing with it. It's also required that it works in order to use basic carrier functionality since they use SMS to send important notices, etc.

**Comment by crass** [comment]
Hmm, perhaps a future avenue would be to separate the UI component out into its own package so that the UI can be disabled and removed from the app drawer.

**Comment by thestinger** [comment]
The UI is part of what needs to be enabled for handling carrier events, etc. That's why disabling the Dialer and Messaging isn't supported.
