### ISSUE TITLE
Cannot receive sms if third party client is set to default in secondary profile

### ISSUE THREAD

**Issue by mawi675lr81** [GrapheneOS/os_issue_tracker#505]
I have QKSMS as default sms app in the secondary profile and I don't receive any messages in QKSMS app. I can see the sms in stock messaging app though. If I set stock messaging app as default, everything works fine

Although the notification for the sms only appears as banner and vibration without any sound(which was already reported by a different user)

**Comment by thestinger** [comment]
Known issue with third party SMS apps. It's not GrapheneOS-related. We recommend using the first party app. There's already https://github.com/GrapheneOS/os_issue_tracker/issues/483 about notifications from Messaging in secondary profiles.
