### ISSUE TITLE
Add toggle to turn on/off Backup Manager service in user settings

### ISSUE THREAD

**Issue by crass** [GrapheneOS/os_issue_tracker#508]
From the Owner profile, if you go to Settings > System > Multiple users and then choose a non-Owner profile, you will see a toggle for `Turn on phone calls & SMS`. It would make sense to add another toggle for `Allow backup/restore`, which would turn on the Backup Manager service for that profile. This is related to #332, but orthagonal because it its neither necessary nor sufficient for that issue.

Currently by default this would be set to off, as this preserves current behavior. I think it should be by default turned on though to prevent confusion for more common workflows. This only matters because when creating a new user profile from the status bar drop down, no options are given over profile creation. So the new user is named `New User N` and the newly created user profile is automatically switched to. Confusion could result if the Backup Manager service is not activated by default because the new profile will show the Backup as not possible to be enabled and the user may not realize that this could be enabled with this toggle.

On the other hand, when creating a new user profile via the `Multiple users` setting screen, the user is prompted for a profile name and then taken to options for that profile (eg. `Turn on phone calls & SMS` and `Switch to [USERNAME]`. The user is not automatically switched. In this work flow, the suggestion in this issue is the only thing necessary to prevent confusion over backups (IMO).

**Comment by thestinger** [comment]
I don't think it makes sense to add a toggle there. The existing issue covers this and it's something that really needs to be addressed upstream

**Comment by thestinger** [comment]
I think you're misunderstanding the existing issue. People there were just discussing ways of using it before Seedvault sets this up upstream. The point is that it's supposed to work by default. I don't see any reason for a toggle like this.

**Comment by crass** [comment]
Like I said in the OP, its neither **necessary** nor sufficient for #332. You are implicitly saying that there is no use value to disabling the Backup Manager service for non-Owner profiles.  And perhaps that's valid. That does **not** make this something covered by #332. At least now there's documentation that this was explicitly rejected. I'm fine with that.

**Comment by thestinger** [comment]
> Currently by default this would be set to off, as this preserves current behavior

No, you're just misunderstanding the situation.

**Comment by thestinger** [comment]
Seedvault doesn't implement what's needed to support backing up secondary user profiles out-of-the-box. It's not a GrapheneOS choice and there is no decision about whether or not to enable it for secondary user profiles that's available to us without forking Seedvault and developing the support for it.
