### ISSUE TITLE
Disable Automatic Reboot

### ISSUE THREAD

**Issue by Jimmy-Py** [GrapheneOS/os_issue_tracker#509]
I'm running the Pixel4A, in 

settings > system > advanced > system update settings > automatic reboot 

I have automatic reboot disabled. However, every few days when the phone is idle, it will do an auto reboot after downloading the latest patch. Any way to stop this?

**Comment by thestinger** [comment]
Automatic reboot is disabled by default and controlled by that configuration option.

**Comment by thestinger** [comment]
The updates are also hardly every few days:

https://grapheneos.org/releases#changelog
