### ISSUE TITLE
Phantom Reboot 

### ISSUE THREAD

**Issue by Jimmy-Py** [GrapheneOS/os_issue_tracker#511]
My Pixel 4a (4G) randomly reboots every few days. I mistakenly thought this was because of system updates (#509), but that it not the case. Today it rebooted right in the middle of a Signal call.

**Comment by thestinger** [comment]
Could be a hardware issue, since we haven't heard of anyone else with this issue and we know you have an identical OS install as everyone else, so it's either hardware or due to your data / configuration.

**Comment by thestinger** [comment]
Could be a hardware issue, since we haven't heard of anyone else with this issue and we know you have an identical OS install as everyone else, so it's either hardware or a bug triggered by your specific data / configuration.

**Comment by thestinger** [comment]
Not able to act on this without a way to reproduce what's likely a hardware problem.

**Comment by thestinger** [comment]
You could try capturing bug report information that's relevant but I don't think it'll be easy. There's nothing we can do with this report as is and it's not happening for anyone else.

**Comment by Jimmy-Py** [comment]
> You could try capturing bug report information that's relevant but I don't think it'll be easy. There's nothing we can do with this report as is and it's not happening for anyone else.

I'm willing to try capturing a bug report if you'd instruct me how.

**Comment by thestinger** [comment]
Developer options has a bug report capture tool at the top. You can share that with me @strcat:matrix.org via Element.
