### ISSUE TITLE
Pixel 5 - Random Freezing various tasks

### ISSUE THREAD

**Issue by LunchBoxStevieC** [GrapheneOS/os_issue_tracker#514]
Pixel 5 - Latest stable release flashed fresh.

Random freezing in various apps and web browser. No response, can't do anything then comes back a few seconds to a couple minutes later. Even on fresh daily boot.

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/os_issue_tracker/issues/442 seems fine to cover this too.

It's strange that a small subset of users are having those issues.
