### ISSUE TITLE
Pixel 5 - Haptic Feedback doesn't turn off.

### ISSUE THREAD

**Issue by LunchBoxStevieC** [GrapheneOS/os_issue_tracker#515]
Pixel 5 - Latest stable release flashed fresh.

Haptic Feedback for keyboard doesn't turn off when set to off with slider.

**Comment by thestinger** [comment]
With which slider?

**Comment by thestinger** [comment]
In the keyboard settings, it has a toggle for vibrate on keypress. Have you disabled that?

I don't think the OS notification vibration and touch feedback settings control it. Those are for notifications and the System UI touch feedback. Apps can still use vibration on their own.

**Comment by LunchBoxStevieC** [comment]
Touch Vibration  (Haptic Feedback for Tap, keyboard and more)  is where I was turning it off.

I found the setting you mentioned and that fixed it.  Thank you!!!!   Hate that feature.

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/os_issue_tracker/issues/517 filed instead.
