### ISSUE TITLE
Camera issue on pixel4a

### ISSUE THREAD

**Issue by Randomeruis** [GrapheneOS/os_issue_tracker#521]
When switching from rear to front or front to rear camera on 4a the camera app will just have black screen.. This will fix after reboot and only occur about 3rd of the time.

**Comment by thestinger** [comment]
This sounds like a hardware issue, not a software one, and there isn't much we can do about a flaky hardware connection to the camera. This is a common symptom of fall damage or water damage. You can search for this with the Pixel 4a and see that other people have the issue on the stock OS.

**Comment by Randomeruis** [comment]
It has been like this sence I bought the device and flashed GrapheneOS. Just now couple months after reporting this because noticed nobody else is talking about this. But will search if people on stock have same issue.

**Comment by thestinger** [comment]
The phone might have been damaged in transit. It's a common symptom of a hardware issue for perhaps 1% of Pixel phone owners. It's more common on the devices like the Pixel 4a without strong water/dust protection.

**Comment by thestinger** [comment]
I would expect it to get progressively worse until it fails completely.

**Comment by thestinger** [comment]
I would expect it to get progressively worse until it fails completely and can't connect to the camera sensor anymore.
