### ISSUE TITLE
Enable grid options

### ISSUE THREAD

**Issue by Exilion666** [GrapheneOS/os_issue_tracker#523]
Hello. In main screen / grapheneOS launcher settings there is an "enabble grid options" option, but i can not find where is it possible to change grid options. Have I misunderstood function of this toggle or where can i finde further settings for the grid? Thanks a lot

**Comment by Exilion666** [comment]
Ok, should i close issue, or let it leave as reminder for now?

**Comment by thestinger** [comment]
It's on our radar and I'd rather close it for now until it's figured out what really has to be done for this, and the rest of it.

**Comment by MaxHillebrand** [comment]
feature request bump, specifically more dense grid size, like `7x7` `8x8` `5x7` etc.
