### ISSUE TITLE
Enhanced, combined PIN and Password Security

### ISSUE THREAD

**Issue by janvantonder** [GrapheneOS/os_issue_tracker#524]
- Having a PIN code (or a fingerprint) for unlocking the phone is practical however not as secure as a good password. 
- Having a good password for authentication is more secure but not very practical.

I would find it extremely useful if I could define both a modestly secure PIN and a strong password.

- In normal use I can use my modest PIN (or fingerprint) for unlocking the phone
- If I lock the phone down then the authentication method changes to strong password
- If someone tampers with my phone and enters an incorrect PIN (or fingerprint) three times -> the authentication method changes to strong password.

This would greatly enhance the security of the phone without sacrificing practicability.

**Comment by thestinger** [comment]
There's already https://github.com/GrapheneOS/os_issue_tracker/issues/28 filed. It was originally filed in 2016. What's needed are developers to work on these things, not the ideas.
