### ISSUE TITLE
GrapheneOS breaks 2.4Ghz wifi pixel4a

### ISSUE THREAD

**Issue by JorySchossau** [GrapheneOS/os_issue_tracker#526]
[I searched open and closed issues]

Is Stable simply 1 update behind AOSP? Wondering if there's a fix right around the corner, otherwise I'm recording this issue here.

With stock AOSP in whatever update state I got my phone in, 2.4Ghz did not work. Updating with the latest security patches and such OTA from Google made 2.4Ghz work for all reboots tested. Then installing GrapheneOS made 2.4Ghz nonfunctional again. Will there be an OTA likely to fix this if it was fixed in AOSP? Or is this a deeper issue related to GrapheneOS alterations to AOSP and it will never work?

**Comment by thestinger** [comment]
> Is Stable simply 1 update behind AOSP?

No. You can see that it's up-to-date...

https://grapheneos.org/releases#stable-channel

> With stock AOSP in whatever update state I got my phone in, 2.4Ghz did not work. Updating with the latest security patches and such OTA from Google made 2.4Ghz work for all reboots tested.

It's probably an issue with the network and it simply isn't reliable.

> Then installing GrapheneOS made 2.4Ghz nonfunctional again. Will there be an OTA likely to fix this if it was fixed in AOSP? Or is this a deeper issue related to GrapheneOS alterations to AOSP and it will never work?

It's likely an issue with your network (probably the router) which you're blaming on the OS.
