### ISSUE TITLE
Calender App disappeared

### ISSUE THREAD

**Issue by deep-ocean-fish** [GrapheneOS/os_issue_tracker#534]
I realised that the GrapheneOS stock calendar app has suddenly vanished. It says under Settings > Apps > show system apps that it is still installed and not disabled. New profiles also do not have the calendar app. 
Is this a bug?

**Comment by thestinger** [comment]
It's intended that there's no longer a launcher icon. I recommend using Etar or another option.

**Comment by thestinger** [comment]
We kept it around so that there's an implementation of viewing calendar events, etc. but in a way that avoids making people think we expect anyone to use that bare minimum sample app for any real usage.

**Comment by deep-ocean-fish** [comment]
Thank you for the fast answer!
