### ISSUE TITLE
Bluetooth connected keyboard reboots Pixel 4a when disconnected by powering off keyboard

### ISSUE THREAD

**Issue by motovate** [GrapheneOS/os_issue_tracker#535]
Hello, I have two Pixel 4a phones and Logitech K380 and K480 bluetooth keyboards. A keyboard connected via bluetooth and disconnected by switching the keyboard off will reboot the phone. This happens with both keyboards and both phones. My work around is to disconnect by turning off bluetooth on the phone rather than power off the keyboard. One phone is mine and the other is my (non-techie) wife's. We really enjoy the privacy provided by GrapheneOS. Thank you very much!

**Comment by motovate** [comment]
Version: RQ2A.210305.006.2021.03.30.02

**Comment by thestinger** [comment]
https://issuetracker.google.com/u/0/issues/184526464

**Comment by thestinger** [comment]
Think this is the same issue as https://github.com/GrapheneOS/os_issue_tracker/issues/458.
