### ISSUE TITLE
Bluetooth Keyboard causes random restarts

### ISSUE THREAD

**Issue by python4lyfe** [GrapheneOS/os_issue_tracker#537]
As the title says, when I attach my travel Bluetooth keyboard to my phone, it will cause my phone to restart randomly. I tried to look and see if there are any error log files that I could attach on my phone - but couldn't find any. This is the first time I've attempted to attach the keyboard to my phone since installing GrapheneOS on it. I do still have Developer Options enabled.

Below are specifications that I believe may be relevant, please let me know if you need anything else:

Phone: Google Pixel (4a) 5G
Build Number: RQ2A.210405.005.2021.04.05.20

Keyboard: iClever Bluetooth keyboard
Model: HB088

**Comment by thestinger** [comment]
See https://github.com/GrapheneOS/os_issue_tracker/issues/458.
