### ISSUE TITLE
Wallpaper gets vertically stretched

### ISSUE THREAD

**Issue by Toby4213** [GrapheneOS/os_issue_tracker#540]
Device: Pixel 5

As the title says, the wallpaper image gets vertically stretched when applied using com.android.wallpaperpicker or the gallery.
The Image has the usual 16:9 aspect ration: https://wallhaven.cc/w/13xk23

![Screenshot_20210412-162439](https://user-images.githubusercontent.com/22265595/114411819-d11dbf80-9bac-11eb-99de-380b7bbb3273.png)

**Comment by thestinger** [comment]
Doesn't look like anything is being stretched. Seems to be working as intended. It's being zoomed to fit the screen ratio.

**Comment by Toby4213** [comment]
No I am 100% certain that the aspect ration of the image isn't preserved. If you look at the planet in the above picture it isn't round anymore. I made my own image by taking the dimensions from a screenshot of the phone, which means the wallpaper should fit perfectly, but it doesn't. The grid below is a bit stretched vertically after applying the wallpaper. I added the red text to show that the grid is indeed stretched.
![stretch_proof](https://user-images.githubusercontent.com/22265595/114534745-9caf0f80-9c4f-11eb-9ec3-4411ac036fcc.png)

**Comment by thestinger** [comment]
Try setting it via the gallery app instead of that wallpaper app. There are multiple ways to set it.

**Comment by Toby4213** [comment]
It doens't matter what I use to set the wallpaper. In both cases I get the same vertical stretching. I think that in both cases the wallpaperpicker app is used to set the wallpaper. I think the problem is the "Set wallpaper" screen which doens't know the right dimensions of the home screen.
Here the way I set the image using the gallery: https://youtu.be/Khq0vdYrmE8 I verified that the wallpaper is still stretched.

**Comment by thestinger** [comment]
I'd suggest cropping it to the correct resolution first in that case.

**Comment by thestinger** [comment]
We're going to be moving to the newer AOSP wallpaper app and we're not going to be developing the old one. The issue is going to remain closed for that reason. It's not a bug but rather something not working the way you want, and it's not something we're going to have around for much longer anyway.

**Comment by Toby4213** [comment]
Alright, that's ok. In that case I am excited for the new wallpaper app! 😄
