### ISSUE TITLE
LTE-only mode setting missing.

### ISSUE THREAD

**Issue by Penguin-Guru** [GrapheneOS/os_issue_tracker#541]
This seems like it could be intentional but I haven't been able to figure out why. [This webpage](https://grapheneos.org/usage#lte-only-mode) says the setting, `Preferred network type` should be in `Settings --> Network & Internet --> Mobile network`, but I don't see it.

Randomly digging through the code, these parts seem like they could be relevant (but I could be completely wrong):

https://github.com/GrapheneOS/platform_packages_apps_Settings/blob/9421b8fce2575b2c31adb2b77956cc55cb926f3d/src/com/android/settings/network/telephony/PreferredNetworkModePreferenceController.java#L49

https://github.com/GrapheneOS/platform_packages_apps_Settings/blob/11/src/com/android/settings/network/telephony/EnabledNetworkModePreferenceController.java#L227

Could someone help me understand what's going on? If this is intentional, what is the reason?

Since some people have said this is likely a carrier issue, my phone, SMS, and MMS all seem to work fine. My status bar shows WiFi and radio service, but the WiFi symbol changes to "LTE" when I turn WiFi off. It doesn't make sense to me that the carrier should have control over what settings are visible to me, and someone did confirm that Graphene does not implement privileged management drivers that are managed by the I.S.P. The conditional code I referenced above seems to suggest that some settings are only visible in certain network modes but I could be misinterpreting that. Would this mean that the settings' visibility are determined based on I.S.P. signalling, such as my service plan (which does support LTE, 3G, 4G, etc.)? It doesn't make sense to me that LTE-only mode settings would be hidden based on radio coverage in my immediate area, but the setting did not appear after I switched off WiFi anyway. I can't think of anything else.

**Comment by thestinger** [comment]
> and someone did confirm that Graphene does not implement privileged management drivers that are managed by the I.S.P

That's misinformation.

**Comment by thestinger** [comment]
Some carriers have their APN configuration or CarrierConfig setup configured to hide certain options. GrapheneOS currently doesn't override those values or ignore them. It's something we eventually intend to do but it has to be done carefully.

**Comment by thestinger** [comment]
Replaced with https://github.com/GrapheneOS/os_issue_tracker/issues/542 although it should probably be a more generic issue. There are other assorted settings not always available depending on the carrier. Exposing some of it might cause breakage though.

**Comment by Penguin-Guru** [comment]
Ok, thanks for the explanation.

I don't know what your plans are but it should at least be safe to display those settings as "greyed out" or "disabled". Maybe some could have a slightly different background colour or some kind of alarming icon. That's the best I can offer.

**Comment by Peter-Easton** [comment]
> > and someone did confirm that Graphene does not implement privileged management drivers that are managed by the I.S.P
> 
> That's misinformation.

Sorry about that.

**Comment by Penguin-Guru** [comment]
No worries. It seems like that is the goal. :)
