### ISSUE TITLE
Calendar widget displaying date doesn't update

### ISSUE THREAD

**Issue by adrienlacombe** [GrapheneOS/os_issue_tracker#543]
Hello, I hope this is the right place to raise this type of issue.
I have added the Calendar widget on my main screen and I noticed the date displayed at the top of the widget never updates. The events are appearing and disappearing fine.
Not sure how I can be of any help to help solve this issue, please let me know.
Thank you vm

**Comment by thestinger** [comment]
You should use a proper calendar app. We'll remove this widget since it's not maintained/developed. See https://github.com/GrapheneOS/os_issue_tracker/issues/544.

**Comment by adrienlacombe** [comment]
Thank you, will do!
