### ISSUE TITLE
[Google Play Services] Attempting remove Google account leads to "This change isn't allowed by your admin"

### ISSUE THREAD

**Issue by silasdavis** [GrapheneOS/os_issue_tracker#673]
I have followed the instructions installing each of

- com.google.android.gsf
- com.google.android.gms
- com.android.vending (using SAI to install this one)

I then opened Play store an logged in. This adds the Google account to the on-device accounts

Later I decide I want to remove the Google account; when I go to `Settings > Accounts`  and try to delete my Google account I am told "This change isn't allowed by your admin"

**Comment by thestinger** [comment]
This is happening in a secondary profile, right? For now you can uninstall the 3 apps.

**Comment by silasdavis** [comment]
I added to my primary profile, I was happy with the convenience tradeoff there but maybe that was a mistake. Still feels like I should be able to remove the account.

**Comment by thestinger** [comment]
You can remove the account. Remove the apps. You're misunderstanding how accounts work.

**Comment by silasdavis** [comment]
Remove which apps, Google play?

> You're misunderstanding how accounts work.

In what way?

 > "This change isn't allowed by your admin"

I am the admin. Are you saying this is not a bug?

**Comment by thestinger** [comment]
Remove the Google Play services apps implementing the account and then install them again.

> I am the admin. Are you saying this is not a bug?

It's lack of compatibility shims, not a bug. I'm pretty sure that error is caused by Play services, not the OS.
