### ISSUE TITLE
No update when VPN enabled and set to unmetered

### ISSUE THREAD

**Issue by daradib** [GrapheneOS/os_issue_tracker#73]
If I set Permitted networks in System update settings to "Unmetered", device does not receive system updates. Device is connected to wifi. If I change Permitted networks to "Not roaming" or "Any", Seamless Update Client begins downloading an update.

I have tried changing the wifi network details to "Treat as unmetered" instead of "Detect automatically". I have tried different wifi networks and ISPs. I have tried turning off mobile data and making sure internet is really accessible over wifi.

    $ adb shell dumpsys connectivity
      NetworkAgentInfo{ ni{[type: VPN[], state: CONNECTED/CONNECTED, reason: agentConnect, extra: (none), failover: false, available: true, roaming: false]}
    [...]
    nc{[ Transports: VPN Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&VALIDATED&NOT_ROAMING&FOREGROUND&NOT_CONGESTED&NOT_SUSPENDED
    [...]
      NetworkAgentInfo{ ni{[type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: (none), failover: false, available: true, roaming: false]}
    [...]
    nc{[ Transports: WIFI Capabilities: NOT_METERED&INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&VALIDATED&NOT_ROAMING&FOREGROUND&NOT_CONGESTED&NOT_SUSPENDED
    [...]

    $ adb shell dumpsys jobscheduler
    [...]
        JobInfo:
          Service: app.seamlessupdate.client/.PeriodicJob
          PERIODIC: interval=+4h0m0s0ms flex=+4h0m0s0ms
          PERSISTED
          Requires: charging=false batteryNotLow=false deviceIdle=false
          Network type: NetworkRequest [ NONE id=0, [ Capabilities: NOT_METERED&INTERNET&NOT_RESTRICTED&TRUSTED&VALIDATED Unwanted:  Uid: 10028] ]
          Backoff: policy=1 initial=+30s0ms
          Has early constraint
          Has late constraint
        Required constraints: TIMING_DELAY DEADLINE CONNECTIVITY [0xd0000000]
        Satisfied constraints: TIMING_DELAY DEVICE_NOT_DOZING BACKGROUND_NOT_RESTRICTED [0x82400000]
        Unsatisfied constraints: DEADLINE CONNECTIVITY [0x50000000]

If I disable "always-on VPN" and "block connections without VPN", Seamless Update Client begins downloading an update. So is "CONNECTIVITY" unsatisfied because the VPN connection is considered NOT_ROAMING instead of NOT_METERED like the underlying wifi connection?

Device: Pixel 3 XL
Version: PQ3A.190505.002.2019.05.18.20

**Comment by thestinger** [comment]
This is how it's supposed to work. By default, a VPN is considered to be a metered network. API 29+ and above provides a way for VPN apps to mark themselves as not being metered networks, so you'll have the feature you want in Android Q once the VPN app adopts it:

https://developer.android.com/reference/android/net/VpnService.Builder#setMetered(boolean)

**Comment by thestinger** [comment]
This is how it's supposed to work in Android P and earlier. There wasn't a way to set whether a VPN should be considered as a metered networks, so they'll all considered metered networks. It's not an issue with the Updater app but rather a feature that's not implemented by Android.

Android Q changes how this works and API 29+ provides a way for VPN apps to set whether or not they're a metered network:

https://developer.android.com/reference/android/net/VpnService.Builder#setMetered(boolean)

**Comment by thestinger** [comment]
This is how it's supposed to work in Android P and earlier. There wasn't a way to set whether a VPN should be considered as a metered networks, so they'll all considered metered networks. It's not an issue with the Updater app but rather how the OS VPN functionality works.

Android Q changes how this works and API 29+ provides a way for VPN apps to set whether or not they're a metered network:

https://developer.android.com/reference/android/net/VpnService.Builder#setMetered(boolean)

**Comment by thestinger** [comment]
This is how it's supposed to work in Android P and earlier. There wasn't a way to set whether a VPN should be considered as a metered network, so they're always considered metered networks as a conservative way of handling it. It's not an issue with the Updater app or the JobScheduler implementation in GrapheneOS. It's how this works in Android.

Android Q changes how this works and API 29+ provides a way for VPN apps to set whether or not they're a metered network:

https://developer.android.com/reference/android/net/VpnService.Builder#setMetered(boolean)

**Comment by daradib** [comment]
Thanks for the explanation! As a workaround, I will try changing Permitted networks back to Any and disabling Background data for Seamless Update Client under App info -> Data usage.

**Comment by bitamarghzar** [comment]
سلام آیا میتوان در تنظیمات نام نقطه دستیابی پراکسی خواست را تعیین کرد آیا این کار وی پی ان انجام میدهد
