### ISSUE TITLE
Deleted profiles leave app detritus/registration behind but unreachable

### ISSUE THREAD

**Issue by cjtenny** [GrapheneOS/os_issue_tracker#737]
- I created and used secondary profiles to install apps.
- I deleted the profiles
- The apps were no longer visible to the owner as installed
- I created new profiles, then installed the same apps from before in those profiles.
- Installation was presented as "update to this existing application" for some of the apps that had been updated since installed in profiles that were deleted.

I don't know what remnants of those apps are around, but as mentioned they don't show up as installed applications to the owner profile.

Some of the profiles had the same name and passphrase as before; I deleted and recreated profiles to change their order in the profile selection drop-down.

**Comment by cjtenny** [comment]
11

**Comment by thestinger** [comment]
Android 12 is now available in the Stable channel. Can you check if you still have this issue? I'd say it's about 50/50.
