### ISSUE TITLE
ATT/FirstNet Wireless Calling

### ISSUE THREAD

**Issue by temp44221** [GrapheneOS/os_issue_tracker#739]
The app to enable wifi calling on ATT has been open sourced as of Android 12. It appears to still not function on the Beta 12 GOS build. Is this the right place to request that enhancement?
https://source.android.com/devices/tech/connect/ims-service-entitlement

**Comment by thestinger** [comment]
It likely only works with Play services. Not something we'll include in the OS by default.

**Comment by boozedog** [comment]
> Does that mean installing play services may allow it to function? If so, I can try that in a new user profile

@temp44221 what app are you talking about to enable wifi calling on AT&T?

**Comment by Zanthed** [comment]
@boozedog https://grapheneos.org/usage#sandboxed-google-play

The Carrier Services app may or may not be needed.
