### ISSUE TITLE
ProtonVPN crashing while setting up connection

### ISSUE THREAD

**Issue by nberlee** [GrapheneOS/os_issue_tracker#74]
Not sure if the logs are usefull enough, please tell me how to provide more usefull info.

ProtonVPN actually behaves the same as the StrongSwan VPN client on F-Droid when connecting to an IKEv2 (app crash, no VPN). Probably because ProtonVPN uses an own compiled strongswan version looking at their logs.

I can also provide logcat of strongswan, but its not configured anymore, have to do that tomorrow, but I am almost positive its the same issue.
[protonvpn graphenos applog.log](https://github.com/GrapheneOS/os_issue_tracker/files/3267553/protonvpn.graphenos.applog.log)
[protonvpn grapheneos adb.log](https://github.com/GrapheneOS/os_issue_tracker/files/3267554/protonvpn.grapheneos.adb.log)

**Comment by thestinger** [comment]
Can you try again the latest release?

**Comment by dallemon** [comment]
Tested. 
ProtonVPN works now.
Had previously tried contacting ProtonVPN and they just recommended using OpenVPN app and a config.
