### ISSUE TITLE
Love Live SiF crash when starting

### ISSUE THREAD

**Issue by pinembour** [GrapheneOS/os_issue_tracker#77]
I'm using a Taimen with the latest release of GrapheneOS. When I launch this game, it crashes after skipping the home screen. This problem does not occur on unmodified AOSP Pie.
However I think I had a similar problem when testing Android Q beta 1 and 2, I'm not sure though.

Here's the [logcat](https://pastebin.com/7UMfGuKG).

**Comment by thestinger** [comment]
This looks like an issue caused by lack of Play Services due to lack of their in-app billing implementation to me. I'm not convinced that this is something to do with GrapheneOS. If it sometimes works without Play Services, that sounds like a bug in the app, not the OS.
