### ISSUE TITLE
4G preferred network option missing

### ISSUE THREAD

**Issue by tekofu** [GrapheneOS/os_issue_tracker#78]
The option at **_Settings > Network & Internet > Mobile Network > Preferred network type_** displays 3G and 2G only. Enabling one of these will make it unable for the user to go back to using 4G. This can be fixed only by resetting the network settings at **_Settings > System > Reset Options > Reset Wi-Fi, mobile & Bluetooth_** and thus resetting the settings for Wi-Fi and Bluetooth as well.

I think this is an upstream issue in AOSP but cannot find any mention of this issue online. Another GrapheneOS user has replicated this and when troubleshooting my SIM on a stock Pixel 2 I cannot replicate it, probably as Google have modified the Settings app for their version and fixed this if indeed it is an AOSP bug.

I appreciate this is a small problem but thought filing an issue would be best.

![Screenshot_20190611-161704](https://user-images.githubusercontent.com/47366807/59284848-e4843a80-8c64-11e9-84b9-dcbbf2d33848.png)

**Comment by nutts0** [comment]
As a workaround u can use this command here and set you're preferred network option.

*#*#4636#*#*

**Comment by thestinger** [comment]
That's not a persistent setting though.

**Comment by nutts0** [comment]
Yes you have to do that after each reboot. I use this to set it to only 4g.

**Comment by thestinger** [comment]
Is this still an issue in the latest release based on Android 10?

@nutts0 @tekofu

**Comment by nutts0** [comment]
I can't test at the moment. I'm on airplane wifi mode when needed. Will get a sim and tell you

**Comment by Kokokokoka** [comment]
I have LTE 3G 2G in the mobile data prefs

**Comment by thestinger** [comment]
It may be a carrier-specific issue, but for now I'm closing this as it appears resolved.
