### ISSUE TITLE
Issues starting Nextcloud

### ISSUE THREAD

**Issue by dwa2010** [GrapheneOS/os_issue_tracker#80]
Hi, I've attached the output from starting nextcloud, which exits with signal 9. This is following the request for logcat for unexpected behaviour on reddit.

java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider (expected, permission not granted/requested)

android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed (Is this part of play services?)

ThemeUtils: java.lang.NoSuchFieldException: No field mCursorDrawable in class Landroid/widget/Editor

nextcloud_logcat.txt](https://github.com/GrapheneOS/os_issue_tracker/files/3293942/nextcloud_logcat.txt)

**Comment by dwa2010** [comment]
Pixel 2 running 2019.06.14.02

**Comment by thestinger** [comment]
It looks like you've disabled the Vanadium app, so you don't have a WebView.

**Comment by dwa2010** [comment]
Hi, many thanks for your initial triage. Vanadium wasn't disabled, but on some further digging I uncovered that Shelter was the cause. In developer settings the "WebView implementation" value was Vanadium, but with the value "uninstalled for user Work profile". Removing the profile using "Accounts->Remove work profile" has resolved the issue, until I can put some time aside to look at work profiles in more detail.

Hopefully this should be enough information for others who may experience the same problems.
