### ISSUE TITLE
Network privacy setting does not represent correct setting

### ISSUE THREAD

**Issue by ph00lt0** [GrapheneOS/os_issue_tracker#830]
The privacy setting under network details in settings app does shows:
```Use per-connection randomized MAC (default)```
Instead of the setting I chose for this specific network which is the per-network randomized MAC

The behavior hasn't changed, the MAC stays the same when reconnecting, just the setting in details menu and edit menu do not reflect the right value. 

Devices tested:
Pixel 4a
SP1A.211105.004.2021112404

**Comment by thestinger** [comment]
Not able to replicate any issues with this feature.

**Comment by alex-resist** [comment]
Could replicate the bug in https://github.com/GrapheneOS/os-issue-tracker/issues/847
