### ISSUE TITLE
disable dynamic kernel module support for Pixel 3, Pixel 3 XL, Pixel 3a, Pixel 3a XL

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os_issue_tracker#84]
The initial attempt blocked the boot process, and I don't have a Suzy-Q debug cable to resolve issues like this right now beyond taking shots in the dark.

**Comment by thestinger** [comment]
This is now an issue for the Pixel 3 and Pixel 3 XL with the upgrade to Android 10. On the positive side, the issue can potentially be identified with a comparison, but there were a *lot* of changes.

**Comment by ab123321** [comment]
Hi Daniel, do you happen to know what commands should be used for connecting to kernel kmsg? I have a Suzy-Q cable, but for my Pixel 3 it opens only Titan M console :/

**Comment by thestinger** [comment]
@ab123321 You have a ChromeOS Suzy-Q cable, not an Android Suzy-Q cable. It's unfortunately not an issue of commands. The Android one needs more hardware than the ChromeOS one.

**Comment by ab123321** [comment]
@thestinger That's very unfortunate... Do you know what kind of upgrade is required to make it work?

**Comment by thestinger** [comment]
No, but there are people on the GrapheneOS IRC channel who know how to do it.

**Comment by thestinger** [comment]
This should be fixed now.
