### ISSUE TITLE
Bitwarden unusable, crashes during search

### ISSUE THREAD

**Issue by tjm00** [GrapheneOS/os_issue_tracker#86]
The crash is consistent and reproducible. To reproduce, try searching the vault for any string. Shortly after the list populates, the application crashes. This is with the latest stable release on a Pixel 3a.

[bitwarden-crash-2.logcat.txt](https://github.com/GrapheneOS/os_issue_tracker/files/3317254/bitwarden-crash-2.logcat.txt)

**Comment by tjm00** [comment]
This is with the latest stable release on a Pixel 3a.

**Comment by thestinger** [comment]
This is the same compatibility issue as https://github.com/GrapheneOS/os_issue_tracker/issues/81 and is resolved in the development branch so it will be fixed in the next release.
