### ISSUE TITLE
Hotspot & tethering option is disabled (greyed out) on Pixel devices

### ISSUE THREAD

**Issue by keshto** [GrapheneOS/os_issue_tracker#90]
On the Pixel sailfish `Network & internet` options the `Hotspot & tethering` option is disabled. If one opens the option via the quick tile and tries to enable any of the hotsport/tethering options it fails `TetherProvisioningAct: Provisioning app is configured, but not available`.

Looks like the tether provisioning apk is missing. Alternatively, one could set the `noprovisioning` property to true `setprop net.tethering.noprovisioning true`, but that requires root.

**Comment by keshto** [comment]
Possibly related? https://github.com/GrapheneOS/os_issue_tracker/issues/70

**Comment by thestinger** [comment]
Yes, I'd rather use the existing #70 issue for this.
