### ISSUE TITLE
App switcher sometimes reverts to the old style

### ISSUE THREAD

**Issue by expobar** [GrapheneOS/os_issue_tracker#93]
![img_7707823934785575265](https://user-images.githubusercontent.com/52035600/61031413-0d2d5a80-a3f2-11e9-8cfc-47de73d1d34d.jpg)

**Comment by nutts0** [comment]
What device is this?

**Comment by thestinger** [comment]
I've never seen it either on any of the devices.

**Comment by thestinger** [comment]
Are you using the standard included launcher, or an alternative one? If you're using a different one, I think this is expected.

**Comment by expobar** [comment]
> Are you using the standard included launcher, or an alternative one? If you're using a different one, I think this is expected.

Pixel 2. In one profile I do use the Microsoft launcher but the one in the screenshot is a newly setup profile. This issue do pop up on my main profile sometimes and it normally goes back to normal. Although sometimes even a reboot won't change it back to modern style but it eventually change on its own back to modern.

**Comment by expobar** [comment]
> If you're using a different one, I think this is expected.

It does comes up more often on Microsoft Launcher, but as usual it kinda gets fixed on it's own.

**Comment by thestinger** [comment]
@expobar Is this still an issue on the latest release based on Android 10?

**Comment by expobar** [comment]
@thestinger It's not popping up anymore. Microsoft Launcher always triggers this on Android 9.
