### ISSUE TITLE
Unset CONFIG_QCOM_DLOAD_MODE

### ISSUE THREAD

**Issue by restrectedpin** [GrapheneOS/os_issue_tracker#97]
CONFIG_QCOM_DLOAD_MODE should not be enabled in production

**Comment by thestinger** [comment]
It only makes `adb reboot edl` supported. The documentation claiming that it will reboot to download mode on a kernel panic isn't accurate and it would need to explicitly configured that way. I don't need to support a unified kernel for production and development builds like Google, but I don't really see any issue with this configuration option in particular that would make it worth prioritizing.

**Comment by thestinger** [comment]
I think this is meant to be this way on Pixel devices. It's tied to something like bootloader lock state. I don't think we want to mess with this right now.
